// Figuren-Zuordnung (Phase 2 des Charakter-Neubaus): Familie, Größe, Farben, Signature-Element, Teamzonen,
// Proportionen und Persönlichkeit jeder Figur. Einzige Quelle für docs/DISTINCT_MATRIX.md, client/js/characters/system.json,
// die Design-Briefs (docs/briefs/) und das Build-Skript. Regeln: docs/CHAR_SYSTEM.md.
//
// Felder:
//   fam     Silhouetten-Familie (siehe FAMILIES in system.mjs)
//   h       sichtbare Höhe in Feldern (Ruhepose, Fuß bis Scheitel; Flieger ohne Schwebehöhe) → Größenklasse
//   main    Hauptfarbe (größte Eigenfarbfläche), acc = Akzentfarbe
//   cat     Kategorie des Signature-Elements, sig = Signature-Element (nur diese Figur besitzt es)
//   zones   Teamzonen (zusätzlich immer: Bodenring und Teamsymbol)
//   prop    Proportionsformel: head = Kopfhöhe/Gesamthöhe, legs = Beinlänge/Gesamthöhe, arms = Armlänge/Rumpfhöhe,
//           hands = Handbreite/Kopfbreite, weapon = Länge von Waffe/Werkzeug/Signature/Gesamthöhe
//   over    bewusst übertriebenes Merkmal
//   mood    Persönlichkeit (Gesicht + Haltung), idle = Idle-Verhalten, attack = Angriffsbewegung
//   faction Herkunft in der Spielwelt (für stimmige Materialien)

/** @typedef {{id:string, fam:string, h:number, main:string, acc:string, skin?:string, cat:string, sig:string, zones:string[], prop:{head:number,legs:number,arms:number,hands:number,weapon:number}, over:string, mood:string, idle:string, attack:string, faction:string, base?:string, variants?:string[]}} Figure */

const P = (head, legs, arms, hands, weapon) => ({ head, legs, arms, hands, weapon });

/** @type {Figure[]} */
export const FIGURES = [
  // ───────────── Krone (Ritter, Schützinnen, Prinzen, Rekruten) ─────────────
  { id: 'knight', faction: 'krone', fam: 'breit', h: 1.85, main: '#8f99a8', acc: '#9a5b2a', cat: 'schild', sig: 'Zinnenschild in Burgturm-Form', zones: ['Schildfeld', 'Helmwimpel'], prop: P(0.36, 0.22, 0.85, 0.5, 0.75), over: 'Zinnenschild fast so hoch wie er selbst', mood: 'stur und pflichtbewusst, Pflaster quer über der Nase', idle: 'klopft mit dem Schwertknauf zweimal an den Schild und späht über die Zinnen', attack: 'Schild vor, kurzer Hieb von oben hinter dem Schild hervor' },
  { id: 'archers', faction: 'krone', fam: 'schlank', h: 1.55, main: '#d9a520', acc: '#2a9d8f', cat: 'ruecken', sig: 'Fächerköcher wie ein Pfauenrad', zones: ['langer Schal', 'Köcherband'], prop: P(0.38, 0.3, 0.9, 0.42, 0.55), over: 'Pfeilfächer breiter als die Schultern', mood: 'sportlich und eifrig, zwinkern beim Zielen', idle: 'wippen auf den Zehen und zupfen an der Sehne', attack: 'Pfeil aus dem Fächer, weites Spannen, Schuss mit Schwung nach hinten', variants: ['Zopf', 'Dutt'] },
  { id: 'musketeer', faction: 'krone', fam: 'schlank', h: 1.95, main: '#8f7a24', acc: '#f4efe6', cat: 'werkzeug', sig: 'Musketengabel als Stütze', zones: ['Hutfeder', 'Schärpe'], prop: P(0.32, 0.36, 0.9, 0.4, 1.0), over: 'Muskete länger als sie selbst', mood: 'ruhig und präzise, hebt eine Augenbraue', idle: 'stellt die Gabel ab, pustet über die Mündung', attack: 'Gabel aufstellen, zielen, Schuss mit Rauchring und Rückstoß' },
  { id: 'three-musketeers', faction: 'krone', fam: 'schlank', h: 1.9, main: '#1f4e5a', acc: '#e7d9a8', cat: 'kopfbedeckung', sig: 'Dreispitz mit großer Kokarde', zones: ['Kokarde', 'Schärpe'], prop: P(0.33, 0.34, 0.9, 0.42, 0.7), over: 'riesige Kokarden am Dreispitz', mood: 'eingespielt und keck, Schwestern-Grinsen', idle: 'drehen den Karabiner wie einen Taktstock', attack: 'Karabiner-Schuss; aus der Nähe Bajonett-Stoß', variants: ['Zopf', 'Locken', 'Kurzhaar'] },
  { id: 'royal-recruits', faction: 'krone', fam: 'breit', h: 1.75, main: '#9fb39a', acc: '#6b4a2a', cat: 'kopfbedeckung', sig: 'übergroßer Schüsselhelm, der über die Augen rutscht', zones: ['Rundschild-Feld', 'Halstuch'], prop: P(0.42, 0.22, 0.8, 0.45, 0.9), over: 'Helm so groß wie der Oberkörper', mood: 'jung, nervös und tapfer', idle: 'schieben den Helm hoch, der wieder herunterrutscht', attack: 'Pikenstoß über den Schildrand', variants: ['Sommersprossen', 'Zahnlücke', 'Brille'] },
  { id: 'prince', faction: 'krone', fam: 'reiter', h: 2.45, main: '#8fbf3a', acc: '#f0c040', cat: 'kopfbedeckung', sig: 'Froschmaul-Stechhelm', zones: ['Schabracke', 'Lanzenwimpel'], prop: P(0.24, 0.0, 0.8, 0.4, 1.15), over: 'Turnierlanze mit Spiralstreifen', mood: 'edel und ungeduldig', idle: 'Pferd scharrt, Prinz richtet die Lanze aus', attack: 'Lanzenstoß im Vorbeireiten; Ansturm mit gesenkter Lanze' },
  { id: 'princess', faction: 'krone', fam: 'dreieckig', h: 1.6, main: '#f7b49a', acc: '#8fe3c0', cat: 'waffe', sig: 'Harfenbogen mit Saiten', zones: ['Schleife am Kleid', 'Diadem-Stein'], prop: P(0.36, 0.0, 0.85, 0.38, 0.65), over: 'Glockenkleid fast so breit wie hoch', mood: 'verträumt, summt beim Zielen', idle: 'zupft eine Saite und lauscht', attack: 'zieht eine glühende Saite wie eine Sehne, brennender Pfeil im hohen Bogen' },
  { id: 'golden-knight', faction: 'krone', fam: 'schlank', h: 2.2, main: '#f2c14e', acc: '#fff6e0', cat: 'kopfbedeckung', sig: 'Strahlenkranz-Helmzier', zones: ['Umhang', 'Brustemblem'], prop: P(0.3, 0.38, 0.9, 0.4, 0.75), over: 'Strahlenkranz wie eine Sonne hinter dem Kopf', mood: 'eitel und strahlend, posiert', idle: 'poliert die Klinge und pustet eine Haarsträhne weg', attack: 'Fechter-Ausfall mit dem Rapier', base: null },
  { id: 'archer-queen', faction: 'krone', fam: 'hochgewachsen', h: 2.15, main: '#1f6b52', acc: '#e8b33c', cat: 'waffe', sig: 'Mondsichel-Armbrust', zones: ['Schleppe des Umhangs', 'Kronenjuwel'], prop: P(0.27, 0.42, 0.95, 0.38, 0.8), over: 'steife Spitzenkrause bis über die Ohren', mood: 'kühl und überlegen, hochgezogene Augenbraue', idle: 'prüft die Sehne, der Umhang weht', attack: 'legt an, kurzes Zielen, Schuss mit Rückstoß' },
  { id: 'little-prince', faction: 'krone', fam: 'winzig', h: 1.55, main: '#2f8f8a', acc: '#f7f2ea', cat: 'kopfbedeckung', sig: 'viel zu große Krone, die über die Augen rutscht', zones: ['Umhang', 'Kronenkissen'], prop: P(0.46, 0.22, 0.75, 0.42, 0.55), over: 'Krone so breit wie der ganze Prinz', mood: 'verwöhnt und ungeduldig, stampft', idle: 'schiebt die Krone hoch und verschränkt die Arme', attack: 'kurbelt die Repetier-Armbrust, die immer schneller schießt' },
  { id: 'guardienne', faction: 'krone', fam: 'keil', h: 2.15, main: '#7a5f96', acc: '#e8d9b0', cat: 'schild', sig: 'echte Holztür als Schild', zones: ['Türfenster-Vorhang', 'Schärpe'], prop: P(0.28, 0.36, 0.95, 0.5, 1.0), over: 'Tür-Schild mit Klinke und Briefschlitz', mood: 'wachsam, beschützend, wortkarg', idle: 'stellt die Tür ab und lehnt sich daran', attack: 'Hellebardenstoß hinter der Tür hervor; Ansturm mit der Tür voran' },
  { id: 'tower-king', faction: 'krone', fam: 'dreieckig', h: 1.6, main: '#7d3f8c', acc: '#ffd34d', cat: 'kopfbedeckung', sig: 'Zinnenkrone wie ein kleiner Turm', zones: ['Hermelinkragen-Saum', 'Zepterstein'], prop: P(0.4, 0.0, 0.7, 0.45, 0.6), over: 'runder Königsbauch im Hermelinmantel', mood: 'gemütlich und stolz, im Schlaf mit Zipfelmütze', idle: 'schläft mit Zipfelmütze über der Krone; wach: zeigt mit dem Zepter', attack: 'zeigt mit dem Zepter auf das Ziel, die Turmkanone feuert' },
  { id: 'tower-guard', faction: 'krone', fam: 'schlank', h: 1.35, main: '#7a8a68', acc: '#f0e0b0', cat: 'werkzeug', sig: 'Signalhorn am Schulterriemen', zones: ['Wimpel am Horn', 'Kappe'], prop: P(0.4, 0.28, 0.85, 0.4, 0.6), over: 'langer Turmbogen', mood: 'aufmerksam, streng', idle: 'späht unter der Hand hervor, bläst kurz ins Horn', attack: 'schneller Schuss mit dem Turmbogen' },

  // ───────────── Nordvolk (Barbaren, Walküre, Holzfäller) ─────────────
  { id: 'barbarians', faction: 'nordvolk', fam: 'breit', h: 1.8, main: '#857565', acc: '#b57a3a', cat: 'kopfbedeckung', sig: 'Wolfskopf-Kapuze mit offenem Maul', zones: ['Gürtelschärpe', 'Armwickel'], prop: P(0.34, 0.22, 0.9, 0.55, 0.6), over: 'gewaltige umwickelte Unterarme', mood: 'laut und draufgängerisch, brüllt', idle: 'rollt die Schultern und klopft sich auf die Brust', attack: 'weit ausholender Hackschwert-Hieb über den Kopf bis zum Boden', variants: ['Rauschebart', 'Narbe', 'Zöpfe', 'Glatze', 'Schnauzer'] },
  { id: 'elite-barbarians', faction: 'nordvolk', fam: 'keil', h: 2.0, main: '#e4a11b', acc: '#5a3a22', cat: 'schulter', sig: 'Bärenschädel-Schulterpanzer', zones: ['Gürtelschärpe', 'Kriegsbemalung-Streifen am Schwertgriff'], prop: P(0.28, 0.3, 1.0, 0.5, 0.85), over: 'Schultern doppelt so breit wie die Hüfte', mood: 'angeberisch, grinst überlegen', idle: 'Wellenschwert lässig auf der Schulter, dehnt den Nacken', attack: 'zweihändiger Diagonalhieb mit halber Drehung', variants: ['Zopfbart', 'Irokese'] },
  { id: 'valkyrie', faction: 'nordvolk', fam: 'breit', h: 1.95, main: '#5a7a8a', acc: '#d98c3a', cat: 'waffe', sig: 'Rad-Doppelaxt mit Speichen', zones: ['Gürtel', 'Helmflügel-Spitzen'], prop: P(0.32, 0.28, 0.9, 0.5, 0.7), over: 'Axt mit Radnabe, so breit wie sie', mood: 'kampflustig, lacht beim Wirbeln', idle: 'stützt die Axt auf und wirft einen Zopf zurück', attack: 'Anlauf-Drehung: ganzer Körper wirbelt mit der Axt einmal herum' },
  { id: 'lumberjack', faction: 'nordvolk', fam: 'hochgewachsen', h: 2.0, main: '#2f6b3a', acc: '#c25b2c', cat: 'ruecken', sig: 'Holzkraxe mit Holzscheiten und Wutflasche', zones: ['Halstuch', 'Mützenband'], prop: P(0.27, 0.41, 1.05, 0.5, 0.8), over: 'Bart voller Tannenzweige', mood: 'hektisch und gutgelaunt', idle: 'wirft die Fällaxt hoch und fängt sie', attack: 'blitzschnelle Hiebe wie beim Holzhacken' },
  { id: 'battle-ram', faction: 'nordvolk', fam: 'fahrzeug', h: 1.7, main: '#6e4523', acc: '#8a8f99', cat: 'fahrzeug', sig: 'geschnitzter Widderkopf mit eisernen Spiralhörnern am Stamm', zones: ['Wimpel am Stamm', 'Schärpen der Schieber'], prop: P(0.3, 0.2, 0.9, 0.5, 1.4), over: 'riesige eiserne Spiralhörner', mood: 'zwei schnaufende Schieber, entschlossen', idle: 'Schieber stampfen auf der Stelle, Stamm wippt', attack: 'Anlauf, Rammstoß mit Squash des Stammes, Splitterwolke' },
  { id: 'berserker', faction: 'nordvolk', fam: 'keil', h: 1.75, main: '#c96f3b', acc: '#3a5a40', cat: 'kopfbedeckung', sig: 'Kochtopf-Helm mit Henkeln wie Hörner', zones: ['Schürze', 'Zopfbänder'], prop: P(0.34, 0.3, 0.95, 0.5, 0.5), over: 'zwei riesige Bratpfannen', mood: 'wild, lacht gackernd', idle: 'schlägt die Pfannen gegeneinander, Funken', attack: 'abwechselnde Pfannenschläge links und rechts, sehr schnell' },
  { id: 'barbarian-hut', faction: 'nordvolk', fam: 'bauwerk', h: 2.9, main: '#5a7a34', acc: '#3a3330', cat: 'bauwerk', sig: 'Langhaus mit Wolfsschädel über dem Tor', zones: ['Torbehang', 'Dachfahne'], prop: P(0, 0, 0, 0, 0.3), over: 'tief heruntergezogenes Grassodendach', mood: 'rauchend und lärmend', idle: 'Rauch aus dem Dachloch, Torbehang weht', attack: 'Tor fliegt auf, Barbaren stürmen heraus' },

  // ───────────── Riesen ─────────────
  { id: 'giant', faction: 'riesen', fam: 'massig', h: 2.75, main: '#9a6b3c', acc: '#e8c35a', cat: 'kopfbedeckung', sig: 'Bommelmütze mit Riesenbommel', zones: ['Bommel', 'Latzhosen-Flicken'], prop: P(0.2, 0.2, 1.1, 0.75, 0.2), over: 'riesige Arbeitshandschuhe', mood: 'gutmütig und schnaufend', idle: 'kratzt sich unter der Mütze', attack: 'beide Fäuste gefaltet, Hammerschlag von oben' },
  { id: 'royal-giant', faction: 'riesen', fam: 'massig', h: 2.7, main: '#4d4b23', acc: '#d4b04a', cat: 'kopfbedeckung', sig: 'hohe Bärenfellmütze der Leibgarde', zones: ['Schärpe', 'Mützenkordel'], prop: P(0.24, 0.22, 1.0, 0.65, 0.5), over: 'Schulterkanone mit Löwenmaul-Mündung', mood: 'streng und stolz, Schnurrbart zuckt', idle: 'salutiert und putzt einen Messingknopf', attack: 'Kanone auf der Schulter: Zielen, Abfeuern, Rückstoß bis in die Knie' },
  { id: 'rune-giant', faction: 'riesen', fam: 'massig', h: 2.7, main: '#9a9890', acc: '#7af0ff', cat: 'werkzeug', sig: 'Runentafel als Schild und Waffe', zones: ['Lendentuch', 'Armreif'], prop: P(0.22, 0.24, 1.05, 0.6, 0.55), over: 'leuchtende Runen-Tätowierungen', mood: 'feierlich und weise, murmelt', idle: 'meißelt eine neue Rune in die Tafel', attack: 'Tafel-Stoß von oben; beim Verzaubern leuchtet eine Rune auf' },
  { id: 'electro-giant', faction: 'werkstatt', fam: 'massig', h: 2.75, main: '#d07f3a', acc: '#5fe3ff', cat: 'schulter', sig: 'Teslaspulen als Schulterpolster', zones: ['Gürtel', 'Helmstreifen'], prop: P(0.22, 0.22, 1.05, 0.7, 0.3), over: 'riesige Gummihandschuhe', mood: 'grimmig, knurrt durch das Schweißervisier', idle: 'Funken springen zwischen den Spulen', attack: 'Faustschlag von oben mit Entladung; Gegenschlag lässt die Spulen aufblitzen' },
  { id: 'bowler', faction: 'riesen', fam: 'massig', h: 2.6, main: '#7f9a6a', acc: '#2e2a33', cat: 'kopfbedeckung', sig: 'winziger Melonenhut auf riesigem Kopf', zones: ['Hosenträger', 'Hutband'], prop: P(0.26, 0.24, 1.05, 0.65, 0.35), over: 'Moos-Rücken eines Steintrolls', mood: 'gemütlich, konzentriert wie beim Kegeln', idle: 'poliert die Runenkugel am Bauch', attack: 'tiefer Kegelwurf: weit ausholen, rollen lassen, Bein hoch' },
  { id: 'mega-knight', faction: 'krone', fam: 'massig', h: 2.8, main: '#5a6372', acc: '#b07a3a', cat: 'kopfbedeckung', sig: 'Glockenhelm, der beim Landen läutet', zones: ['Schulterumhang', 'Helmband'], prop: P(0.24, 0.2, 1.0, 0.8, 0.0), over: 'Kugelfäuste aus Gusseisen', mood: 'wuchtig und selbstgefällig', idle: 'lässt die Kugelfäuste aneinanderklacken', attack: 'Doppelfaust-Hammer; Sprung mit Glockenläuten bei der Landung' },
  { id: 'goblinstein-monster', faction: 'kobolde', fam: 'massig', h: 2.75, main: '#7a8f74', acc: '#c47a3a', cat: 'ruecken', sig: 'Rücken-Akku mit Kabeln zu Kupferklemmen am Hals', zones: ['Hosenbund', 'Armbinde'], prop: P(0.2, 0.24, 1.1, 0.7, 0.2), over: 'Flickenkörper mit ungleich großen Armen', mood: 'sanftes Monster, brummt Wiegenlieder', idle: 'Funken an den Klemmen, wiegt den Kopf', attack: 'schwerfälliger Doppelschlag; Blitzverbindung zum Doktor' },
  { id: 'goblin-giant', faction: 'kobolde', fam: 'massig', h: 2.75, main: '#6f8f3a', acc: '#c08a4a', skin: '#6f8f3a', cat: 'ruecken', sig: 'Fass-Krähennest mit zwei Speerkobolden', zones: ['Krähennest-Fähnchen', 'Gürtel'], prop: P(0.22, 0.2, 1.1, 0.7, 0.45), over: 'Riesenohren mit Ohrringen wie Fassreifen', mood: 'tumb und gutmütig, grinst schief', idle: 'die beiden Speerkobolde zanken sich im Fass', attack: 'schwerer Schwinger mit der Faust; oben werfen die Speerkobolde' },

  // ───────────── Werkstatt (Mechanik, Dampf, Elektrik) ─────────────
  { id: 'pekka', faction: 'werkstatt', fam: 'mechanisch', h: 2.85, main: '#4a3d36', acc: '#58e0c0', cat: 'kopfbedeckung', sig: 'Laternenkopf mit Flamme', zones: ['Brustwappen', 'Schulterwimpel'], prop: P(0.2, 0.3, 1.0, 0.55, 0.9), over: 'Fallbeil-Schwert länger als der Rumpf', mood: 'stumm und unaufhaltsam, die Flamme flackert vor Zorn', idle: 'Flamme flackert, Kolben zischen leise', attack: 'Schwert weit über den Kopf, Fallbeil-Hieb mit Funken' },
  { id: 'mini-pekka', faction: 'werkstatt', fam: 'mechanisch', h: 1.7, main: '#6f7682', acc: '#ff8a3d', cat: 'kopfbedeckung', sig: 'Dampfpfeife auf dem Kessel, pfeift beim Schlag', zones: ['Brustplakette', 'Pfeifenband'], prop: P(0.5, 0.22, 0.8, 0.5, 0.7), over: 'Riesen-Rohrzange', mood: 'eifrig und tollpatschig, ein großes Zyklopenauge', idle: 'tippelt, Dampfwölkchen aus der Pfeife', attack: 'Rohrzange über den Kopf, Schlag, Pfiff' },
  { id: 'sparky', faction: 'werkstatt', fam: 'mechanisch', h: 2.5, main: '#3a5a3a', acc: '#9ff0ff', cat: 'waffe', sig: 'Kondensator-Schüssel mit Ladebalken', zones: ['Panzerstreifen', 'Antennenwimpel'], prop: P(0.2, 0.15, 0.6, 0.5, 0.6), over: 'Schüssel größer als der Käferpanzer', mood: 'brummt ungeduldig, Ladebalken als Gesichtsausdruck', idle: 'Ladebalken füllen sich, Beine trippeln', attack: 'volle Ladung: Schüssel glüht, gewaltiger Entladungsschuss, Rückstoß' },
  { id: 'zappies', faction: 'werkstatt', fam: 'mechanisch', h: 1.3, main: '#c0c8d0', acc: '#ffe14a', cat: 'koerper', sig: 'Glühbirnen-Kopf mit Wendelfaden', zones: ['Batteriestreifen', 'Fußkappen'], prop: P(0.45, 0.25, 0.7, 0.45, 0.3), over: 'Batterie-Rucksack größer als der Rumpf', mood: 'aufgekratzt, flackern beim Reden', idle: 'Birne flackert, Federbeine wippen', attack: 'Birne leuchtet auf, Zap-Blitz aus der Antenne', variants: ['Birne rund', 'Birne spitz', 'Birne gedreht'] },
  { id: 'flying-machine', faction: 'werkstatt', fam: 'mechanisch', h: 1.7, main: '#e5d3a8', acc: '#5b8c5a', cat: 'fluegel', sig: 'Schlagflügel aus Segeltuch mit Holzrippen', zones: ['Flügelstreifen', 'Pilotenschal'], prop: P(0.2, 0.0, 0.6, 0.4, 1.3), over: 'Flügelspannweite doppelt so groß wie die Höhe', mood: 'Pilotin mit Zunge im Mundwinkel', idle: 'Flügel schlagen, Pilotin kurbelt', attack: 'Bugkanone feuert, Gestell ruckt zurück' },
  { id: 'furnace', faction: 'werkstatt', fam: 'mechanisch', h: 2.1, main: '#3b4250', acc: '#ff8a2a', cat: 'koerper', sig: 'glühende Ofenklappe als Bauch', zones: ['Ofenrohr-Band', 'Henkeltuch'], prop: P(0.3, 0.2, 0.6, 0.45, 0.4), over: 'Ofenrohr als hoher Hut', mood: 'brummig und hitzköpfig', idle: 'pafft Rauchringe aus dem Ofenrohr', attack: 'Klappe schnappt auf, spuckt Glut; Feuergeist hüpft heraus' },
  { id: 'cannon-cart', faction: 'werkstatt', fam: 'fahrzeug', h: 1.7, main: '#3f8f86', acc: '#c99a3c', cat: 'waffe', sig: 'Hechtkopf-Kanonenrohr', zones: ['Karrenwimpel', 'Ohrenschützer des Kanoniers'], prop: P(0.28, 0.0, 0.7, 0.45, 0.9), over: 'Fischmaul-Mündung mit Zähnen', mood: 'Kanonier mit Ohrenschützern, pfeift', idle: 'Kanonier schaut durchs Fernrohr', attack: 'Rohr ruckt zurück, Rauch aus dem Fischmaul' },
  { id: 'goblin-machine', faction: 'kobolde', fam: 'mechanisch', h: 2.55, main: '#8a5a44', acc: '#4fd1c5', cat: 'werkzeug', sig: 'Kolbenfaust mit Dampfzylinder', zones: ['Raketenwimpel', 'Pilotenhelm'], prop: P(0.2, 0.25, 1.0, 0.8, 0.4), over: 'Kolbenfaust größer als der Pilot', mood: 'Pilot jauchzt, Maschine stampft', idle: 'Auspuff pufft, Pilot kurbelt an den Hebeln', attack: 'Kolbenfaust schnellt vor; Schulter-Raketenwerfer feuert unabhängig' },
  { id: 'goblin-drill', faction: 'kobolde', fam: 'bauwerk', h: 2.6, main: '#a05a36', acc: '#e0b040', cat: 'bauwerk', sig: 'Bohrturm mit Schraubenspitze und Kobold-Fahrer', zones: ['Turmfahne', 'Fahrerhelm'], prop: P(0, 0, 0, 0, 0.4), over: 'Riesenschraube', mood: 'rattert und ruckelt', idle: 'Schraube dreht, Erdbrocken fliegen', attack: 'Luke springt auf, Kobold hüpft heraus' },

  // ───────────── Zirkel (Magie) ─────────────
  { id: 'wizard', faction: 'zirkel', fam: 'dreieckig', h: 1.95, main: '#8a2d55', acc: '#ffb347', cat: 'begleiter', sig: 'fliegendes, feuerspuckendes Zauberbuch', zones: ['Gürtelschärpe', 'Hutband'], prop: P(0.3, 0.0, 0.85, 0.45, 0.35), over: 'Ballonärmel', mood: 'theatralisch, deklamiert', idle: 'blättert im schwebenden Buch, das gähnt', attack: 'Buch schnappt auf, spuckt einen Feuerball; Magier dirigiert' },
  { id: 'ice-wizard', faction: 'zirkel', fam: 'dreieckig', h: 1.9, main: '#d8eefc', acc: '#8e7bd8', cat: 'werkzeug', sig: 'Schneekugel-Stab mit Winterlandschaft', zones: ['Schal', 'Mantelsaum'], prop: P(0.32, 0.0, 0.8, 0.45, 0.85), over: 'Eiszapfen-Bart bis zum Gürtel', mood: 'gelassen und schusselig', idle: 'schüttelt die Schneekugel und staunt', attack: 'schwenkt die Schneekugel, Eissplitter-Fächer' },
  { id: 'electro-wizard', faction: 'zirkel', fam: 'hochgewachsen', h: 2.0, main: '#126e82', acc: '#f7f06d', cat: 'ruecken', sig: 'Rucksack aus Blitzflaschen mit Kupferbügeln', zones: ['Mantelkragen', 'Brillenband'], prop: P(0.28, 0.4, 1.0, 0.5, 0.45), over: 'Kupferspulen-Handschuhe', mood: 'exzentrisch, grinst manisch', idle: 'Funken knistern zwischen den Fingern', attack: 'beide Hände vor, zwei Blitze gleichzeitig' },
  { id: 'witch', faction: 'zirkel', fam: 'hochgewachsen', h: 2.1, main: '#4f7a3a', acc: '#c8a2e8', cat: 'begleiter', sig: 'Krähe auf der Hutspitze', zones: ['Hutband', 'Mantelfutter'], prop: P(0.26, 0.42, 1.0, 0.4, 0.9), over: 'krummer, zweimal geknickter Hut', mood: 'gackernd und verschlagen', idle: 'Krähe putzt sich, Knochen-Windspiel klimpert', attack: 'Stab nach vorn, Knochenspiel klingt, Geisterkugel fliegt' },
  { id: 'night-witch', faction: 'zirkel', fam: 'hochgewachsen', h: 2.1, main: '#2e2448', acc: '#c8d0e0', cat: 'kopfbedeckung', sig: 'Glockenturm-Hut, aus dem Fledermäuse fliegen', zones: ['Mantelfutter', 'Glockenseil'], prop: P(0.24, 0.42, 1.0, 0.4, 0.8), over: 'Hut mit kleinem Glockenstuhl', mood: 'träge und spöttisch, gähnt', idle: 'die Glocke im Hut schwingt, eine Fledermaus guckt heraus', attack: 'Sichelstab-Hieb; beim Rufen läutet die Hutglocke' },
  { id: 'mother-witch', faction: 'zirkel', fam: 'dreieckig', h: 1.9, main: '#6b6b2a', acc: '#ff6fb5', cat: 'ruecken', sig: 'Kessel-Rucksack mit blubberndem Fluchsud', zones: ['Schultertuch', 'Hutschleife'], prop: P(0.32, 0.0, 0.85, 0.45, 0.45), over: 'Lockenwickler unter dem Hut', mood: 'resolute Hexen-Oma, droht mit der Kelle', idle: 'rührt im Rückenkessel, schnuppert', attack: 'schleudert Fluchsud mit der Kelle' },
  { id: 'magic-archer', faction: 'zirkel', fam: 'schlank', h: 2.0, main: '#3b2a6b', acc: '#f8e38a', cat: 'waffe', sig: 'Fernrohr-Bogen mit Messingvisier', zones: ['Hutband', 'Umhangfutter'], prop: P(0.3, 0.38, 0.95, 0.4, 0.9), over: 'Astrolabium-Hutkrempe mit Messingringen', mood: 'verträumter Sterngucker, präzise', idle: 'schaut durch das Fernrohr in den Himmel', attack: 'zielt durch das Fernrohr, Lichtpfeil schießt in gerader Linie' },
  { id: 'executioner', faction: 'zirkel', fam: 'hochgewachsen', h: 2.3, main: '#4a3426', acc: '#b8862d', cat: 'waffe', sig: 'Sichelaxt an einer Kette', zones: ['Schulterband', 'Kettenschleife'], prop: P(0.22, 0.44, 1.05, 0.5, 0.6), over: 'Eisenmaske mit zwei runden Gucklöchern', mood: 'stoisch, summt unheimlich', idle: 'lässt die Axt an der Kette pendeln', attack: 'Drehung, die Axt fliegt im weiten Bogen aus und kommt zurück in die Hand' },
  { id: 'goblinstein', faction: 'kobolde', fam: 'schlank', h: 1.95, main: '#eef0f2', acc: '#7b4fd1', cat: 'werkzeug', sig: 'Fernsteuerkasten mit Blitzantenne', zones: ['Armbinde', 'Brillenband'], prop: P(0.34, 0.34, 0.9, 0.45, 0.55), over: 'Schweißerbrille mit dicken Gläsern', mood: 'größenwahnsinnig, lacht irre', idle: 'drückt Knöpfe am Kasten, Antenne funkt', attack: 'reckt die Antenne, Blitz auf das Ziel' },
  { id: 'monk', faction: 'zirkel', fam: 'breit', h: 2.15, main: '#9a4a7a', acc: '#d39a3a', cat: 'ruecken', sig: 'Bronzegong auf dem Rücken', zones: ['Schärpe', 'Gebetskette-Quaste'], prop: P(0.3, 0.26, 0.95, 0.6, 0.55), over: 'riesige Handflächen', mood: 'heiter und unerschütterlich', idle: 'streicht sich den Bart, Gebetskette klackert', attack: 'Kombo aus Handflächenstößen, der dritte mit Gongschlag' },
  { id: 'spirit-empress-ground', faction: 'zirkel', fam: 'dreieckig', h: 2.0, main: '#3fb07c', acc: '#ffb45a', cat: 'kopfbedeckung', sig: 'Laternenkrone mit schwebenden Lichtern', zones: ['Ärmelsaum', 'Fächerquaste'], prop: P(0.28, 0.0, 0.95, 0.4, 0.5), over: 'bodenlange Seidenärmel', mood: 'würdevoll, lächelt geheimnisvoll', idle: 'fächelt mit dem Seidenfächer, Lichter kreisen', attack: 'Fächerschlag mit Geisterwelle' },
  { id: 'spirit-empress-air', faction: 'zirkel', fam: 'schlangenartig', h: 2.9, main: '#f8d9f5', acc: '#ffb45a', cat: 'reittier', sig: 'Nebelband-Drache, auf dem die Kaiserin reitet', zones: ['Zügelband', 'Ärmelsaum'], prop: P(0.2, 0.0, 0.8, 0.4, 1.6), over: 'Drachenleib als endloses Nebelband', mood: 'schwebend und erhaben', idle: 'Drachenleib wogt in Wellen', attack: 'Drache stößt eine Geisterwelle aus' },

  // ───────────── Kobolde ─────────────
  { id: 'goblins', faction: 'kobolde', fam: 'winzig', h: 1.3, main: '#8b5a3c', acc: '#e9e2d0', skin: '#7fae4a', cat: 'waffe', sig: 'geschliffener Löffeldolch', zones: ['Halstuch', 'Gürtelknoten'], prop: P(0.48, 0.22, 0.8, 0.45, 0.35), over: 'Riesenohren mit Goldringen', mood: 'frech und gierig', idle: 'hüpfen und lecken am Löffel', attack: 'schnelles Zustechen mit dem Löffeldolch', variants: ['Ohrring links', 'Ohrring rechts', 'Zahnlücke', 'Nasenring'] },
  { id: 'spear-goblins', faction: 'kobolde', fam: 'schlank', h: 1.4, main: '#e8892f', acc: '#c6c26a', skin: '#93b844', cat: 'ruecken', sig: 'Bambusspeer-Bündel auf dem Rücken', zones: ['Hutband', 'Speerwimpel'], prop: P(0.44, 0.26, 0.85, 0.42, 0.75), over: 'Anglerhut mit Haken an der Krempe', mood: 'eifrig, streckt die Zunge raus', idle: 'zählen ihre Speere', attack: 'weit ausholender Speerwurf mit Hüpfer', variants: ['Haken am Hut', 'Feder am Hut', 'Flicken am Hut'] },
  { id: 'dart-goblin', faction: 'kobolde', fam: 'geduckt', h: 1.35, main: '#c2418f', acc: '#e9f27a', skin: '#6fb08a', cat: 'waffe', sig: 'Blasrohr doppelt so lang wie er selbst', zones: ['Stirnband', 'Federschmuck'], prop: P(0.44, 0.24, 0.8, 0.4, 1.4), over: 'Blasrohr', mood: 'hibbelig, schielt beim Zielen', idle: 'pustet Staub aus dem Blasrohr', attack: 'Backen aufblasen, Pfeil, Backen fallen zusammen' },
  { id: 'goblin-demolisher', faction: 'kobolde', fam: 'kugelig', h: 1.75, main: '#b5a26b', acc: '#f4c430', skin: '#7fae4a', cat: 'kopfbedeckung', sig: 'Bullaugen-Helm am gepolsterten Bombenanzug', zones: ['Warnstreifen', 'Helmlampe'], prop: P(0.36, 0.18, 0.75, 0.55, 0.3), over: 'kugelrunder Polsteranzug', mood: 'fröhlich-leichtsinnig', idle: 'klopft an die Helmscheibe', attack: 'Dynamitstange über Kopf werfen; Ansturm-Form mit brennender Helmlunte' },
  { id: 'goblin-brawler', faction: 'kobolde', fam: 'keil', h: 1.95, main: '#a35d3d', acc: '#8a95a3', skin: '#6e9c40', cat: 'schmuck', sig: 'gesprengte Handschellen mit Kettenresten', zones: ['Boxerhosen-Bund', 'Faustwickel'], prop: P(0.3, 0.24, 1.1, 0.75, 0.3), over: 'Fäuste groß wie der Kopf', mood: 'wütend und befreit, schnaubt', idle: 'schattenboxt, Ketten klirren', attack: 'Haken-Kombination mit den Kettenfäusten' },
  { id: 'bush-goblin', faction: 'kobolde', fam: 'geduckt', h: 1.35, main: '#3f7a35', acc: '#ff9a3d', skin: '#86b84f', cat: 'kostuem', sig: 'Tarnanzug aus Zweigen und Blättern', zones: ['Stirnband', 'Gürtel'], prop: P(0.44, 0.22, 0.8, 0.45, 0.35), over: 'Blätterschopf wie ein Strauch', mood: 'verschwörerisch, flüstert', idle: 'schaut sich verstohlen um', attack: 'Sprung aus der Hocke mit Stichdolch' },
  { id: 'decoy-goblin', faction: 'kobolde', fam: 'winzig', h: 1.35, main: '#b8b0a0', acc: '#2e8a5a', skin: '#97c25a', cat: 'kostuem', sig: 'Lockente-Kostüm mit Holzschnabel', zones: ['Schnabelband', 'Halstuch'], prop: P(0.46, 0.2, 0.75, 0.42, 0.3), over: 'Entenschnabel-Kapuze', mood: 'albern, quakt', idle: 'watschelt auf der Stelle', attack: 'Schnabel-Kopfstoß und Stich' },
  { id: 'goblin-hut', faction: 'kobolde', fam: 'bauwerk', h: 2.8, main: '#a8865a', acc: '#e07a2a', cat: 'bauwerk', sig: 'schiefe Flickwerk-Hütte mit Kürbis-Schornstein', zones: ['Türvorhang', 'Dachfahne'], prop: P(0, 0, 0, 0, 0.3), over: 'krummer Kürbisschornstein', mood: 'knarzend, Kobolde gucken heraus', idle: 'Schornstein raucht, Vorhang wackelt', attack: 'Vorhang fliegt auf, ein Speerkobold springt heraus' },
  { id: 'goblin-cage', faction: 'kobolde', fam: 'bauwerk', h: 2.2, main: '#d0a840', acc: '#3a3a40', cat: 'bauwerk', sig: 'vergoldeter Vogelkäfig mit rüttelndem Raufbold', zones: ['Käfigschild', 'Wimpel'], prop: P(0, 0, 0, 0, 0.3), over: 'riesiges Vorhängeschloss', mood: 'wackelnd, der Gefangene tobt', idle: 'Raufbold rüttelt an den Stäben', attack: 'Käfig platzt, Raufbold stürmt heraus; Evo: Stäbe ziehen Gegner hinein' },

  // ───────────── Gruft (Untote) ─────────────
  { id: 'skeletons', faction: 'gruft', fam: 'winzig', h: 1.05, main: '#efe6d0', acc: '#5ee6ff', cat: 'koerper', sig: 'riesiger rissiger Schädel mit Geisteraugen', zones: ['Halstuch'], prop: P(0.52, 0.2, 0.75, 0.45, 0.35), over: 'Schädel halb so groß wie der ganze Körper', mood: 'klapprig-fröhlich', idle: 'Kiefer klappert, Kopf wackelt', attack: 'Stich mit dem Knochendolch', variants: ['Riss links', 'Riss rechts', 'Zahn fehlt'] },
  { id: 'guards', faction: 'gruft', fam: 'winzig', h: 1.4, main: '#8a7a78', acc: '#efe6d0', cat: 'schild', sig: 'Sargdeckel-Schild', zones: ['Sargdeckel-Emblem', 'Helmfeder'], prop: P(0.42, 0.22, 0.8, 0.42, 0.85), over: 'Sargdeckel länger als der Wächter', mood: 'steif und pflichtbewusst, salutieren', idle: 'stehen stramm, ein Knochen wackelt', attack: 'Speerstoß hinter dem Sargdeckel hervor', variants: ['Helmfeder', 'Rostfleck', 'Kerbe im Schild'] },
  { id: 'giant-skeleton', faction: 'gruft', fam: 'massig', h: 2.9, main: '#d9c9a0', acc: '#3d4a3a', cat: 'koerper', sig: 'Uhrwerk-Bombe im Brustkorb', zones: ['Halstuch', 'Armband'], prop: P(0.24, 0.3, 1.1, 0.7, 0.3), over: 'Riesenfäuste aus Fingerknochen', mood: 'dröhnend lachend', idle: 'Kiefer klappert, die Bombe tickt', attack: 'Rundumschlag mit der Knochenfaust' },
  { id: 'skeleton-king', faction: 'gruft', fam: 'massig', h: 3.0, main: '#4b4a62', acc: '#d8ccb0', cat: 'kopfbedeckung', sig: 'Geweihkrone', zones: ['Robensaum', 'Schulterumhang'], prop: P(0.24, 0.3, 1.05, 0.6, 0.65), over: 'Grabstein-Keule', mood: 'majestätisch und hohl lachend', idle: 'stützt sich auf die Grabstein-Keule, Seelenlichter kreisen', attack: 'Grabstein-Keule von oben, Flächenschlag' },
  { id: 'tomb-queen', faction: 'gruft', fam: 'massig', h: 2.8, main: '#2a6b6b', acc: '#d9b54a', cat: 'kostuem', sig: 'aufrechter Sarkophag als Kleid', zones: ['Sarkophag-Band', 'Schleier'], prop: P(0.22, 0.0, 1.0, 0.5, 0.5), over: 'Sarkophag-Rumpf mit bemalter Maske', mood: 'eisig und erhaben', idle: 'Sarkophagdeckel öffnet sich einen Spalt', attack: 'Schlag mit dem Zepter, Deckel klappt auf' },
  { id: 'skeleton-dragons', faction: 'gruft', fam: 'gefluegelt', h: 1.75, main: '#ded2b5', acc: '#6dff9a', cat: 'leuchten', sig: 'grünes Geisterfeuer im Brustkorb', zones: ['Halsband'], prop: P(0.3, 0.0, 0.0, 0.0, 1.2), over: 'Knochenflügel mit zerfetzter Haut', mood: 'gierig, schnappt', idle: 'Flügelschlag, Feuer züngelt durch die Rippen', attack: 'grüner Feuerball aus dem Kiefer', variants: ['Hornspitze', 'Kerbe im Kiefer'] },
  { id: 'skeleton-barrel', faction: 'gruft', fam: 'schwebend', h: 2.2, main: '#6b4a3a', acc: '#efe6d0', cat: 'kopfbedeckung', sig: 'Propellerkappe auf dem Fass', zones: ['Fähnchen', 'Fassband'], prop: P(0.0, 0.0, 0.0, 0.0, 0.3), over: 'Knochen gucken aus den Spundlöchern', mood: 'ratternd und kichernd', idle: 'Propeller dreht, Fass schaukelt', attack: 'Sturz auf das Gebäude, Fass platzt' },
  { id: 'wall-breakers', faction: 'gruft', fam: 'geduckt', h: 1.45, main: '#9a6a3a', acc: '#2a2a2a', cat: 'werkzeug', sig: 'Pulverfass über dem Kopf mit glimmender Lunte', zones: ['Stirnband', 'Fassband'], prop: P(0.4, 0.26, 0.8, 0.45, 0.45), over: 'Fass größer als der Träger', mood: 'begeistert, rennt kichernd', idle: 'balanciert das Fass', attack: 'Sprung gegen das Gebäude, Fass zündet' },
  { id: 'wall-breaker-runner', faction: 'gruft', fam: 'geduckt', h: 1.35, main: '#e6dcc2', acc: '#ff6a3d', cat: 'kopfbedeckung', sig: 'flatterndes Sprinter-Stirnband', zones: ['Stirnband'], prop: P(0.42, 0.3, 0.85, 0.45, 0.2), over: 'extrem lange Knochenbeine', mood: 'gehetzt, rudert mit den Armen', idle: 'trippelt auf der Stelle', attack: 'Hechtsprung mit Faustschlag' },
  { id: 'general-gerry', faction: 'gruft', fam: 'winzig', h: 1.4, main: '#2b2d3a', acc: '#e0b040', cat: 'kopfbedeckung', sig: 'Zweispitz mit Federbusch', zones: ['Federbusch', 'Schärpe'], prop: P(0.46, 0.2, 0.8, 0.42, 0.5), over: 'goldene Epauletten breiter als der Schädel', mood: 'kommandierend, zeigt mit dem Säbel', idle: 'zeigt mit dem Säbel nach vorn', attack: 'Säbelhieb mit Schildstoß' },
  { id: 'shadow-skeleton', faction: 'gruft', fam: 'winzig', h: 1.05, main: '#4a3a7a', acc: '#c9b8ff', cat: 'koerper', sig: 'Rauchschweif statt Beine', zones: ['Augenglut-Ring'], prop: P(0.5, 0.0, 0.75, 0.45, 0.35), over: 'leuchtende Augenhöhlen', mood: 'flüsternd, unheimlich', idle: 'flackert und wabert', attack: 'Schattenstich' },
  { id: 'skeletrooper', faction: 'gruft', fam: 'winzig', h: 1.45, main: '#6b7a3a', acc: '#e9dfc5', cat: 'ruecken', sig: 'Fallschirm-Packsack mit Reißleine', zones: ['Fliegerschal', 'Packsack-Streifen'], prop: P(0.44, 0.22, 0.8, 0.42, 0.55), over: 'Fliegerbrille über leeren Augenhöhlen', mood: 'tollkühn, salutiert', idle: 'zieht an den Gurten', attack: 'Landung mit Speer voran, dann Speerstöße' },
  { id: 'royal-ghost', faction: 'gruft', fam: 'schwebend', h: 1.95, main: '#a8f0e0', acc: '#c9a24a', cat: 'kopfbedeckung', sig: 'schwebende Krone über leerem Helm', zones: ['Umhangfetzen'], prop: P(0.3, 0.0, 0.9, 0.45, 0.6), over: 'leerer Helm, aus dem Licht scheint', mood: 'melancholisch, seufzt', idle: 'Krone kreist, Schweif wabert', attack: 'Geistersäbel-Schwung mit Flächenwelle' },
  { id: 'souldier', faction: 'gruft', fam: 'schwebend', h: 1.4, main: '#7fd8c8', acc: '#e6e0c0', cat: 'waffe', sig: 'Geisterpike mit Wimpelfetzen', zones: ['Wimpelfetzen'], prop: P(0.4, 0.0, 0.8, 0.42, 0.9), over: 'Pike doppelt so lang wie der Geist', mood: 'eifrig und durchscheinend', idle: 'schwebt im Kreis', attack: 'Pikenstoß nach vorn' },
  { id: 'tombstone', faction: 'gruft', fam: 'bauwerk', h: 1.9, main: '#8d8a9a', acc: '#7dff8a', cat: 'bauwerk', sig: 'Grabstein mit winkender Skeletthand', zones: ['Grablicht-Schirm', 'Kranzschleife'], prop: P(0, 0, 0, 0, 0.3), over: 'schiefer Grabstein mit Moos', mood: 'unheimlich-witzig', idle: 'die Skeletthand winkt, Grablicht flackert', attack: 'Erde bricht auf, Skelette klettern heraus' },

  // ───────────── Elementarwesen (Geister, Golems, Elixier, Lava, Eis) ─────────────
  { id: 'golem', faction: 'elementar', fam: 'massig', h: 3.3, main: '#c4938a', acc: '#3fe0c5', cat: 'begleiter', sig: 'Bäumchen mit Vogelnest auf der Schulter', zones: ['Tuch am Bäumchen', 'Armband'], prop: P(0.18, 0.24, 1.1, 0.8, 0.3), over: 'Felsfäuste so groß wie der Rumpf', mood: 'uralt und träge, brummt', idle: 'ein Vogel hüpft im Bäumchen', attack: 'langsamer Doppelfausthieb' },
  { id: 'golemite', faction: 'elementar', fam: 'kugelig', h: 2.0, main: '#a87f76', acc: '#3fe0c5', cat: 'koerper', sig: 'halbe Säule als Rumpf mit Kapitell-Kopf', zones: ['Armband'], prop: P(0.3, 0.2, 0.9, 0.6, 0.2), over: 'abgebrochenes Säulenkapitell', mood: 'trotzig', idle: 'bröselt', attack: 'Kopfstoß mit dem Kapitell' },
  { id: 'elixir-golem', faction: 'elementar', fam: 'massig', h: 2.55, main: '#d13cf0', acc: '#e6f7ff', cat: 'koerper', sig: 'Glasbauch voller blubbernder Flüssigkeit', zones: ['Halsband', 'Korkensiegel'], prop: P(0.18, 0.2, 1.0, 0.6, 0.3), over: 'Korken als Kopf', mood: 'tumb-fröhlich, blubbert', idle: 'Blasen steigen, Flüssigkeit schwappt', attack: 'schwappende Doppelfaust' },
  { id: 'elixir-golemite', faction: 'elementar', fam: 'kugelig', h: 1.9, main: '#b84ad8', acc: '#d8fff7', cat: 'koerper', sig: 'Erlenmeyerkolben-Körper mit Stopfen', zones: ['Halsband'], prop: P(0.3, 0.2, 0.85, 0.55, 0.2), over: 'Glasbauch mit Messskala', mood: 'aufgeregt', idle: 'schwappt', attack: 'Kopfnuss mit dem Stopfen' },
  { id: 'elixir-blob', faction: 'elementar', fam: 'amorph', h: 1.2, main: '#ff8ae2', acc: '#7a4a2a', cat: 'kopfbedeckung', sig: 'Korkhütchen auf dem Klecks', zones: ['Hutband'], prop: P(0.5, 0.0, 0.0, 0.0, 0.2), over: 'riesige glänzende Augen', mood: 'quietschfidel', idle: 'wabbelt', attack: 'Platscher nach vorn' },
  { id: 'ice-golem', faction: 'elementar', fam: 'kugelig', h: 1.95, main: '#9fe0f5', acc: '#ff9a62', cat: 'koerper', sig: 'eingefrorener Fisch im Bauch', zones: ['Strickschal'], prop: P(0.28, 0.18, 0.75, 0.55, 0.3), over: 'kugelrunder Eisbauch', mood: 'verschlafen-friedlich', idle: 'gähnt, Eiskristalle rieseln', attack: 'Kopfstoß mit Frostklirren' },
  { id: 'lava-hound', faction: 'elementar', fam: 'schwebend', h: 3.0, main: '#3a2f34', acc: '#ff6a1a', cat: 'koerper', sig: 'Vulkankrater auf dem Rücken', zones: ['Halsband'], prop: P(0.3, 0.1, 0.3, 0.4, 0.3), over: 'Basaltplatten-Panzer', mood: 'hechelnd und gutmütig', idle: 'Krater raucht, Zunge hängt heraus', attack: 'Lavaspucke' },
  { id: 'lava-pup', faction: 'elementar', fam: 'gefluegelt', h: 1.15, main: '#7a4f4f', acc: '#ffb02e', cat: 'koerper', sig: 'Glutkringel-Schwanz', zones: ['Halsband'], prop: P(0.45, 0.15, 0.3, 0.4, 0.3), over: 'riesige Welpenaugen', mood: 'tapsig', idle: 'jagt den eigenen Schwanz', attack: 'kleiner Glutbiss' },
  { id: 'fire-spirit', faction: 'elementar', fam: 'schwebend', h: 1.0, main: '#ff7a1a', acc: '#ffd84d', cat: 'koerper', sig: 'Kerzenwachs-Körper mit Flammenhaar', zones: ['Wachsmanschette'], prop: P(0.55, 0.0, 0.5, 0.4, 0.0), over: 'Flammenhaar höher als der Körper', mood: 'übermütig', idle: 'tropft, Flamme züngelt', attack: 'Hechtsprung und Explosion' },
  { id: 'ice-spirit', faction: 'elementar', fam: 'winzig', h: 0.95, main: '#e8fbff', acc: '#4fa3c7', cat: 'koerper', sig: 'Eiskristall-Stacheln wie ein Igel', zones: ['Schleife'], prop: P(0.6, 0.12, 0.4, 0.4, 0.0), over: 'Stachelkranz', mood: 'kichernd, kalt', idle: 'rollt sich ein und wieder auf', attack: 'Kugelsprung und Frostplatzer' },
  { id: 'electro-spirit', faction: 'elementar', fam: 'schwebend', h: 1.0, main: '#ffe14a', acc: '#8d5cf6', cat: 'koerper', sig: 'Steckerzinken als Ohren', zones: ['Schwanzband'], prop: P(0.55, 0.0, 0.4, 0.4, 0.0), over: 'Zickzack-Schwanz', mood: 'aufgekratzt', idle: 'zappelt, Funken', attack: 'Sprung, Blitz springt weiter' },
  { id: 'heal-spirit', faction: 'elementar', fam: 'schwebend', h: 1.0, main: '#d6f07a', acc: '#ff9ac8', cat: 'koerper', sig: 'Pusteblumen-Kopf', zones: ['Blattschleife'], prop: P(0.6, 0.0, 0.4, 0.4, 0.0), over: 'Samenschirmchen', mood: 'sanft und kichernd', idle: 'Samen lösen sich und schweben', attack: 'Sprung, Samenwolke heilt' },
  { id: 'snowman', faction: 'elementar', fam: 'kugelig', h: 2.0, main: '#f4f8ff', acc: '#7fc8ff', cat: 'kopfbedeckung', sig: 'Frostkrone aus Eiszapfen', zones: ['Strickschal'], prop: P(0.3, 0.0, 0.6, 0.4, 0.3), over: 'Rübennase mit Raureif', mood: 'frostig-freundlich', idle: 'Schneeflocken rieseln um ihn', attack: 'Frostaura pulsiert' },

  // ───────────── Tiere und Drachen ─────────────
  { id: 'baby-dragon', faction: 'tiere', fam: 'gefluegelt', h: 1.75, main: '#35b6a0', acc: '#ffe3b0', cat: 'kopfbedeckung', sig: 'Eierschalen-Mütze', zones: ['Lätzchen'], prop: P(0.45, 0.15, 0.4, 0.4, 0.6), over: 'Kopf so groß wie der Bauch, Stummelflügel', mood: 'verspielt und neugierig', idle: 'schielt nach der Eierschale, Schwanz wedelt', attack: 'holt Luft, Bauch bläht sich, spuckt einen Feuerball und hustet Rauch' },
  { id: 'electro-dragon', faction: 'tiere', fam: 'gefluegelt', h: 2.0, main: '#3a3aa0', acc: '#ffe14a', cat: 'koerper', sig: 'Blitzableiter-Horn mit Kupferspule', zones: ['Flügelsaum'], prop: P(0.3, 0.15, 0.4, 0.4, 0.9), over: 'statisch abstehende Mähne', mood: 'nervös, zuckt', idle: 'Funken zwischen Horn und Schwanzspitze', attack: 'Horn lädt auf, Kettenblitz aus dem Maul' },
  { id: 'inferno-dragon', faction: 'tiere', fam: 'gefluegelt', h: 2.15, main: '#5a2a2a', acc: '#ff9d2e', cat: 'werkzeug', sig: 'Brennglas in Messingfassung vor dem Maul', zones: ['Halfterriemen'], prop: P(0.28, 0.15, 0.4, 0.4, 0.9), over: 'Brennglas so groß wie der Kopf', mood: 'brütend und konzentriert', idle: 'Rauch aus den Nüstern, Linse glänzt', attack: 'Hitzestrahl durch die Linse, die mit jeder Stufe heller glüht' },
  { id: 'phoenix', faction: 'tiere', fam: 'gefluegelt', h: 1.9, main: '#ffb02e', acc: '#e0306f', cat: 'koerper', sig: 'Schleppfedern wie Flammenbänder', zones: ['Fußring'], prop: P(0.26, 0.2, 0.4, 0.4, 1.2), over: 'Flammenkamm', mood: 'stolz und feurig', idle: 'Federn lodern, Kopfnicken', attack: 'Krallenhieb im Flug; Formen: glühendes Ei, flaumiges Küken' },
  { id: 'bats', faction: 'tiere', fam: 'gefluegelt', h: 0.95, main: '#4f5d7a', acc: '#ff7aa8', cat: 'koerper', sig: 'Lindenblatt-Ohren und ein einzelner Zahn', zones: ['Flügelspitzen-Bänder'], prop: P(0.6, 0.0, 0.3, 0.3, 0.0), over: 'Ohren größer als der Körper', mood: 'hibbelig, quietscht', idle: 'flattert schnell im Kreis', attack: 'Sturzflug-Biss', variants: ['Ohr geknickt', 'Zahn links', 'Bauchfleck'] },
  { id: 'minions', faction: 'tiere', fam: 'gefluegelt', h: 1.3, main: '#7c5cc4', acc: '#ff9f43', cat: 'koerper', sig: 'einzelnes Stirnhorn und Pik-Schwanz', zones: ['Halstuch'], prop: P(0.45, 0.15, 0.6, 0.45, 0.3), over: 'Pik-Schwanzspitze', mood: 'frech und zappelig', idle: 'flattern, zeigen auf Ziele', attack: 'spucken eine glühende Kugel', variants: ['Horn gebogen', 'Horn gerade', 'Zahnlücke'] },
  { id: 'mega-minion', faction: 'tiere', fam: 'gefluegelt', h: 1.85, main: '#7a7590', acc: '#ffb347', cat: 'koerper', sig: 'Steinbauch-Panzer mit Wasserspeier-Hörnern', zones: ['Armbinde'], prop: P(0.32, 0.18, 0.8, 0.6, 0.3), over: 'kleine Flügel tragen einen schweren Steinbauch', mood: 'grimmig, ächzt', idle: 'Flügel arbeiten schwer, Bauch schaukelt', attack: 'Sturzfaust von oben' },
  { id: 'minion-giant', faction: 'tiere', fam: 'gefluegelt', h: 2.6, main: '#6a1a6e', acc: '#c8ff6b', cat: 'koerper', sig: 'Kehlsack, der sich vor dem Spucken aufbläht', zones: ['Ohrmarke', 'Armbinde'], prop: P(0.26, 0.15, 0.9, 0.6, 0.3), over: 'genähte Laborflügel', mood: 'träge und verfressen', idle: 'Kehlsack bläht sich langsam', attack: 'Kehlsack bläht sich auf, Giftspucke im Bogen' },
  { id: 'royal-hogs', faction: 'tiere', fam: 'vierbeinig', h: 1.15, main: '#f3cdb5', acc: '#f2c14e', cat: 'kopfbedeckung', sig: 'Minikrone zwischen den Ohren', zones: ['Schleife am Ringelschwanz'], prop: P(0.45, 0.2, 0.0, 0.0, 0.0), over: 'Schweineschnauze groß wie der Kopf', mood: 'quiekend und stolz', idle: 'schnüffeln, Ohren wackeln', attack: 'Kopfstoß mit Kronenspitze', variants: ['Fleck am Ohr', 'Krone schief', 'Doppelkinn'] },
  { id: 'cursed-hog', faction: 'tiere', fam: 'vierbeinig', h: 1.25, main: '#c79ad8', acc: '#5b8a2a', cat: 'kopfbedeckung', sig: 'Mini-Hexenhut mit Fluchsternchen', zones: ['Hutband'], prop: P(0.48, 0.18, 0.0, 0.0, 0.0), over: 'Fluchrauch aus den Ohren', mood: 'verwirrt und grantig', idle: 'grunzt, Fluchsternchen kreisen', attack: 'Rammstoß' },
  { id: 'rhino', faction: 'tiere', fam: 'vierbeinig', h: 2.0, main: '#8a8f80', acc: '#c9b13f', cat: 'koerper', sig: 'Doppelhorn mit Sichelmond-Schutzplatte', zones: ['Satteldecke'], prop: P(0.3, 0.25, 0.0, 0.0, 0.5), over: 'Panzerfalten wie Plattenrüstung', mood: 'stur und schnaubend', idle: 'scharrt mit dem Huf', attack: 'Ansturm mit gesenktem Horn' },

  // ───────────── Reiter ─────────────
  { id: 'hog-rider', faction: 'krone', fam: 'reiter', h: 2.15, main: '#b3735a', acc: '#ff8c1a', cat: 'reittier', sig: 'Karottenangel vor der Schweineschnauze', zones: ['Rennseide-Rauten', 'Satteldecke'], prop: P(0.26, 0.0, 0.85, 0.45, 0.6), over: 'Rennbrille und flatternde Jockeymütze', mood: 'übermütig, jauchzt', idle: 'Schwein scharrt, Reiter wippt im Sattel', attack: 'Polo-Schlag seitlich von oben; Flusssprung mit flatternden Ohren' },
  { id: 'dark-prince', faction: 'krone', fam: 'reiter', h: 2.35, main: '#3b3350', acc: '#9be564', cat: 'reittier', sig: 'gepanzerter Waran als Reittier', zones: ['Schabracke', 'Schildmitte'], prop: P(0.22, 0.0, 0.85, 0.45, 0.6), over: 'Waran-Krallen und Stachelschulter', mood: 'düster und arrogant', idle: 'Waran züngelt, Morgenstern pendelt', attack: 'Rundumschlag mit dem Morgenstern' },
  { id: 'ram-rider', faction: 'nordvolk', fam: 'reiter', h: 2.3, main: '#f1e6d0', acc: '#2b8c7a', cat: 'reittier', sig: 'Widder mit Doppelspiral-Hörnern und Glöckchen', zones: ['Satteldecke', 'Zopfbänder'], prop: P(0.24, 0.0, 0.85, 0.42, 0.5), over: 'Hörner groß wie Wagenräder', mood: 'abenteuerlustig, ruft', idle: 'Widder schüttelt die Glöckchen', attack: 'Widder rammt; die Reiterin wirbelt die Bola' },

  // ───────────── Gesindel (Banditen, Fischer, Jäger …) ─────────────
  { id: 'bandit', faction: 'gesindel', fam: 'geduckt', h: 1.7, main: '#cf6a2a', acc: '#3c3a4a', cat: 'kostuem', sig: 'Fuchsohr-Kapuze mit Fuchsschwanz-Schal', zones: ['Schalknoten', 'Gürtel'], prop: P(0.34, 0.3, 0.9, 0.45, 0.35), over: 'buschiger Schwanzschal', mood: 'verschlagen, grinst', idle: 'wirft den Knüppel hoch und fängt ihn', attack: 'Uppercut mit dem Knüppel; Sprint als Schemen mit Nachbildern' },
  { id: 'boss-bandit', faction: 'gesindel', fam: 'keil', h: 2.0, main: '#9a6274', acc: '#f2c14e', cat: 'ruecken', sig: 'Beutesack über der Schulter, aus dem Münzen fallen', zones: ['Mantelfutter', 'Halstuch'], prop: P(0.28, 0.34, 0.95, 0.45, 0.5), over: 'riesiger Silberfuchs-Kragen', mood: 'selbstsicher und arrogant', idle: 'wirft eine Münze hoch', attack: 'Doppelschlag mit zwei Brecheisen; Rauchgranate zur Flucht' },
  { id: 'fisherman', faction: 'gesindel', fam: 'breit', h: 1.9, main: '#f2c230', acc: '#2e7d6b', cat: 'werkzeug', sig: 'Angelrute mit Riesen-Blinker', zones: ['Halstuch', 'Hutband'], prop: P(0.33, 0.23, 0.92, 0.55, 1.2), over: 'Südwester mit breiter Krempe', mood: 'knurrig-gemütlich, Pfeife im Mund', idle: 'zieht an der Pfeife, prüft die Schnur', attack: 'Rutenstoß; Auswurf mit dem Blinker, Schnur spannt, Einholen' },
  { id: 'hunter', faction: 'gesindel', fam: 'breit', h: 1.9, main: '#5e4a26', acc: '#c4602d', cat: 'waffe', sig: 'Donnerbüchse mit Trichtermündung', zones: ['Patronengurt-Schärpe', 'Mützenschwanz-Band'], prop: P(0.32, 0.24, 0.9, 0.55, 0.75), over: 'Biberfellmütze mit Schwanz', mood: 'brummig, kneift ein Auge zu', idle: 'stopft Pulver nach', attack: 'Anlegen, Bumm mit starkem Rückstoß' },
  { id: 'miner', faction: 'gesindel', fam: 'geduckt', h: 1.7, main: '#6e5e58', acc: '#ffd84d', cat: 'koerper', sig: 'Maulwurf-Schaufelkrallen', zones: ['Halstuch'], prop: P(0.36, 0.22, 0.8, 0.8, 0.0), over: 'Krallen breiter als der Kopf', mood: 'kurzsichtig und fleißig', idle: 'schnuppert mit der Rüsselnase', attack: 'Krallenhieb; taucht als Erdhügel unter' },
  { id: 'mighty-miner', faction: 'gesindel', fam: 'breit', h: 2.35, main: '#e0a030', acc: '#6f7682', cat: 'werkzeug', sig: 'Bohrer statt rechtem Arm', zones: ['Helmband', 'Gürtel'], prop: P(0.28, 0.22, 1.0, 0.65, 0.5), over: 'Bauhelm mit greller Stirnlampe', mood: 'polternd und zufrieden', idle: 'lässt den Bohrer kurz aufheulen', attack: 'Bohrer bohrt mit steigender Drehzahl; Flucht durch die Erde mit Bombe' },
  { id: 'ronin', faction: 'gesindel', fam: 'schlank', h: 2.0, main: '#5b6b4f', acc: '#d9c8a0', cat: 'kopfbedeckung', sig: 'tiefer Strohhut mit Papiersiegel', zones: ['Hüftschärpe', 'Siegelband'], prop: P(0.28, 0.38, 0.95, 0.42, 0.65), over: 'Hutkrempe breiter als die Schultern', mood: 'ruhig und wachsam', idle: 'steht still, Hand am Griff', attack: 'Ziehen und Schlag in einer Bewegung; Parade mit Funken' },
  { id: 'firecracker', faction: 'gesindel', fam: 'schlank', h: 1.6, main: '#1fb5c4', acc: '#ff4fa3', cat: 'waffe', sig: 'Papierschirm, dessen Speichen Raketen sind', zones: ['Schirmrand', 'Gürtelschleife'], prop: P(0.36, 0.3, 0.85, 0.42, 0.7), over: 'Wunderkerzen im Haarknoten', mood: 'aufgekratzt, lacht laut', idle: 'dreht den Schirm, Funken sprühen', attack: 'Schirm nach vorn, Rakete zischt, Rückstoß-Hüpfer nach hinten' },
  { id: 'battle-healer', faction: 'gesindel', fam: 'breit', h: 1.85, main: '#8fb573', acc: '#f4ecd8', cat: 'ruecken', sig: 'Mörser-Rucksack mit Kräutern', zones: ['Kopftuch', 'Schürzenband'], prop: P(0.32, 0.22, 0.9, 0.55, 0.8), over: 'Riesenstößel als Keule', mood: 'resolut und fürsorglich', idle: 'zerstößt Kräuter in der Luft und schnuppert', attack: 'Stößel von oben wie beim Zerstoßen, Kräuterwolke heilt' },
  { id: 'bomber', faction: 'gesindel', fam: 'kugelig', h: 1.45, main: '#3a3532', acc: '#f2efe6', cat: 'kopfbedeckung', sig: 'Zylinder voller Bomben', zones: ['Halstuch', 'Hutband'], prop: P(0.4, 0.18, 0.75, 0.45, 0.4), over: 'Zylinder höher als der Körper', mood: 'kichernd und schelmisch', idle: 'jongliert eine Bombe, Ruß bröselt', attack: 'lüpft den Hut, zieht eine Bombe, Wurf im hohen Bogen' },
  { id: 'balloon', faction: 'gesindel', fam: 'schwebend', h: 2.6, main: '#7a3b69', acc: '#c9a24a', cat: 'koerper', sig: 'Zwiebelkuppel-Ballon aus Flicken mit Messingpropeller', zones: ['Wimpelkette', 'Korbrand'], prop: P(0.12, 0.0, 0.5, 0.4, 0.3), over: 'Gnom-Pilot mit Riesen-Hörrohr', mood: 'schadenfroh kichernder Pilot', idle: 'Ballon schaukelt, Propeller dreht, Pilot lauscht', attack: 'Pilot wuchtet eine Bombe über den Korbrand' },
  { id: 'rascal-boy', faction: 'gesindel', fam: 'breit', h: 1.95, main: '#c8a46a', acc: '#3f8f3f', cat: 'kostuem', sig: 'Rüstung aus Pappkartons mit Klebeband', zones: ['Kappe', 'Klebeband-Streifen'], prop: P(0.36, 0.24, 0.9, 0.5, 0.6), over: 'Kochtopfdeckel als Schild', mood: 'großspurig, Zahnlücke', idle: 'wedelt mit dem Holzschwert', attack: 'Holzschwert-Kloppe von oben' },
  { id: 'rascal-girl', faction: 'gesindel', fam: 'winzig', h: 1.5, main: '#e8879a', acc: '#3a3d5c', cat: 'waffe', sig: 'Astgabel-Schleuder', zones: ['Haarschleifen', 'Latzhosen-Träger'], prop: P(0.44, 0.24, 0.8, 0.42, 0.35), over: 'Zöpfe, die beim Schießen hochfliegen', mood: 'frech, Sommersprossen', idle: 'sucht Steinchen am Boden', attack: 'Schleuder spannen, Zielen mit einem Auge, Schuss', variants: ['Zöpfe', 'Pferdeschwanz'] },
  { id: 'suspicious-bush', faction: 'gesindel', fam: 'amorph', h: 1.35, main: '#3f8f3a', acc: '#ffd23f', cat: 'koerper', sig: 'zwei Augenpaare im Busch und große Schuhe', zones: ['Schnürsenkel'], prop: P(0.0, 0.12, 0.0, 0.0, 0.0), over: 'Schuhe unter dem Busch', mood: 'verdächtig unschuldig', idle: 'Augen blinzeln abwechselnd', attack: 'Busch springt auf, zwei Kobolde hüpfen heraus' },

  // ───────────── Helden (Basisfigur + Rang-Merkmal + Spezial-Pose) ─────────────
  { id: 'knight-hero', base: 'knight', faction: 'krone', fam: 'breit', h: 1.95, main: '#c8a090', acc: '#e0a83a', cat: 'umhang', sig: 'Löwenmähnen-Kragen mit Heldenumhang', zones: ['Umhang', 'Schildfeld'], prop: P(0.35, 0.22, 0.85, 0.5, 0.75), over: 'Zinnenschild mit goldener Krone', mood: 'herausfordernd, ruft zum Kampf', idle: 'Spott-Pose: schlägt mit dem Schwert auf den Schild und winkt Gegner heran', attack: 'Schild vor, Hieb von oben' },
  { id: 'giant-hero', base: 'giant', faction: 'riesen', fam: 'massig', h: 2.9, main: '#c08a46', acc: '#f3d36b', cat: 'kopfbedeckung', sig: 'Erntekrone aus Weizenähren', zones: ['Steppdecken-Umhang', 'Bommel'], prop: P(0.19, 0.21, 1.12, 0.8, 0.2), over: 'Steppdecken-Umhang', mood: 'stolzer Erntekönig', idle: 'Heldenwurf-Pose: packt die Luft und holt weit aus', attack: 'Hammerfaust; Fähigkeit: packt eine Truppe und schleudert sie' },
  { id: 'mini-pekka-hero', base: 'mini-pekka', faction: 'werkstatt', fam: 'mechanisch', h: 1.8, main: '#6fa08a', acc: '#f0b23a', cat: 'ruecken', sig: 'Pfannkuchen-Turm auf dem Rücken mit Sirupflasche', zones: ['Brustplakette', 'Serviette'], prop: P(0.48, 0.22, 0.8, 0.5, 0.7), over: 'Pfannkuchen-Stapel mit drei Füllleisten', mood: 'verfressen und begeistert', idle: 'Pfannkuchen-Pose: schnuppert am Stapel, Pfeife trällert', attack: 'Rohrzangen-Schlag; Fähigkeit: verschlingt die Pfannkuchen' },
  { id: 'musketeer-hero', base: 'musketeer', faction: 'krone', fam: 'schlank', h: 2.05, main: '#3f8a63', acc: '#f2d58a', cat: 'werkzeug', sig: 'Werkzeuggürtel mit Kurbel und Bauplan-Rolle', zones: ['Hutfeder', 'Schärpe'], prop: P(0.31, 0.36, 0.9, 0.4, 1.0), over: 'Federhut mit Orden', mood: 'tüchtig, plant voraus', idle: 'Bauplan-Pose: entrollt den Plan und zeigt nach vorn', attack: 'Musketenschuss; Fähigkeit: wirft den Geschützturm-Bausatz' },
  { id: 'ice-golem-hero', base: 'ice-golem', faction: 'elementar', fam: 'kugelig', h: 2.05, main: '#c8f0ff', acc: '#ffcf6b', cat: 'kopfbedeckung', sig: 'Eiskrone mit Schneeflocken-Zacken', zones: ['Frostschärpe', 'Strickschal'], prop: P(0.28, 0.18, 0.8, 0.55, 0.3), over: 'Schneesturm-Wirbel um den Bauch', mood: 'majestätisch-verschlafen', idle: 'Schneesturm-Pose: Arme hoch, Wirbel kreist', attack: 'Kopfstoß; Fähigkeit: drei Eisstöße' },
  { id: 'wizard-hero', base: 'wizard', faction: 'zirkel', fam: 'dreieckig', h: 2.05, main: '#b4307a', acc: '#ff8a3a', cat: 'umhang', sig: 'Flammenumhang, der sich zu Flügeln öffnet', zones: ['Gürtelschärpe', 'Hutband'], prop: P(0.3, 0.0, 0.85, 0.45, 0.35), over: 'Feuerflügel im Flug', mood: 'großspurig, hebt ab', idle: 'Flug-Pose: Umhang bauscht sich, Füße heben ab', attack: 'Feuerball aus dem Buch; Fähigkeit: Feuriger Flug mit Wirbeln' },
  { id: 'goblins-hero', base: 'goblins', faction: 'kobolde', fam: 'winzig', h: 1.4, main: '#533143', acc: '#ffd34d', skin: '#7fae4a', cat: 'fahne', sig: 'Brigade-Banner auf dem Rücken', zones: ['Bannertuch', 'Halstuch'], prop: P(0.46, 0.22, 0.8, 0.45, 0.6), over: 'Banner doppelt so hoch wie der Kobold', mood: 'kriegerisch-frech, Kriegsbemalung', idle: 'Banner-Pose: schwenkt das Banner', attack: 'Löffeldolch-Stich; Fähigkeit: rammt das Banner in den Boden' },
  { id: 'mega-minion-hero', base: 'mega-minion', faction: 'tiere', fam: 'gefluegelt', h: 1.95, main: '#9a93b3', acc: '#ffd36b', cat: 'kopfbedeckung', sig: 'Visierhelm mit Heldenstern', zones: ['Armbinde', 'Helmbusch'], prop: P(0.31, 0.18, 0.85, 0.6, 0.3), over: 'Steinbauch mit Goldgravur', mood: 'jagend, fixiert sein Ziel', idle: 'Sprung-Pose: duckt sich in der Luft zum Teleport', attack: 'Sturzfaust; Fähigkeit: Teleport zum schwächsten Gegner' },
  { id: 'magic-archer-hero', base: 'magic-archer', faction: 'zirkel', fam: 'schlank', h: 2.1, main: '#6a52b8', acc: '#fff0a8', cat: 'umhang', sig: 'Sternbild-Mantel mit drei leuchtenden Pfeilsternen', zones: ['Hutband', 'Umhangfutter'], prop: P(0.3, 0.38, 0.95, 0.4, 0.9), over: 'Sternbilder, die sich auf dem Mantel bewegen', mood: 'gerissen und verspielt', idle: 'Dreifach-Pose: fächert drei Pfeile auf', attack: 'Lichtpfeil; Fähigkeit: Sprung zurück, Lockvogel bleibt stehen' },
  { id: 'balloon-hero', base: 'balloon', faction: 'gesindel', fam: 'schwebend', h: 2.75, main: '#f08a5a', acc: '#2f4f6f', cat: 'begleiter', sig: 'Skelett-Kadett mit Fallschirm im Korb', zones: ['Wimpelkette', 'Korbrand'], prop: P(0.12, 0.0, 0.55, 0.4, 0.3), over: 'Fallschirm-Ausleger am Korb', mood: 'Pilot und Kadett salutieren', idle: 'Absprung-Pose: Kadett klettert auf den Korbrand', attack: 'Bombenabwurf; Fähigkeit: Kadett springt mit Fallschirm ab' },
  { id: 'bowler-hero', base: 'bowler', faction: 'riesen', fam: 'massig', h: 2.75, main: '#e6e2d8', acc: '#ffcf6b', cat: 'kopfbedeckung', sig: 'Krone aus Kegeln', zones: ['Hosenträger', 'Kegelband'], prop: P(0.25, 0.25, 1.08, 0.65, 0.35), over: 'Kegelkrone', mood: 'triumphierender Kegelkönig', idle: 'Mörser-Pose: stemmt einen Felsen über den Kopf', attack: 'Kegelwurf; Fähigkeit: Felswürfe im hohen Bogen' },
  { id: 'dark-prince-hero', base: 'dark-prince', faction: 'krone', fam: 'reiter', h: 2.5, main: '#2f3d33', acc: '#c6f07a', cat: 'kopfbedeckung', sig: 'Sichelmond-Krone über dem Visier', zones: ['Schabracke', 'Schildmitte'], prop: P(0.22, 0.0, 0.85, 0.45, 0.6), over: 'reitet ein gepanzertes Nashorn', mood: 'eiskalt und siegesgewiss', idle: 'Absprung-Pose: steht in den Steigbügeln', attack: 'Morgenstern-Rundumschlag; Fähigkeit: springt ab, das Nashorn stürmt allein' },
  { id: 'berserker-hero', base: 'berserker', faction: 'nordvolk', fam: 'keil', h: 1.85, main: '#6b4a30', acc: '#6b8a4a', cat: 'umhang', sig: 'Bärenfell-Umhang mit Bärenkopf-Kapuze', zones: ['Schürze', 'Zopfbänder'], prop: P(0.33, 0.3, 0.95, 0.5, 0.5), over: 'Bärengeist-Schemen bei der Wut', mood: 'wild, brüllt wie ein Bär', idle: 'Wut-Pose: Pfannen hoch, Bärenkopf brüllt', attack: 'Pfannen-Wirbel; Fähigkeit: Bärengeist-Raserei' },
  { id: 'valkyrie-hero', base: 'valkyrie', faction: 'nordvolk', fam: 'breit', h: 2.05, main: '#7a9aa8', acc: '#f0b24a', cat: 'kopfbedeckung', sig: 'Sturmflügelhelm mit goldenen Schwingen', zones: ['Gürtel', 'Windbänder'], prop: P(0.31, 0.28, 0.9, 0.5, 0.7), over: 'Windbänder an der Axt', mood: 'stürmisch', idle: 'Wirbelwind-Pose: Axt über dem Kopf kreisend', attack: 'Drehschlag; Fähigkeit: Wirbelwind' },
  { id: 'ice-wizard-hero', base: 'ice-wizard', faction: 'zirkel', fam: 'dreieckig', h: 2.0, main: '#eaf6ff', acc: '#5fd0c8', cat: 'begleiter', sig: 'kleiner Schneemann-Gehilfe auf der Schulter', zones: ['Schal', 'Mantelsaum'], prop: P(0.31, 0.0, 0.8, 0.45, 0.85), over: 'Schneekugel-Stab mit Schneemann darin', mood: 'großväterlich, lacht', idle: 'Frostkerl-Pose: formt einen Schneeball', attack: 'Eissplitter-Fächer; Fähigkeit: beschwört den Schneemann' },
  { id: 'tombstone-hero', base: 'tombstone', faction: 'gruft', fam: 'bauwerk', h: 2.5, main: '#6f7b8a', acc: '#d9b54a', cat: 'bauwerk', sig: 'Mausoleum mit Säulen und Krone über dem Tor', zones: ['Torbanner', 'Kranzschleife'], prop: P(0, 0, 0, 0, 0.3), over: 'Krone über dem Portal', mood: 'feierlich und unheimlich', idle: 'Tor knarrt, Licht flackert', attack: 'Skelette schlurfen heraus; Fähigkeit: Tor öffnet sich für die Grabkönigin' },
];

/** Formen gehören zur Basisfigur (eigene Teile im selben Modell). */
export const FORM_LOOKS = {
  'cannon-cart-cannon': { figure: 'cannon-cart', form: 'cannon', note: 'Rohr auf Dreibein, Karren zerbrochen, Kanonier hält sich die Ohren zu' },
  'goblin-demolisher-kamikaze': { figure: 'goblin-demolisher', form: 'kamikaze', note: 'Helmlunte brennt, rennt mit nach hinten gestreckten Armen' },
  'phoenix-egg': { figure: 'phoenix', form: 'egg', note: 'glühendes Ei mit Rissen, pulsiert' },
  'phoenix-reborn': { figure: 'phoenix', form: 'reborn', note: 'flaumiges Küken mit kleiner Flamme' },
  'magic-archer-decoy': { figure: 'magic-archer-hero', form: 'decoy', note: 'Sternenstaub-Doppelgänger, halb durchsichtig' },
  'lumberjack-ghost': { figure: 'lumberjack', form: 'ghost', note: 'durchscheinender Geist mit leuchtender Axt' },
};

/** Evo-Optik pro Figur (Phase 5): Farbschema, zusätzliche Rüstung, Leuchtkanten, Partikelhülle. */
export const EVO_LOOKS = {};

export const figureById = new Map(FIGURES.map((f) => [f.id, f]));
