// Design-Briefs: Elementar (Golems, Elixier, Lava, Eis, Geister)
export default {
  golem: {
    concept: 'Der Golem ist ein uralter, träger Riese aus rosa Granit mit einem leuchtenden türkisen Schlussstein im Brustkorb. Auf seiner Schulter wächst ein Bäumchen mit einem Vogelnest. Er stapft zu Gebäuden, und stirbt er, zerfällt er in zwei Golemiten.',
    unique: 'Das Bäumchen mit Vogel auf der Schulter ist ein lebendes Detail, das kein anderer Riese hat; der rosa Granit ist eine einmalige Steinfarbe. Felsgolems anderer Spiele sind grau mit Moos; dieser ist rosa mit Baum und Vogel.',
    silhouette: 'Riesiger Berg mit flachem kleinem Kopf, riesigen Felsfäusten und einem Baum, der über eine Schulter ragt.',
    mainName: 'Rosengranit',
    accName: 'Türkis (Schlussstein, Adern)',
    materials: [['Baumgrün', '#5a8a3a'], ['Rinde', '#6b4a32'], ['Vogel', '#f0c040']],
    signature: 'Ein kleiner Baum mit Vogelnest auf der linken Schulter; der Vogel hüpft herum.',
    details: {
      kleidung: 'Steinplatten, Granitbrocken',
      material: 'Granit, Moos, Holz',
      muster: 'Granitsprenkel, Risse mit Türkisglühen',
      schnallen: 'keine',
      abnutzung: 'abgesplitterte Kanten',
      accessoires: 'Tuch am Bäumchen und Armband (Teamzonen)',
    },
    face: 'Zwei türkis glühende Augenschlitze unter einer schweren Steinstirn, ein dünner Mundriss, der brummt.',
    weapon: 'Zwei Felsfäuste so groß wie der Rumpf, mit türkis glühenden Rissen an den Knöcheln.',
    anim: {
      idle: ['ein Vogel hüpft im Bäumchen, der Golem brummt'],
      walk: ['langsamer Stampfgang mit `char.step` (XXL-Beben), Blätter rieseln'],
      attack: ['beide Fäuste hoch (Anticipation, Stretch), Doppelhieb (Squash)'],
      hit: ['Steinstaub rieselt'],
      spawn: ['landet mit Beben, der Vogel flattert auf'],
      death: ['bricht auseinander, zwei Golemiten rollen heraus, der Baum fällt'],
    },
  },
  golemite: {
    concept: 'Der Golemit ist ein trotziges Bruchstück des Golems: eine halbe Säule als Rumpf mit einem abgebrochenen Kapitell als Kopf. Er stapft weiter zu Gebäuden.',
    unique: 'Die halbe Säule mit Kapitell-Kopf ist eine einmalige Form; als Bruchstück des Golems trägt er dessen Granit und Türkisglühen. Golem-Teile anderer Spiele sind Felsbrocken; dieser ist eine Säule.',
    silhouette: 'Kugelig-gedrungen, oben das breite Kapitell, kurze Steinarme.',
    mainName: 'Dunkler Rosengranit',
    accName: 'Türkis',
    materials: [['Moos', '#6a8a3a']],
    signature: 'Ein abgebrochenes Säulenkapitell mit Voluten als Kopf.',
    details: {
      kleidung: 'Säulenschaft, Kapitell',
      material: 'Granit',
      muster: 'Kannelur, Bruchkanten',
      schnallen: 'keine',
      abnutzung: 'frische Bruchkante',
      accessoires: 'Armband (Teamzone)',
    },
    face: 'Türkise Augen zwischen den Voluten, ein trotziger Mund.',
    weapon: 'Kopfstoß mit dem Kapitell.',
    anim: {
      idle: ['bröselt'],
      walk: ['watschelnd'],
      attack: ['Kopfstoß mit dem Kapitell'],
      hit: ['Brocken springen ab'],
      spawn: ['rollt aus dem zerfallenden Golem'],
      death: ['zerfällt in Kiesel (Todesschaden)'],
    },
  },
  'elixir-golem': {
    concept: 'Der Elixiergolem ist ein tumb-fröhlicher Riese aus einem großen Glaskolben voller blubberndem magentafarbenem Elixier mit einem Korken als Kopf. Er läuft zu Gebäuden, zerplatzt in zwei Golemiten und diese in Kleckse. Jeder Teil schenkt dem Gegner Elixier.',
    unique: 'Ein durchsichtiger Glasbauch mit Flüssigkeit und Blasen sowie der Korkkopf sind einmalig. Elixiergolems anderer Spiele sind pinke Steinwesen; dieser ist ein Glaskolben.',
    silhouette: 'Massig, großer runder Bauch aus Glas, kleiner Korkkopf, Arme aus Glasröhren mit Messingmanschetten.',
    mainName: 'Elixier-Magenta',
    accName: 'Glasweiß',
    materials: [['Kork', '#b8864a'], ['Messing', '#c8a046']],
    signature: 'Ein Glasbauch mit blubbernder Flüssigkeit, Blasen und Spiegelungen.',
    details: {
      kleidung: 'Glaskörper, Korken, Messingbänder',
      material: 'Glas, Kork, Messing, Elixier',
      muster: 'Blasen, Messskala am Bauch',
      schnallen: 'Messingmanschetten',
      abnutzung: 'Kratzer im Glas',
      accessoires: 'Halsband und Korkensiegel (Teamzonen)',
    },
    face: 'Gesicht auf dem Korken mit großen dummen Augen und blubberndem Mund.',
    weapon: 'Glasfäuste mit Elixier.',
    anim: {
      idle: ['Blasen steigen, die Flüssigkeit schwappt'],
      walk: ['schwappender Gang mit `char.step`'],
      attack: ['schwappende Doppelfaust'],
      hit: ['Glas klirrt, Flüssigkeit spritzt'],
      spawn: ['plumpst, die Flüssigkeit schwappt hoch'],
      death: ['zerplatzt in zwei Golemiten, Elixiertropfen'],
    },
  },
  'elixir-golemite': {
    concept: 'Der Elixiergolemit ist ein aufgeregter Erlenmeyerkolben auf Stummelbeinen mit Stopfen als Kopf und einer Messskala am Bauch. Er zerfällt später in zwei Kleckse.',
    unique: 'Die Kolbenform mit Messskala ist einmalig. Kleine Elixierwesen anderer Spiele sind Kleckse; dieser ist ein Laborkolben.',
    silhouette: 'Kugelig-dreieckig wie ein Kolben, oben der Stopfen.',
    mainName: 'Elixierviolett',
    accName: 'Glaswasser',
    materials: [['Stopfen (Gummi)', '#4a3a40']],
    signature: 'Ein Erlenmeyerkolben-Körper mit Gummistopfen und Skala.',
    details: {
      kleidung: 'Glaskolben, Stopfen',
      material: 'Glas, Gummi, Elixier',
      muster: 'Skala, Blasen',
      schnallen: 'keine',
      abnutzung: 'Sprung im Glas',
      accessoires: 'Halsband (Teamzone)',
    },
    face: 'Aufgeregte Augen im Glas, Mund auf dem Stopfen.',
    weapon: 'Kopfnuss mit dem Stopfen.',
    anim: {
      idle: ['schwappt'],
      walk: ['tippelt'],
      attack: ['Kopfnuss'],
      hit: ['Glas klirrt'],
      spawn: ['rollt aus den Scherben'],
      death: ['zerplatzt in zwei Kleckse'],
    },
  },
  'elixir-blob': {
    concept: 'Der Elixierklecks ist ein quietschfideler Klecks aus rosa Elixier mit einem winzigen Korkhütchen. Er hüpft zu Gebäuden und platscht dagegen.',
    unique: 'Glänzender Klecks mit Korkhut und riesigen Augen ist einmalig. Kleckse anderer Spiele sind formlos; dieser trägt einen Hut.',
    silhouette: 'Tropfenförmiger Blob mit kleinem Hut oben.',
    mainName: 'Elixierrosa',
    accName: 'Korkbraun',
    materials: [['Glanz', '#ffe8fa']],
    signature: 'Ein winziges Korkhütchen auf dem Klecks.',
    details: {
      kleidung: 'Korkhut',
      material: 'Elixier, Kork',
      muster: 'Glanzpunkte',
      schnallen: 'keine',
      abnutzung: 'keine',
      accessoires: 'Hutband (Teamzone)',
    },
    face: 'Riesige glänzende Augen und ein kleiner Mund.',
    weapon: 'Er selbst: ein Platscher mit dem ganzen Körper, der beim Aufprall flach wird und wieder zurückfedert.',
    anim: {
      idle: ['wabbelt'],
      walk: ['hüpft mit Squash und Stretch'],
      attack: ['Platscher nach vorn'],
      hit: ['zerfließt kurz'],
      spawn: ['tropft heraus'],
      death: ['zerplatzt in Tröpfchen'],
    },
  },
  'ice-golem': {
    concept: 'Der Eisgolem ist ein verschlafen-friedlicher Riese aus einem Eisblock mit einem eingefrorenen Fisch im Bauch und einem gestrickten Schal. Er läuft zu Gebäuden. Stirbt er, verlangsamt eine Frostexplosion alles in der Nähe.',
    unique: 'Der eingefrorene Fisch im durchsichtigen Eisbauch ist einmalig; der Strickschal (Teamzone) ist ein warmes Detail an einem Eiswesen. Eisgolems anderer Spiele sind kantige Blöcke; dieser ist rund mit Fisch.',
    silhouette: 'Kugeliger Eisbauch mit kleinem Kopf und kurzen Armen, Schal mit wehenden Enden.',
    mainName: 'Eisblau',
    accName: 'Fischorange',
    materials: [['Eiskanten', '#e8fbff'], ['Schal', '#ff00f1']],
    signature: 'Ein orangefarbener Fisch ist im Bauch eingefroren und schaut überrascht.',
    details: {
      kleidung: 'Strickschal',
      material: 'Eis, Wolle',
      muster: 'Eisrisse, Strickmuster',
      schnallen: 'keine',
      abnutzung: 'Schmelztropfen',
      accessoires: 'Strickschal (Teamzone)',
    },
    face: 'Schläfrige Augen, ein gähnender Mund aus Eis.',
    weapon: 'Ein Kopfstoß mit der Eisstirn; beim Tod sprengt der Eisbauch in einer Frostwolke auseinander.',
    anim: {
      idle: ['gähnt, Eiskristalle rieseln'],
      walk: ['rutschender Watschelgang'],
      attack: ['Kopfstoß mit Frostklirren'],
      hit: ['Eis splittert'],
      spawn: ['landet, Schneestaub'],
      death: ['zerspringt, der Fisch fällt heraus und zappelt'],
    },
  },
  'lava-hound': {
    concept: 'Der Lavahund ist ein hechelnder, gutmütiger fliegender Riesenhund aus Basalt mit einem Vulkankrater auf dem Rücken. Lava-Adern leuchten zwischen seinen Basaltplatten. Er fliegt zu Gebäuden und zerplatzt beim Tod in sechs Lavawelpen.',
    unique: 'Der rauchende Krater auf dem Rücken ist einmalig; die Basaltplatten-Struktur unterscheidet ihn von allen Drachen. Lava-Wesen anderer Spiele sind fliegende Fischformen; dieser ist ein Hund mit Ohren und Zunge.',
    silhouette: 'Schwebend, rundlicher Hundekörper mit Hängeohren, kleinen Flügelstummeln, Kraterkegel oben.',
    mainName: 'Basalt',
    accName: 'Lavaorange',
    materials: [['Glut', '#ffd27a'], ['Rauch', '#5a5058']],
    signature: 'Ein kleiner rauchender Vulkankrater auf dem Rücken.',
    details: {
      kleidung: 'Basaltplatten',
      material: 'Basalt, Lava',
      muster: 'Lava-Adern',
      schnallen: 'keine',
      abnutzung: 'Krusten',
      accessoires: 'Halsband (Teamzone)',
    },
    face: 'Hundegesicht mit Hängeohren, glühenden Augen und heraushängender Lavazunge.',
    weapon: 'Lavaspucke aus dem Hundemaul: zähe, glühende Klumpen, die beim Aufprall Funken schlagen.',
    anim: {
      idle: ['Krater raucht, Zunge hängt heraus, Hecheln'],
      walk: ['schwebt mit Ohrenschlackern'],
      attack: ['Lavaspucke'],
      hit: ['Krusten bröckeln'],
      spawn: ['fällt mit Rauch ein und fängt sich'],
      death: ['zerplatzt in sechs Welpen und Basaltbrocken'],
    },
  },
  'lava-pup': {
    concept: 'Die Lavawelpe ist ein tapsiger fliegender Welpe aus rötlichem Basalt mit riesigen Welpenaugen und einem kringeligen Glutschwanz. Sie beißt kleine Glutbisse.',
    unique: 'Der Glutkringel-Schwanz und die Welpenaugen sind einmalig; als Junges des Lavahunds teilt sie Basalt und Lava. Lavawelpen anderer Spiele sind kleine Fische; diese ist ein Hündchen.',
    silhouette: 'Kleiner runder Welpe mit Flügelstummeln und Kringelschwanz.',
    mainName: 'Rötlicher Basalt',
    accName: 'Glutbernstein',
    materials: [],
    signature: 'Ein Schwanz, der sich als glühender Kringel einrollt.',
    details: {
      kleidung: 'keine',
      material: 'Basalt, Glut',
      muster: 'Glutpunkte',
      schnallen: 'keine',
      abnutzung: 'keine',
      accessoires: 'Halsband (Teamzone)',
    },
    face: 'Riesige runde Augen, Stupsnase, kleine Zunge.',
    weapon: 'Kleine Glutzähne, die beim Biss aufglühen und eine winzige Funkenwolke hinterlassen.',
    anim: {
      idle: ['jagt den eigenen Schwanz'],
      walk: ['flattert'],
      attack: ['Glutbiss'],
      hit: ['jault'],
      spawn: ['purzelt aus dem Lavahund'],
      death: ['zerfällt in Glutfunken'],
    },
  },
  'fire-spirit': {
    concept: 'Der Feuergeist ist ein übermütiges Kerzenwesen aus Wachs mit einer Flammenfrisur, die höher ist als der Körper. Er springt auf Gegner und explodiert.',
    unique: 'Kerzenwachs-Körper mit Tropfen und Flammenhaar sind einmalig. Feuergeister anderer Spiele sind Flammenbälle; dieser ist eine lebende Kerze.',
    silhouette: 'Zylinder mit Tropfen, oben eine hohe Flamme.',
    mainName: 'Flammenorange',
    accName: 'Glutgelb',
    materials: [['Wachs', '#f8e6c8']],
    signature: 'Ein Kerzenwachs-Körper mit herablaufenden Tropfen und einer Flammenfrisur.',
    details: {
      kleidung: 'Wachsmanschette',
      material: 'Wachs, Feuer',
      muster: 'Wachstropfen',
      schnallen: 'keine',
      abnutzung: 'geschmolzene Kanten',
      accessoires: 'Wachsmanschette (Teamzone)',
    },
    face: 'Freche Augen im Wachs und ein lachender Mund.',
    weapon: 'Er selbst (Explosion).',
    anim: {
      idle: ['tropft, die Flamme züngelt'],
      walk: ['hüpft'],
      attack: ['Hechtsprung und Explosion'],
      hit: ['Flamme flackert'],
      spawn: ['entzündet sich'],
      death: ['Explosion mit Wachsspritzern'],
    },
  },
  'ice-spirit': {
    concept: 'Der Eisgeist ist ein kichernder kleiner Kristall-Igel mit Eisstacheln. Er rollt sich zur Kugel, springt auf Gegner und friert sie ein.',
    unique: 'Igel-Silhouette mit Eiskristall-Stacheln ist einmalig. Eisgeister anderer Spiele sind Schneebälle; dieser ist ein Igel.',
    silhouette: 'Kleine Kugel mit Stachelkranz und Füßchen.',
    mainName: 'Frostweiß',
    accName: 'Stahlblau',
    materials: [],
    signature: 'Ein Kranz aus Eiskristall-Stacheln wie bei einem Igel.',
    details: {
      kleidung: 'keine',
      material: 'Eis',
      muster: 'Facetten',
      schnallen: 'keine',
      abnutzung: 'keine',
      accessoires: 'Schleife (Teamzone)',
    },
    face: 'Kleine Knopfaugen, Stupsnase, kicherndes Mündchen.',
    weapon: 'Er selbst (Frostplatzer).',
    anim: {
      idle: ['rollt sich ein und wieder auf'],
      walk: ['rollt'],
      attack: ['Kugelsprung und Frostplatzer'],
      hit: ['Stacheln klirren'],
      spawn: ['rollt aus Schnee'],
      death: ['zerspringt in Eissplitter'],
    },
    special: { evo: 'Doppelfrost-Evo: Ein zweiter Stachelkranz und eine Krone aus Eiszapfen, dazu blau leuchtende Spitzen. Schneeflocken bilden die Partikelhülle; der zweite Frostschlag kommt mit Nachklirren.' },
  },
  'electro-spirit': {
    concept: 'Der Elektrogeist ist ein aufgekratzter Funke mit zwei Steckerzinken als Ohren und einem Zickzack-Schwanz. Er springt auf Gegner, und sein Blitz springt auf bis zu neun Ziele über.',
    unique: 'Steckerzinken-Ohren und Zickzack-Schwanz sind einmalig. Elektrogeister anderer Spiele sind Funkenkugeln; dieser hat Steckerohren.',
    silhouette: 'Tropfen mit zwei geraden Ohren oben und Zickzack unten.',
    mainName: 'Blitzgelb',
    accName: 'Violett',
    materials: [['Steckermetall', '#c8ccd2']],
    signature: 'Zwei Messing-Steckerzinken als Ohren.',
    details: {
      kleidung: 'keine',
      material: 'Elektrizität, Metall',
      muster: 'Funkenlinien',
      schnallen: 'keine',
      abnutzung: 'keine',
      accessoires: 'Schwanzband (Teamzone)',
    },
    face: 'Zickzack-Augen und ein breites Funkengrinsen.',
    weapon: 'Er selbst (Kettenblitz).',
    anim: {
      idle: ['zappelt, Funken'],
      walk: ['zuckt vorwärts'],
      attack: ['Sprung, Blitz springt weiter'],
      hit: ['flackert'],
      spawn: ['zündet mit Funken'],
      death: ['zerplatzt in Blitzfäden'],
    },
  },
  'heal-spirit': {
    concept: 'Der Heilungsgeist ist ein sanftes, kicherndes Pusteblumen-Wesen, dessen Kopf aus Samenschirmchen besteht. Er springt auf Gegner, macht Flächenschaden und hinterlässt ein Heilfeld aus schwebenden Samen.',
    unique: 'Pusteblumen-Kopf mit fliegenden Samen ist einmalig. Heilgeister anderer Spiele sind Lichtkugeln; dieser ist eine Pusteblume.',
    silhouette: 'Runde, flauschige Kugel auf einem Stängelkörper.',
    mainName: 'Lindgelb',
    accName: 'Blütenrosa',
    materials: [['Stängel', '#7ab040']],
    signature: 'Ein Kopf aus Samenschirmchen, die beim Heilen fortfliegen.',
    details: {
      kleidung: 'Blattschleife',
      material: 'Pflanzenflaum',
      muster: 'Schirmchen',
      schnallen: 'keine',
      abnutzung: 'ein paar Samen fehlen',
      accessoires: 'Blattschleife (Teamzone)',
    },
    face: 'Kleine geschlossene Lachaugen, rosige Wangen.',
    weapon: 'Er selbst (Samenwolke).',
    anim: {
      idle: ['Samen lösen sich und schweben'],
      walk: ['schwebt'],
      attack: ['Sprung, Samenwolke heilt'],
      hit: ['Samen wirbeln'],
      spawn: ['erblüht'],
      death: ['zerstäubt in Samen'],
    },
  },
  snowman: {
    concept: 'Der Schneemann ist ein frostig-freundlicher Gehilfe des Eismagier-Helden mit einer Krone aus Eiszapfen und einer Rübennase mit Raureif. Er erscheint mit einem Frostschlag und friert alles in seiner Nähe ein, solange er steht.',
    unique: 'Die Frostkrone aus Eiszapfen auf einem Schneemann ist einmalig. Schneemänner anderer Spiele tragen Zylinder; dieser trägt eine Eiskrone.',
    silhouette: 'Zwei Schneekugeln mit Krone oben und Ästen als Arme.',
    mainName: 'Schneeweiß',
    accName: 'Eishimmel',
    materials: [['Rübe', '#ff8a3a'], ['Äste', '#6b4a32'], ['Kohle', '#2a2830']],
    signature: 'Eine Krone aus Eiszapfen auf dem Kopf.',
    details: {
      kleidung: 'Strickschal, Eiskrone',
      material: 'Schnee, Eis, Holz, Kohle',
      muster: 'Schneeflocken',
      schnallen: 'Kohleknöpfe',
      abnutzung: 'schmelzende Kanten',
      accessoires: 'Strickschal (Teamzone)',
    },
    face: 'Kohleaugen, Rübennase und ein Lächeln aus Kohlestückchen.',
    weapon: 'Keine Hiebwaffe; seine Frostaura ist ein Ring aus Schneeflocken, der in Wellen von ihm ausgeht.',
    anim: {
      idle: ['Schneeflocken rieseln um ihn'],
      walk: ['keine Fortbewegung (steht)'],
      attack: ['Frostaura pulsiert'],
      hit: ['Schnee bröckelt'],
      spawn: ['rollt sich auf mit Frostschlag'],
      death: ['schmilzt zu einer Pfütze mit Krone'],
    },
  },
};
