// Design-Briefs: Gesindel (Banditen, Fischer, Jäger, Gräber, Kinder …)
export default {
  bandit: {
    concept: 'Die Banditin ist eine verschlagene Fuchs-Diebin mit einer Kapuze mit Fuchsohren und einem buschigen Fuchsschwanz als Schal. Sie sprintet unverwundbar auf Gegner zu und schlägt mit einem lederumwickelten Knüppel zu.',
    unique: 'Fuchsohr-Kapuze plus Fuchsschwanz-Schal geben eine Tier-Silhouette, die keine andere Menschenfigur hat; die geduckte Laufhaltung ist ihr Kennzeichen. Banditinnen anderer Spiele tragen Augenmasken und Dolche; diese ist ein Fuchs mit Knüppel.',
    silhouette: 'Geduckt nach vorn, Kapuze mit zwei spitzen Ohren, ein großer buschiger Schwanzschal hinten.',
    mainName: 'Fuchsrot (Kapuze, Jacke)',
    accName: 'Anthrazit (Hose, Maske)',
    materials: [['Schwanzspitze', '#f6efe2'], ['Haut', '#f0c4a0'], ['Knüppel', '#7a4a2a']],
    signature: 'Eine Kapuze mit Fuchsohren und ein Fuchsschwanz-Schal mit weißer Spitze.',
    details: {
      kleidung: 'Fuchsohr-Kapuze, kurze Jacke, Wickelhose, weiche Stiefel',
      material: 'Wolle, Fell, Leder',
      muster: 'Fellstriche, Flicken',
      schnallen: 'Gürtel mit Dietrich-Bund',
      abnutzung: 'zerrissener Ärmel',
      accessoires: 'Schalknoten und Gürtel (Teamzonen), Dietriche',
    },
    face: 'Schmale, listige Augen hinter einer Augenmaske, spitzes Grinsen mit einem Eckzahn.',
    weapon: 'Lederumwickelter Knüppel mit Eisenkappe.',
    anim: {
      idle: ['wirft den Knüppel hoch und fängt ihn'],
      walk: ['schleichender, geduckter Lauf'],
      attack: ['Uppercut mit dem Knüppel'],
      hit: ['Ohren klappen an'],
      spawn: ['landet in der Hocke'],
      death: ['löst sich in Rauch auf, der Schal bleibt kurz liegen'],
    },
    special: { extra: '**Sprint (`DASH`):** als Schemen mit drei Nachbildern, der Schwanzschal flach.' },
  },
  'boss-bandit': {
    concept: 'Boss Bandit ist die selbstsichere Anführerin der Fuchsbande in einem altrosa Samtmantel mit riesigem Silberfuchs-Kragen. Über der Schulter trägt sie einen Beutesack, aus dem Münzen fallen. Sie kämpft mit zwei Brecheisen und flieht mit einer Rauchgranate.',
    unique: 'Beutesack mit fallenden Münzen und Silberfuchs-Kragen sind einmalig; sie ist die Keil-Silhouette mit Sack. Banditen-Bosse anderer Spiele tragen Masken und Klingen; diese trägt Samt und Brecheisen.',
    silhouette: 'Keil mit riesigem Pelzkragen, Sack über einer Schulter, zwei kurze Eisen in den Händen.',
    mainName: 'Altrosa (Samtmantel)',
    accName: 'Beutegold',
    materials: [['Silberfuchs', '#e8e8ec'], ['Sack', '#b89a6a'], ['Brecheisen', '#5a5f6b']],
    signature: 'Ein Beutesack über der Schulter, aus dem Goldmünzen fallen.',
    details: {
      kleidung: 'Samtmantel mit Pelzkragen, Weste, Reiterhose, hohe Stiefel, Federhut',
      material: 'Samt, Pelz, Leinen, Eisen',
      muster: 'Brokat an der Weste',
      schnallen: 'Goldschnallen',
      abnutzung: 'Löcher im Sack',
      accessoires: 'Mantelfutter und Halstuch (Teamzonen), Rauchgranaten am Gürtel',
    },
    face: 'Selbstsicheres Lächeln, eine hochgezogene Braue, Schönheitsfleck.',
    weapon: 'Zwei kurze Brecheisen mit gespaltenen Enden und Lederwicklung, dazu Rauchgranaten am Gürtel.',
    anim: {
      idle: ['wirft eine Münze hoch'],
      walk: ['stolzierender Gang, der Sack klimpert'],
      attack: ['Doppelschlag mit beiden Brecheisen'],
      hit: ['Münzen fallen aus dem Sack'],
      spawn: ['landet und schultert den Sack'],
      death: ['Sack platzt, Münzen regnen'],
    },
    special: {
      ability: 'Fluchtgranate: Sie wirft eine Rauchgranate vor die Füße (Pose). Event `char.ability.boss-bandit` erzeugt eine Rauchwolke, aus der sie zurückspringt.',
      aura: 'Goldene Bodenaura mit fallenden Münzen; der Sprint zieht Nachbilder.',
    },
  },
  fisherman: {
    concept: 'Der Fischer ist ein knurrig-gemütlicher Seebär in gelbem Ölzeug mit Südwester und Pfeife. Mit seiner Angelrute wirft er einen Riesen-Blinker aus, zieht Gegner zu sich oder sich selbst zu Gebäuden. Er ist wetterfest wie ein Leuchtturm.',
    unique: 'Die Angelrute mit Riesen-Blinker (Köder in Fischform) ist einmalig. Fischer anderer Spiele schwingen Fische und Anker; dieser angelt mit Rute und Blinker.',
    silhouette: 'Breit in weitem Ölzeug, Südwester mit Krempe, lange Rute diagonal nach oben.',
    mainName: 'Ölzeug-Gelb',
    accName: 'Seegrün (Pullover, Stiefel)',
    materials: [['Bart', '#e8e2d6'], ['Blinker', '#c8ccd2'], ['Pfeife', '#6b4a2a']],
    signature: 'Eine Angelrute mit Kurbel und einem Blinker, der wie ein glänzender Fisch aussieht.',
    details: {
      kleidung: 'Südwester, Ölzeugjacke, Strickpullover, Gummistiefel',
      material: 'Ölzeug, Wolle, Gummi, Bambus',
      muster: 'Zopfmuster am Pullover',
      schnallen: 'Jackenknebel',
      abnutzung: 'Salzflecken',
      accessoires: 'Halstuch und Hutband (Teamzonen), Pfeife',
    },
    face: 'Rauschebart, buschige Brauen, Pfeife im Mundwinkel, zusammengekniffene Augen.',
    weapon: 'Angelrute mit Riesen-Blinker.',
    anim: {
      idle: ['zieht an der Pfeife, prüft die Schnur'],
      walk: ['schwerer, wiegender Seemannsgang'],
      attack: ['Rutenstoß; Auswurf über Kopf (Anticipation), Schnur spannt, Einholen'],
      hit: ['Südwester rutscht'],
      spawn: ['landet breitbeinig'],
      death: ['setzt sich, die Pfeife fällt'],
    },
  },
  hunter: {
    concept: 'Der Jäger ist ein brummiger Trapper in dunklem Leder mit einer Biberfellmütze samt Schwanz. Er schießt mit einer Donnerbüchse mit Trichtermündung zehn Kugeln breit gestreut.',
    unique: 'Die Trichtermündung der Donnerbüchse und die Biberfellmütze mit Schwanz sind einmalig. Jäger anderer Spiele haben Schrotflinten und Bärte; dieser trägt eine Donnerbüchse und Biberfell.',
    silhouette: 'Breit, Mütze mit Schwanz hinten, Büchse mit breitem Trichter vorn.',
    mainName: 'Dunkles Leder',
    accName: 'Rost (Mütze, Gurt)',
    materials: [['Biberfell', '#6b4a32'], ['Büchse (Messing)', '#c8a046']],
    signature: 'Eine Donnerbüchse mit trichterförmiger Messingmündung.',
    details: {
      kleidung: 'Biberfellmütze, Ledermantel mit Fransen, Mokassins',
      material: 'Leder, Fell, Messing',
      muster: 'Fransen, Perlenstickerei',
      schnallen: 'Patronengurt',
      abnutzung: 'Ruß an der Mündung',
      accessoires: 'Patronengurt-Schärpe und Mützenschwanz-Band (Teamzonen), Pulverhorn',
    },
    face: 'Brummiges Gesicht, ein Auge zugekniffen, Stoppelbart.',
    weapon: 'Donnerbüchse mit Trichtermündung.',
    anim: {
      idle: ['stopft Pulver nach'],
      walk: ['schwerer Pirschgang'],
      attack: ['Anlegen (Anticipation), Bumm mit starkem Rückstoß'],
      hit: ['Mützenschwanz wackelt'],
      spawn: ['landet in der Hocke'],
      death: ['fällt nach hinten, die Mütze rollt'],
    },
    special: { evo: 'Netz-Evo: Eine Netzrolle auf dem Rücken, ein Fangnetz-Werfer am Gürtel und Messingbeschläge an der Büchse. Netzfäden bilden die Partikelhülle; der Netzwurf hat eine eigene Pose.' },
  },
  miner: {
    concept: 'Der Tunnelgräber ist ein kurzsichtiger, fleißiger Maulwurfmann mit riesigen Schaufelkrallen und runder, dunkler Brille. Er gräbt sich überall in der Arena hin und taucht als Erdhügel auf.',
    unique: 'Ein Maulwurfmann mit Schaufelkrallen ist einmalig; der Große Gräber ist ein Zwerg mit Bohrer. Gräber anderer Spiele sind Menschen mit Spitzhacke und Helmlampe; dieser ist ein Maulwurf mit Brille.',
    silhouette: 'Geduckt, spitze Nase, zwei große Krallenhände.',
    mainName: 'Maulwurfgrau',
    accName: 'Brillengelb',
    materials: [['Nase', '#e8a0a0'], ['Weste', '#6b5040']],
    signature: 'Riesige, schaufelförmige Krallenhände.',
    details: {
      kleidung: 'Weste mit Werkzeug, Brille',
      material: 'Fell, Leder, Glas',
      muster: 'Fellstriche',
      schnallen: 'Westenknöpfe',
      abnutzung: 'Erde im Fell',
      accessoires: 'Halstuch (Teamzone)',
    },
    face: 'Rüsselnase, kleine Augen hinter der Brille, Schnurrhaare.',
    weapon: 'Seine Schaufelkrallen: fünf breite Krallen pro Hand, mit denen er gräbt und zuschlägt.',
    anim: {
      idle: ['schnuppert mit der Rüsselnase'],
      walk: ['tapsiger Gang'],
      attack: ['Krallenhieb'],
      hit: ['Brille rutscht'],
      spawn: ['bricht aus dem Boden'],
      death: ['gräbt sich ein'],
    },
  },
  'mighty-miner': {
    concept: 'Der Große Gräber ist ein polternder, zufriedener Zwergen-Bohrmeister mit einem Bohrer statt rechtem Arm und einem Bauhelm mit greller Stirnlampe. Sein Schaden steigt, je länger er bohrt. Er kann sich auf die andere Seite durchgraben und eine Bombe zurücklassen.',
    unique: 'Der Bohrer-Arm ist einmalig. Der Tunnelgräber ist ein Maulwurf. Gräber-Champions anderer Spiele tragen Spitzhacken; dieser hat einen Bohrarm.',
    silhouette: 'Breit und stämmig, großer Bohrer rechts, Helm mit Lampe.',
    mainName: 'Ocker (Overall)',
    accName: 'Stahl (Bohrer)',
    materials: [['Bart', '#6b4f36'], ['Helm', '#f0c020'], ['Lampe', '#fff6c8']],
    signature: 'Ein Bohrer statt des rechten Arms, der sich mit steigender Drehzahl dreht.',
    details: {
      kleidung: 'Bauhelm, Overall, Lederschürze, Stiefel',
      material: 'Stahl, Leder, Leinen',
      muster: 'Spiralrillen am Bohrer',
      schnallen: 'Gurtschnallen',
      abnutzung: 'Staub, Ölflecken',
      accessoires: 'Helmband und Gürtel (Teamzonen), Sprengstoffkiste',
    },
    face: 'Breiter Bart, Knollennase, zufriedenes Grinsen.',
    weapon: 'Bohrarm mit Spiralbohrer, Kolbengehäuse und Drehzahlanzeige, die mit steigendem Schaden ausschlägt.',
    anim: {
      idle: ['lässt den Bohrer kurz aufheulen'],
      walk: ['polternder Gang'],
      attack: ['Bohrer setzt an und bohrt mit steigender Drehzahl'],
      hit: ['Helm wackelt'],
      spawn: ['landet mit Staub'],
      death: ['Bohrer stoppt, er kippt um'],
    },
    special: {
      ability: 'Explosive Flucht: Er bohrt sich ein (Pose: Bohrer nach unten). Event `char.ability.mighty-miner` erzeugt eine Erdfontäne, eine Bombe bleibt zurück.',
      aura: 'Ockerfarbene Bodenaura mit Gesteinssplittern.',
    },
  },
  ronin: {
    concept: 'Der Ronin ist ein ruhiger, wachsamer Wanderschwertkämpfer mit einem tiefen Strohhut, an dem ein Papiersiegel hängt. Er pariert alle paar Sekunden einen Nahkampfangriff und schlägt mit doppeltem Schaden zurück.',
    unique: 'Der tiefe Strohhut mit Papiersiegel und die olivgraue Reisekleidung sind einmalig. Wanderschwertkämpfer anderer Spiele tragen Dunkelblau; dieser trägt Oliv und Stroh.',
    silhouette: 'Schlank, Hutkrempe breiter als die Schultern, Schwert an der Hüfte.',
    mainName: 'Olivgrau (Gewand)',
    accName: 'Stroh',
    materials: [['Siegel', '#f4ead2'], ['Klinge', '#d8dee6']],
    signature: 'Ein tiefer Strohhut mit herabhängendem Papiersiegel.',
    details: {
      kleidung: 'Strohhut, Reisegewand, Hosenrock, Strohsandalen',
      material: 'Stroh, Leinen, Stahl',
      muster: 'Flechtmuster am Hut',
      schnallen: 'Gürtelknoten',
      abnutzung: 'Staub an den Säumen',
      accessoires: 'Hüftschärpe und Siegelband (Teamzonen), Bambusflasche',
    },
    face: 'Halb vom Hut verdeckt, ein ruhiges Auge, schmaler Mund.',
    weapon: 'Langschwert mit Lederwicklung.',
    anim: {
      idle: ['steht still, die Hand am Griff'],
      walk: ['ruhiger Schritt'],
      attack: ['Ziehen und Schlag in einer Bewegung'],
      hit: ['Parade mit Funken'],
      spawn: ['landet in Kampfhaltung'],
      death: ['sinkt auf ein Knie, der Hut fällt'],
    },
  },
  firecracker: {
    concept: 'Die Feuerwerkerin ist eine aufgekratzte Pyrotechnikerin mit einem Papierschirm, dessen Speichen Raketen sind, und Wunderkerzen im Haarknoten. Sie schießt Raketen, die am Ziel in Funken zerplatzen, und hüpft nach jedem Schuss zurück.',
    unique: 'Der Raketenschirm ist eine einmalige Waffe. Feuerwerkerinnen anderer Spiele tragen Raketenwerfer auf dem Rücken; diese schießt mit einem Schirm.',
    silhouette: 'Schlank, über ihr ein runder Schirm, aus dessen Rand Raketen ragen.',
    mainName: 'Cyan (Kleid)',
    accName: 'Pink (Schirm, Funken)',
    materials: [['Schirmpapier', '#fff2d8'], ['Haar', '#2a1e2e']],
    signature: 'Ein Papierschirm, dessen Speichen Raketen sind.',
    details: {
      kleidung: 'Kurzkleid, Leggings, Stiefel',
      material: 'Seide, Papier, Bambus',
      muster: 'Funkenmuster',
      schnallen: 'Gürtelschleife',
      abnutzung: 'angesengte Schirmränder',
      accessoires: 'Schirmrand und Gürtelschleife (Teamzonen), Wunderkerzen',
    },
    face: 'Lachender Mund, Funken in den Augen, Haarknoten.',
    weapon: 'Papierschirm mit acht Raketen als Speichen; die vorderste Rakete zündet bei jedem Schuss.',
    anim: {
      idle: ['dreht den Schirm, Funken sprühen'],
      walk: ['hüpfender Gang'],
      attack: ['Schirm nach vorn (Anticipation), Rakete zischt, Rückstoß-Hüpfer nach hinten'],
      hit: ['Schirm klappt zu'],
      spawn: ['schwebt am Schirm herab'],
      death: ['Schirm fliegt davon'],
    },
    special: { evo: 'Glut-Evo: Ein Doppelschirm mit Glutrand und glühende Haarstäbe. Glut bildet die Partikelhülle; die Funken hinterlassen Glut am Boden.' },
  },
  'battle-healer': {
    concept: 'Die Kampfheilerin ist eine resolute, fürsorgliche Kräuterfrau mit einem Mörser-Rucksack voller Kräuter und einem Riesenstößel als Keule. Jeder Schlag lässt eine heilende Kräuterwolke aufsteigen, und beim Erscheinen heilt sie Verbündete.',
    unique: 'Mörser-Rucksack plus Stößel sind einmalig. Heilerinnen anderer Spiele tragen Rüstung und Kolben; diese ist eine Kräuterfrau mit Mörser.',
    silhouette: 'Breit, Kopftuch, runder Mörser hinten, langer Stößel.',
    mainName: 'Salbeigrün',
    accName: 'Leinen',
    materials: [['Mörser (Stein)', '#9a948a'], ['Kräuter', '#5a9a3a'], ['Stößel (Holz)', '#a8763e']],
    signature: 'Ein steinerner Mörser auf dem Rücken, aus dem Kräuter ragen.',
    details: {
      kleidung: 'Kopftuch, Kleid mit Schürze, Stiefel',
      material: 'Leinen, Stein, Holz',
      muster: 'Kräuter-Stickerei',
      schnallen: 'Gurte',
      abnutzung: 'Kräuterflecken',
      accessoires: 'Kopftuch und Schürzenband (Teamzonen)',
    },
    face: 'Runde Wangen, energischer Blick, ein Lächeln.',
    weapon: 'Riesiger Holzstößel mit Steinkopf, dazu der Mörser auf dem Rücken, aus dem Kräuter stieben.',
    anim: {
      idle: ['zerstößt Kräuter in der Luft und schnuppert'],
      walk: ['zielstrebiger Schritt'],
      attack: ['Stößel von oben wie beim Zerstoßen, Kräuterwolke'],
      hit: ['Kräuter fallen'],
      spawn: ['landet, eine Heilwolke breitet sich aus'],
      death: ['sinkt zusammen, Kräuter wirbeln'],
    },
  },
  bomber: {
    concept: 'Der Bomber ist ein kichernder, rußiger Schornsteinfeger-Wicht mit einem Zylinder, aus dem er Bomben zieht. Einen Besen trägt er auf dem Rücken. Er wirft Bomben im hohen Bogen.',
    unique: 'Ein Zylinder voller Bomben ist einmalig; die runde Silhouette mit Zylinder ebenso. Bomber anderer Spiele sind Skelette; dieser ist ein Schornsteinfeger.',
    silhouette: 'Kugelrund mit hohem Zylinder, Besen hinten.',
    mainName: 'Ruß',
    accName: 'Schal-Weiß',
    materials: [['Bombe', '#2a2830'], ['Lunte', '#ff9a2e'], ['Besen', '#a8763e']],
    signature: 'Ein hoher Zylinder, aus dem Bomben ragen.',
    details: {
      kleidung: 'Zylinder, Jacke mit Goldknöpfen, Hose, Stiefel',
      material: 'Filz, Wolle, Messing',
      muster: 'Rußflecken',
      schnallen: 'Goldknöpfe',
      abnutzung: 'Ruß überall',
      accessoires: 'Halstuch und Hutband (Teamzonen), Besen',
    },
    face: 'Rußgesicht mit weißen Augen und breitem Kichern.',
    weapon: 'Runde Schwarzpulver-Bomben mit kurzer Lunte, die er aus dem Zylinder zieht.',
    anim: {
      idle: ['jongliert eine Bombe, Ruß bröselt'],
      walk: ['watschelnd'],
      attack: ['lüpft den Hut (Anticipation), zieht eine Bombe, Wurf im hohen Bogen'],
      hit: ['Rußwolke'],
      spawn: ['plumpst mit Rußwolke'],
      death: ['Hut fällt, Bomben rollen heraus'],
    },
    special: { evo: 'Springbomben-Evo: Sprungfedern an Schuhen und Hut, Bomben mit Federn. Federfunken bilden die Partikelhülle; die Bombe hüpft weiter.' },
  },
  balloon: {
    concept: 'Der Ballon ist ein Zwiebelkuppel-Heißluftballon aus Pflaumen-Flicken mit Messingpropeller. Im Korb sitzt ein schadenfroh kichernder Gnom mit Riesen-Hörrohr. Er fliegt zu Gebäuden und wirft schwere Bomben.',
    unique: 'Zwiebelkuppel-Form mit Propeller und Gnom-Pilot mit Hörrohr sind einmalig. Ballone anderer Spiele tragen Schädelgesichter; dieser ist eine Flickenkuppel.',
    silhouette: 'Große Zwiebelform oben, kleiner Korb unten, Propeller hinten.',
    mainName: 'Pflaume (Hülle)',
    accName: 'Messing',
    materials: [['Korb', '#a8763e'], ['Gnom-Haut', '#e8b894'], ['Bombe', '#2a2830']],
    signature: 'Eine Zwiebelkuppel-Hülle aus Flicken mit Messingpropeller.',
    details: {
      kleidung: 'Gnom mit Fliegermütze',
      material: 'Stoff, Messing, Weide',
      muster: 'Flickennähte',
      schnallen: 'Seile, Ösen',
      abnutzung: 'Flicken',
      accessoires: 'Wimpelkette und Korbrand (Teamzonen), Hörrohr',
    },
    face: 'Gnom mit langer Nase, Hörrohr am Ohr, kicherndem Mund.',
    weapon: 'Schwere Eisenbomben mit Flossen, die der Gnom über den Korbrand wuchtet.',
    anim: {
      idle: ['Ballon schaukelt, Propeller dreht, Pilot lauscht'],
      walk: ['gleitet'],
      attack: ['Gnom wuchtet eine Bombe über den Korbrand (Anticipation), Ballon hüpft nach oben'],
      hit: ['Hülle bebt'],
      spawn: ['schwebt herab'],
      death: ['Hülle zischt, er trudelt, die Bombe fällt (Todesschaden)'],
    },
  },
  'rascal-boy': {
    concept: 'Der Rabauke ist ein großspuriger Junge in einer Rüstung aus Pappkartons und Klebeband mit einem Kochtopfdeckel als Schild. Er kämpft vorn mit einem Holzschwert, zäh und laut.',
    unique: 'Papprüstung mit Klebeband ist einmalig. Rabauken anderer Spiele tragen Kappen; dieser trägt Karton.',
    silhouette: 'Breit durch die Kartonrüstung, Topfdeckel vorn, Holzschwert hoch.',
    mainName: 'Pappe',
    accName: 'Kappengrün',
    materials: [['Klebeband', '#c8ccd2'], ['Deckel', '#9aa3ad'], ['Haut', '#f0c090']],
    signature: 'Eine Rüstung aus Pappkartons mit Klebeband-Streifen.',
    details: {
      kleidung: 'Kartonrüstung, Kappe, kurze Hose, Turnschuhe',
      material: 'Pappe, Klebeband, Holz',
      muster: 'Aufschriften auf dem Karton',
      schnallen: 'Klebeband',
      abnutzung: 'eingedrückte Ecken',
      accessoires: 'Kappe und Klebeband-Streifen (Teamzonen)',
    },
    face: 'Zahnlücke, großspuriges Grinsen.',
    weapon: 'Holzschwert und Topfdeckel.',
    anim: {
      idle: ['wedelt mit dem Holzschwert'],
      walk: ['großspuriger Gang'],
      attack: ['Holzschwert-Kloppe von oben'],
      hit: ['Karton beult ein'],
      spawn: ['landet mit Pose'],
      death: ['Karton fällt auseinander'],
    },
  },
  'rascal-girl': {
    concept: 'Die Rabaukin ist ein freches Mädchen mit Sommersprossen, Zöpfen und Latzhose, das mit einer Astgabel-Schleuder Steinchen schießt. Sie steht hinter dem Rabauken.',
    unique: 'Die Astgabel-Schleuder ist einmalig; Zöpfe, die beim Schießen hochfliegen, sind ihr Merkmal. Schleuder-Kinder anderer Spiele tragen Rosa; diese trägt eine Erdbeer-Latzhose.',
    silhouette: 'Winzig mit zwei abstehenden Zöpfen, Schleuder vorn.',
    mainName: 'Erdbeerrosa (Latzhose)',
    accName: 'Tinte (Shirt)',
    materials: [['Haar', '#e8743b'], ['Schleuder (Holz)', '#8a5a32']],
    signature: 'Eine Astgabel-Schleuder mit Gummiband.',
    details: {
      kleidung: 'Latzhose, Ringelshirt, Turnschuhe',
      material: 'Jeans, Baumwolle, Holz',
      muster: 'Ringel, Flicken',
      schnallen: 'Latzhosenknöpfe',
      abnutzung: 'Grasflecken',
      accessoires: 'Haarschleifen und Latzhosen-Träger (Teamzonen)',
    },
    face: 'Sommersprossen, freches Grinsen, ein zugekniffenes Auge beim Zielen.',
    weapon: 'Astgabel-Schleuder mit Lederbeutel und Gummiband, dazu eine Tasche voller Kiesel.',
    anim: {
      idle: ['sucht Steinchen am Boden'],
      walk: ['hüpfender Gang'],
      attack: ['Schleuder spannen (Anticipation), Schuss'],
      hit: ['Zöpfe fliegen'],
      spawn: ['landet mit Hüpfer'],
      death: ['setzt sich hin und schmollt'],
    },
    special: { variants: 'Zöpfe, Pferdeschwanz; Farbton ±6°, Größe ±5 %' },
  },
  'suspicious-bush': {
    concept: 'Der Suspicious Bush ist ein verdächtig unschuldiger Busch mit zwei Augenpaaren und großen Schuhen, der zum nächsten Gebäude schleicht. Am Ziel springen zwei Busch-Kobolde heraus.',
    unique: 'Ein Busch mit zwei Augenpaaren und Schuhen ist einmalig. Tarnbüsche anderer Spiele sind einfache Büsche; dieser hat Schuhe.',
    silhouette: 'Rundlicher Busch, unten zwei große Schuhe.',
    mainName: 'Buschgrün',
    accName: 'Augengelb',
    materials: [['Schuhe', '#6b4a32']],
    signature: 'Zwei Augenpaare im Busch und große Schuhe darunter.',
    details: {
      kleidung: 'Schuhe',
      material: 'Blätter, Leder',
      muster: 'Blattschuppen',
      schnallen: 'Schnürsenkel',
      abnutzung: 'welke Blätter',
      accessoires: 'Schnürsenkel (Teamzone)',
    },
    face: 'Zwei Augenpaare, die abwechselnd blinzeln.',
    weapon: 'Keine; die Kobolde springen heraus.',
    anim: {
      idle: ['Augen blinzeln abwechselnd'],
      walk: ['schleicht auf Zehenspitzen'],
      attack: ['Busch springt auf, Kobolde hüpfen heraus'],
      hit: ['Blätter fallen'],
      spawn: ['wächst aus dem Boden'],
      death: ['Busch fällt auseinander, Kobolde springen heraus'],
    },
  },
};
