// Design-Briefs: Gruft (Untote)
export default {
  skeletons: {
    concept: 'Die Skelette sind drei klapprig-fröhliche Winzlinge mit einem riesigen, rissigen Schädel und cyanblauen Geisteraugen. Sie stechen mit Knochendolchen zu. Ihr Schädel ist halb so groß wie der ganze Körper.',
    unique: 'Der übergroße, rissige Schädel mit cyanfarbenem Augenfeuer und das Halstuch machen sie unverwechselbar; andere Untote haben Sargdeckel, Kronen oder Fässer. Skelette anderer Spiele sind meist normal proportioniert; diese sind Wackelkopf-Winzlinge.',
    silhouette: 'Winzig: großer runder Schädel auf einem dünnen Knochenkörper, Dolch nach vorn.',
    mainName: 'Knochenweiß',
    accName: 'Geister-Cyan (Augen)',
    materials: [['Knochenschatten', '#c8bca0'], ['Dolch', '#d8cfb8']],
    signature: 'Ein großer Schädel mit Riss und zwei cyan leuchtenden Augenhöhlen.',
    details: {
      kleidung: 'nur Knochen und Halstuch',
      material: 'Knochen',
      muster: 'Risse, Rippenbögen',
      schnallen: 'keine',
      abnutzung: 'abgebrochener Zahn',
      accessoires: 'Halstuch (Teamzone)',
    },
    face: 'Leere Augenhöhlen mit cyan Flämmchen, die sich beim Ausdruck verformen, und ein klapperndes Grinsen.',
    weapon: 'Knochendolch aus einer Rippe.',
    anim: {
      idle: ['Kiefer klappert, Kopf wackelt'],
      walk: ['schnelles Klappern, Kopf wippt'],
      attack: ['Stich mit dem Knochendolch'],
      hit: ['Kopf dreht sich einmal herum'],
      spawn: ['klettern aus dem Boden'],
      death: ['fallen in einen Knochenhaufen'],
    },
    special: {
      evo: 'Klon-Evo: cyanfarbene Leuchtnähte an den Gelenken, Knochenkrönchen und Schulterknochen-Panzer. Cyan-Funken bilden die Partikelhülle; jeder Angriff spaltet eine Kopie ab.',
      variants: 'Riss links, Riss rechts, Zahn fehlt; Farbton ±6°, Größe ±5 %',
    },
  },
  guards: {
    concept: 'Die Wächter sind drei steife, pflichtbewusste Skelett-Wachen mit Schilden aus Sargdeckeln und Speeren. Erst muss der Deckel brechen, dann sie selbst. Sie salutieren gern.',
    unique: 'Sargdeckel mit Kreuz-Beschlag als Schild ist einmalig (der Ritter hat einen Zinnenschild, die Rekruten Rundschilde). Skelettwächter anderer Spiele tragen Rundschilde; diese verstecken sich hinter Sargdeckeln.',
    silhouette: 'Kleines Skelett hinter einem hohen, sechseckigen Sargdeckel; der Speer ragt darüber hinaus.',
    mainName: 'Verwittertes Grau (Sargholz)',
    accName: 'Knochenweiß',
    materials: [['Eisenbeschlag', '#5a5f6b'], ['Helm', '#7a828e']],
    signature: 'Ein sechseckiger Sargdeckel mit Eisenbeschlägen als Schild.',
    details: {
      kleidung: 'rostige Helme, Knochen',
      material: 'Holz, Eisen, Knochen',
      muster: 'Holzmaserung, Nagelreihen',
      schnallen: 'Sargdeckel-Beschläge',
      abnutzung: 'Rostflecken',
      accessoires: 'Sargdeckel-Emblem und Helmfeder (Teamzonen)',
    },
    face: 'Schädel mit grünlichen Augenpunkten unter dem Helmrand und strammem Kiefer.',
    weapon: 'Speer mit Knochenspitze.',
    anim: {
      idle: ['stehen stramm, ein Knochen wackelt'],
      walk: ['marschieren im Gleichschritt'],
      attack: ['Speerstoß hinter dem Deckel hervor'],
      hit: ['Deckel ächzt; bei Schildbruch zerbricht er in Bretter'],
      spawn: ['landen mit Deckel voran'],
      death: ['Knochen fallen hinter den Deckel'],
    },
    special: { variants: 'Helmfeder, Rostfleck, Kerbe im Schild; Farbton ±6°, Größe ±5 %', extra: '**Schildbruch:** Teile mit `data-state="shield"` entfallen, sobald der Schild-Wert 0 ist; zurück bleibt ein Holzsplitter am Arm.' },
  },
  'giant-skeleton': {
    concept: 'Das Riesenskelett ist ein dröhnend lachender Knochenriese mit einer tickenden Uhrwerk-Bombe im Brustkorb. Er schlägt mit riesigen Fingerknochen-Fäusten. Fällt er, rollt die Bombe heraus und explodiert nach drei Sekunden.',
    unique: 'Die Uhrwerk-Bombe mit Zahnrädern zwischen den Rippen ist einmalig; die vergilbten Knochen und das Halstuch unterscheiden ihn von allen anderen Skeletten. Riesenskelette anderer Spiele tragen die Bombe in der Hand; dieses trägt sie im Brustkorb.',
    silhouette: 'Massig, großer Schädel, breiter Brustkorb mit runder Bombe innen, riesige Knochenhände.',
    mainName: 'Vergilbter Knochen',
    accName: 'Eisendunkel (Bombe)',
    materials: [['Zahnräder (Messing)', '#c8a046'], ['Lunte', '#ff7a2a']],
    signature: 'Eine runde Eisenbombe mit Uhrwerk-Zifferblatt hängt im Brustkorb und tickt sichtbar.',
    details: {
      kleidung: 'zerrissene Hose, Halstuch',
      material: 'Knochen, Eisen, Messing',
      muster: 'Risse, Zahnräder',
      schnallen: 'Gurte um die Bombe',
      abnutzung: 'Moos an den Knochen',
      accessoires: 'Halstuch und Armband (Teamzonen)',
    },
    face: 'Großer Schädel mit dröhnend offenem Kiefer, glühenden Augenhöhlen und einem schiefen Zahn.',
    weapon: 'Riesige Knochenfäuste.',
    anim: {
      idle: ['Kiefer klappert, die Bombe tickt'],
      walk: ['schwerer Gang mit `char.step`, Knochen klappern'],
      attack: ['Faust weit nach hinten (Anticipation), Rundumschlag'],
      hit: ['Rippen klappern, das Zifferblatt springt'],
      spawn: ['landet, die Bombe tickt los'],
      death: ['zerfällt, die Bombe rollt heraus (Todesschaden)'],
    },
  },
  'skeleton-king': {
    concept: 'Der Skelettkönig ist ein majestätischer, hohl lachender König der Toten mit einer Geweihkrone und einer Robe aus nachtgrauem Gruftsamt. Er schlägt mit einer Keule aus einem Grabstein. Er sammelt die Seelen gefallener Truppen und ruft daraus Skelette.',
    unique: 'Die Geweihkrone aus Hirschstangen und die Grabstein-Keule sind einmalig. Die Grabkönigin trägt einen Sarkophag, General Gerry einen Zweispitz. Skelettkönige anderer Spiele tragen Goldkronen und Purpur; dieser trägt Geweih und Nachtgrau.',
    silhouette: 'Massig in weiter Robe mit Schulterumhang, oben ein ausladendes Geweih, die Keule ist ein Grabstein an einem Knochengriff.',
    mainName: 'Nachtgrau (Robe)',
    accName: 'Knochenweiß',
    materials: [['Geweih', '#e8dcc0'], ['Grabstein', '#8a8a96'], ['Seelenlicht', '#9ff0ff']],
    signature: 'Eine Krone aus zwei Hirschgeweih-Stangen mit Eisenreif.',
    details: {
      kleidung: 'Gruftsamt-Robe mit Fellkragen, Schulterumhang, Knochenpanzer',
      material: 'Samt, Knochen, Stein, Eisen',
      muster: 'Grabinschrift auf der Keule',
      schnallen: 'Eisenreif, Knochenspangen',
      abnutzung: 'Moos am Grabstein',
      accessoires: 'Robensaum und Schulterumhang (Teamzonen), Seelenlichter',
    },
    face: 'Großer Schädel mit Kinnbart aus Spinnweben, glühenden Augen und hohl lachendem Kiefer.',
    weapon: 'Keule aus einem gerundeten Grabstein mit Inschrift und Moos, an einen langen Schenkelknochen gebunden.',
    anim: {
      idle: ['stützt sich auf die Keule, Seelenlichter kreisen'],
      walk: ['schwerer Schritt, die Robe schleift'],
      attack: ['Keule über den Kopf (Anticipation), Flächenschlag'],
      hit: ['Geweih wackelt'],
      spawn: ['steigt aus dem Boden'],
      death: ['zerfällt, die Krone fällt'],
    },
    special: {
      ability: 'Seelenruf: Er hebt die Keule und das Geweih leuchtet (Pose). Event `char.ability.skeleton-king` erzeugt einen Seelenwirbel, aus dem Skelette steigen.',
      aura: 'Knochenweiße Bodenaura mit kreisenden Seelenlichtern, deren Zahl mit den gesammelten Seelen wächst.',
    },
  },
  'tomb-queen': {
    concept: 'Die Grabkönigin ist eine eisige Herrscherin, deren Körper ein aufrecht stehender, bemalter Sarkophag ist. Aus ihm ragen Knochenarme mit einem Zepter. Sie marschiert zu Gebäuden, und der Sarkophagdeckel klappt beim Schlag auf.',
    unique: 'Ein aufrechter Sarkophag als Kleid mit bemalter Maske ist eine einmalige Form; andere Untote sind offene Skelette. Grabköniginnen anderer Spiele sind Mumien mit Binden; diese ist ein lebender Sarg.',
    silhouette: 'Massig wie ein senkrechter Sarg: oben ein Kopfende mit Gesichtsmaske, darunter eine Kastenform, seitlich Knochenarme.',
    mainName: 'Petrol (Sarkophag)',
    accName: 'Gold (Bemalung, Zepter)',
    materials: [['Knochenarme', '#e8dcc0'], ['Schleier', '#d8e8e8']],
    signature: 'Der aufrechte Sarkophag mit bemaltem Gesicht, Goldbändern und einem Deckel, der sich öffnet.',
    details: {
      kleidung: 'Sarkophag-Körper, Schleier, Knochenarme',
      material: 'bemaltes Holz, Gold, Knochen',
      muster: 'Schlangen- und Sternmotive',
      schnallen: 'Goldbänder',
      abnutzung: 'abgeplatzte Farbe',
      accessoires: 'Sarkophag-Band und Schleier (Teamzonen)',
    },
    face: 'Die bemalte Maske mit langen Augen; im Spalt des Deckels leuchten echte Augen.',
    weapon: 'Zepter mit Schlangenkopf.',
    anim: {
      idle: ['Deckel öffnet sich einen Spalt, Augen leuchten'],
      walk: ['ruckelnder Schritt auf Knochenfüßen'],
      attack: ['Zepter hoch (Anticipation), Schlag, der Deckel klappt auf'],
      hit: ['Farbe splittert'],
      spawn: ['steigt aus der Erde (Fähigkeit des Grabstein-Helden)'],
      death: ['Sarkophag kippt um, der Deckel fällt ab'],
    },
  },
  'skeleton-dragons': {
    concept: 'Die Skelettdrachen sind zwei gierige Knochendrachen mit zerfetzten Flügelhäuten und grünem Geisterfeuer im Brustkorb. Sie spucken grüne Feuerbälle mit Flächenschaden.',
    unique: 'Das grüne Feuer, das durch die Rippen leuchtet, ist einmalig; andere Drachen haben Schuppen und Haut. Knochendrachen anderer Spiele speien weißes Feuer; diese leuchten grün von innen.',
    silhouette: 'Knochiger Drache mit offenen Rippen, zerfetzten Flügeln und langem Knochenschwanz.',
    mainName: 'Knochenbeige',
    accName: 'Geistergrün',
    materials: [['Flügelhaut', '#8a8478']],
    signature: 'Grünes Geisterfeuer brennt im offenen Brustkorb.',
    details: {
      kleidung: 'Knochen, Flügelhautfetzen',
      material: 'Knochen, Haut',
      muster: 'Wirbelreihen',
      schnallen: 'keine',
      abnutzung: 'Risse in den Flügeln',
      accessoires: 'Halsband (Teamzone)',
    },
    face: 'Langer Schädel mit Hörnern, grün glühenden Augen und schnappendem Kiefer.',
    weapon: 'Grüner Geisterfeuer-Ball aus dem Knochenkiefer, der beim Aufprall in grüne Flammenzungen zerspritzt.',
    anim: {
      idle: ['Flügelschlag mit `char.flap`, Feuer züngelt durch die Rippen'],
      walk: ['Flug mit Wellen im Schwanz'],
      attack: ['Kopf zurück (Anticipation), grüner Feuerball'],
      hit: ['Knochen klappern'],
      spawn: ['fliegen aus grünem Rauch'],
      death: ['zerfallen in der Luft, Knochen regnen'],
    },
    special: { variants: 'Hornspitze, Kerbe im Kiefer; Farbton ±6°, Größe ±5 %' },
  },
  'skeleton-barrel': {
    concept: 'Das Skelettfass ist ein kicherndes Holzfass mit einer Propellerkappe obendrauf, das ratternd zu Gebäuden fliegt. Aus den Spundlöchern gucken Knochen. Platzt es, regnen Skelette.',
    unique: 'Ein Fass, das mit einer Propellerkappe fliegt, ist einmalig; der Ballon fliegt mit Hülle, die Flugmaschine mit Flügeln. Fliegende Fässer anderer Spiele hängen an Ballonen; dieses hat eine Kappe mit Propeller.',
    silhouette: 'Rundes Fass mit Propeller oben, kleine Fahne, Knochen gucken heraus.',
    mainName: 'Fassbraun',
    accName: 'Knochenweiß',
    materials: [['Fassreifen', '#5a5f6b'], ['Propeller', '#c8a046']],
    signature: 'Eine Propellerkappe mit drei Blättern sitzt auf dem Fassdeckel.',
    details: {
      kleidung: 'Fass mit Reifen und Kappe',
      material: 'Holz, Eisen, Messing',
      muster: 'Dauben, Reifen',
      schnallen: 'Kappenriemen',
      abnutzung: 'Löcher im Fass',
      accessoires: 'Fähnchen und Fassband (Teamzonen)',
    },
    face: 'Zwei Schädelaugen gucken durch die Spundlöcher und kichern.',
    weapon: 'Keine; es platzt über dem Ziel.',
    anim: {
      idle: ['Propeller dreht, Fass schaukelt'],
      walk: ['ratternder Flug'],
      attack: ['Sturz auf das Gebäude, Fass platzt'],
      hit: ['Dauben knarren'],
      spawn: ['propellert hoch'],
      death: ['Fass platzt, Skelette fallen heraus'],
    },
    special: { evo: 'Doppelfass-Evo: Ein zweites, kleineres Fass hängt darunter, dazu Eisenbeschläge, ein Doppelpropeller und grüne Leuchtspalten. Holzsplitter-Funken bilden die Partikelhülle; bei 75 % Leben fällt das untere Fass ab.' },
  },
  'wall-breakers': {
    concept: 'Die Mauerbrecher sind zwei begeisterte Skelette, die je ein Pulverfass mit glimmender Lunte über dem Kopf tragen. Sie rennen kichernd zu Gebäuden und sprengen sich daran.',
    unique: 'Das Pulverfass über dem Kopf ist größer als der Träger und gibt eine runde Oberform; andere Skelette tragen Dolche oder Schilde. Mauerbrecher anderer Spiele tragen Bomben; diese tragen Fässer mit Lunte.',
    silhouette: 'Geduckt rennend mit erhobenen Armen, darüber das runde Fass.',
    mainName: 'Fassholz-Braun',
    accName: 'Pulverschwarz (Reifen)',
    materials: [['Knochen', '#e8dfc8'], ['Lunte', '#ff7a2a']],
    signature: 'Ein Pulverfass mit glimmender Lunte, über dem Kopf getragen.',
    details: {
      kleidung: 'Stirnband, Knochen',
      material: 'Holz, Eisen, Knochen',
      muster: 'Dauben',
      schnallen: 'Fassreifen',
      abnutzung: 'Brandflecken',
      accessoires: 'Stirnband und Fassband (Teamzonen)',
    },
    face: 'Schädel mit begeistert aufgerissenem Kiefer und Funken in den Augen.',
    weapon: 'Das Pulverfass selbst: Eichendauben, zwei Eisenreifen und eine kurze, glimmende Lunte im Spundloch.',
    anim: {
      idle: ['balancieren das Fass'],
      walk: ['rennen kichernd, das Fass wippt'],
      attack: ['Sprung gegen das Gebäude, das Fass zündet'],
      hit: ['Fass wackelt gefährlich'],
      spawn: ['landen, das Fass hüpft'],
      death: ['Explosion'],
    },
    special: { evo: 'Läufer-Evo: Eisenbeschläge und eine Doppel-Lunte am Fass, Sprinter-Stirnbänder. Lunten-Funken bilden die Partikelhülle; zerbricht das Fass, rennen sie als Läufer weiter.' },
  },
  'wall-breaker-runner': {
    concept: 'Der Läufer ist ein Mauerbrecher, dessen Fass geplatzt ist. Er rennt gehetzt mit flatterndem Sprinter-Stirnband und rudernden Armen auf extrem langen Knochenbeinen weiter.',
    unique: 'Extrem lange Knochenbeine und das flatternde Stirnband geben eine Sprinter-Silhouette, die kein anderes Skelett hat. Läufer anderer Spiele sind Kopien; dieser ist ein dürrer Sprinter.',
    silhouette: 'Geduckt, sehr lange Beine, Stirnband flattert waagerecht.',
    mainName: 'Knochenweiß',
    accName: 'Sprintorange (Stirnband)',
    materials: [['Schatten', '#c8bca0']],
    signature: 'Ein langes Sprinter-Stirnband, das waagerecht nach hinten flattert.',
    details: {
      kleidung: 'nur Stirnband',
      material: 'Knochen, Stoff',
      muster: 'Knochenrillen',
      schnallen: 'keine',
      abnutzung: 'Rußflecken vom Fass',
      accessoires: 'Stirnband (Teamzone)',
    },
    face: 'Gehetzter Schädel mit aufgerissenen Augen und offenem Kiefer.',
    weapon: 'Bloße Knochenfäuste, mit denen er sich im Hechtsprung gegen das Gebäude wirft.',
    anim: {
      idle: ['trippelt auf der Stelle'],
      walk: ['rennt mit rudernden Armen'],
      attack: ['Hechtsprung mit Faustschlag'],
      hit: ['stolpert'],
      spawn: ['springt aus der Explosion'],
      death: ['zerfällt im Laufen'],
    },
  },
  'general-gerry': {
    concept: 'General Gerry ist ein kommandierender Skelett-General mit Zweispitz und Federbusch, goldenen Epauletten und Säbel. Solange er lebt, kämpfen gefallene Skelette als Schatten weiter.',
    unique: 'Zweispitz mit Federbusch und Epauletten breiter als der Schädel sind einmalig unter den Skeletten. Skelettgeneräle anderer Spiele tragen Helme; dieser trägt einen Zweispitz und einen schwarzen Rock.',
    silhouette: 'Winzig mit breitem Zweispitz und Epauletten, Säbel erhoben.',
    mainName: 'Rockschwarz',
    accName: 'Epaulettengold',
    materials: [['Knochen', '#efe6d0'], ['Säbel', '#c8ccd2']],
    signature: 'Ein Zweispitz mit Federbusch (Teamzone).',
    details: {
      kleidung: 'Zweispitz, Uniformrock mit Epauletten, Knochen',
      material: 'Filz, Gold, Knochen',
      muster: 'Goldlitzen',
      schnallen: 'Rockknöpfe',
      abnutzung: 'Mottenlöcher',
      accessoires: 'Federbusch und Schärpe (Teamzonen)',
    },
    face: 'Schädel mit Monokel und kommandierend offenem Kiefer.',
    weapon: 'Säbel und kleiner Rundschild.',
    anim: {
      idle: ['zeigt mit dem Säbel nach vorn'],
      walk: ['Stechschritt'],
      attack: ['Säbelhieb mit Schildstoß'],
      hit: ['Zweispitz verrutscht'],
      spawn: ['landet und salutiert'],
      death: ['fällt, der Zweispitz bleibt liegen'],
    },
  },
  'shadow-skeleton': {
    concept: 'Das Schattenskelett ist ein flüsternder, unheimlicher Schatten eines gefallenen Skeletts. Statt Beinen hat es einen Rauchschweif. Es kämpft unverwundbar weiter, solange General Gerry lebt.',
    unique: 'Rauchschweif statt Beine und violette Schattenfarbe unterscheiden es klar vom normalen Skelett. Schattenwesen anderer Spiele sind schwarze Klone; dieses ist violett mit leuchtenden Augen.',
    silhouette: 'Winziger Schädel und Oberkörper über einem gewundenen Rauchschweif.',
    mainName: 'Schattenviolett',
    accName: 'Fliederlicht',
    materials: [],
    signature: 'Ein wabernder Rauchschweif ersetzt die Beine.',
    details: {
      kleidung: 'keine',
      material: 'Schatten, Rauch',
      muster: 'Rauchlocken',
      schnallen: 'keine',
      abnutzung: 'keine',
      accessoires: 'Augenglut-Ring (Teamzone)',
    },
    face: 'Leuchtende Augen und ein flüsternder, verschwommener Kiefer.',
    weapon: 'Ein Schattendolch aus violettem Rauch, der nur im Moment des Stichs Form annimmt.',
    anim: {
      idle: ['flackert und wabert'],
      walk: ['gleitet'],
      attack: ['Schattenstich'],
      hit: ['keine Reaktion (unverwundbar), nur Wabern'],
      spawn: ['steigt aus einem gefallenen Skelett'],
      death: ['löst sich auf, wenn Gerry fällt'],
    },
  },
  skeletrooper: {
    concept: 'Der Skelett-Fallschirmjäger ist ein tollkühner Kadett mit Fliegerbrille, Schal und Fallschirm-Packsack. Er springt aus dem Helden-Ballon auf Bodentruppen, landet mit dem Speer voran und kämpft weiter.',
    unique: 'Fallschirm-Packsack mit Reißleine und Fliegerbrille sind einmalig. Fallschirmspringer anderer Spiele sind Soldaten; dieser ist ein olivgrün eingekleidetes Skelett.',
    silhouette: 'Winzig mit Packsack auf dem Rücken und Speer, Brille auf dem Schädel.',
    mainName: 'Oliv (Overall, Packsack)',
    accName: 'Knochenweiß',
    materials: [['Brille (Messing)', '#c8a046'], ['Fallschirm', '#f0e6d0']],
    signature: 'Ein Fallschirm-Packsack mit Reißleine; beim Sprung öffnet sich der Schirm.',
    details: {
      kleidung: 'Overall, Fliegerbrille, Schal',
      material: 'Segeltuch, Leder, Knochen',
      muster: 'Packsack-Nähte',
      schnallen: 'Gurte mit Schnellverschluss',
      abnutzung: 'gerissene Leine',
      accessoires: 'Fliegerschal und Packsack-Streifen (Teamzonen)',
    },
    face: 'Schädel mit Fliegerbrille und tollkühnem Grinsen.',
    weapon: 'Kurzer Landungsspeer mit Knochenspitze und gerolltem Wimpel am Schaft.',
    anim: {
      idle: ['zieht an den Gurten'],
      walk: ['zackiger Schritt'],
      attack: ['Speerstöße'],
      hit: ['Brille rutscht'],
      spawn: ['schwebt am Schirm herab, landet mit Speer voran (`char.land`)'],
      death: ['Schirm deckt ihn zu'],
    },
  },
  'royal-ghost': {
    concept: 'Der Königsgeist ist eine melancholische, leere Ritterrüstung aus Helm und Brustpanzer, über der eine Krone schwebt. Statt Beinen hat er einen Geisterschweif. Er ist unsichtbar, bis er mit dem Geistersäbel zuschlägt.',
    unique: 'Die schwebende Krone über einem leeren Helm ist einmalig; der Skelettkönig trägt ein Geweih, die Grabkönigin einen Sarkophag. Geisterkönige anderer Spiele sind Gespenster mit Laken; dieser ist eine leere Rüstung.',
    silhouette: 'Tropfenform: Helm, Brustpanzer, Schweif; darüber eine kleine Krone.',
    mainName: 'Geisterminze',
    accName: 'Altgold (Krone)',
    materials: [['Rüstung', '#b8c8c0']],
    signature: 'Eine kleine Krone schwebt über dem leeren Helm; aus dem Visier scheint Licht.',
    details: {
      kleidung: 'Helm, Brustpanzer, zerfetzter Umhang',
      material: 'Geisterstahl, Gold, Nebel',
      muster: 'Rostspuren, Umhangfetzen',
      schnallen: 'Panzerriemen',
      abnutzung: 'Löcher im Umhang',
      accessoires: 'Umhangfetzen (Teamzone)',
    },
    face: 'Leeres Visier mit zwei Lichtpunkten und einem Seufzer-Wölkchen.',
    weapon: 'Geistersäbel mit geschwungener, durchscheinender Klinge und Goldkorb, der eine Nebelwelle hinter sich herzieht.',
    anim: {
      idle: ['Krone kreist, der Schweif wabert'],
      walk: ['schwebt'],
      attack: ['Geistersäbel-Schwung mit Flächenwelle'],
      hit: ['Rüstung klappert, er wird kurz sichtbar'],
      spawn: ['materialisiert sich'],
      death: ['Rüstung fällt in sich zusammen, die Krone steigt auf und verschwindet'],
    },
    special: { evo: 'Seelen-Evo: Die Krone bekommt drei Juwelen, die Rüstung leuchtende Kanten, ein langer Geisterumhang kommt hinzu. Geisterfunken bilden die Partikelhülle; beim Sichtbarwerden steigen zwei Seelensoldaten auf.' },
  },
  souldier: {
    concept: 'Der Seelensoldat ist ein eifriger, durchscheinender Geisterpikenier mit einem Wimpelfetzen an der Pike. Er erscheint, wenn der Evo-Königsgeist sichtbar wird.',
    unique: 'Durchscheinender Geist mit überlanger Pike ist einmalig. Geistersoldaten anderer Spiele sind Ritter; dieser ist ein kleiner Pikenier.',
    silhouette: 'Tropfen mit langer Pike.',
    mainName: 'Geistermint',
    accName: 'Pergament (Wimpel)',
    materials: [],
    signature: 'Eine Geisterpike mit zerrissenem Wimpel.',
    details: {
      kleidung: 'Geisterhelm',
      material: 'Nebel',
      muster: 'Nebelschlieren',
      schnallen: 'keine',
      abnutzung: 'keine',
      accessoires: 'Wimpelfetzen (Teamzone)',
    },
    face: 'Zwei runde Lichtaugen und ein O-förmiger Mund.',
    weapon: 'Durchscheinende Pike, doppelt so lang wie der Geist, mit zerrissenem Wimpel unter der Spitze.',
    anim: {
      idle: ['schwebt im Kreis'],
      walk: ['schwebt'],
      attack: ['Pikenstoß'],
      hit: ['verwischt'],
      spawn: ['steigt mit Landeschaden aus dem Boden'],
      death: ['verweht'],
    },
  },
  tombstone: {
    concept: 'Der Grabstein ist ein schiefer, bemooster Grabstein, aus dessen Erde eine Skeletthand winkt. Davor flackert ein Grablicht. Alle vier Sekunden klettern zwei Skelette heraus.',
    unique: 'Die winkende Skeletthand vor dem Stein ist ein witziges, einmaliges Detail. Der Grabstein-Held ist ein Mausoleum. Grabsteine anderer Spiele sind einfache Steine; dieser winkt.',
    silhouette: 'Abgerundeter Grabstein, schief, davor eine Hand und eine Laterne.',
    mainName: 'Grabsteingrau',
    accName: 'Geistergrün (Grablicht)',
    materials: [['Moos', '#6a8a3a'], ['Erde', '#6b4a32']],
    signature: 'Eine Skeletthand ragt aus der Erde und winkt.',
    details: {
      kleidung: 'Stein, Erdhügel',
      material: 'Stein, Moos, Erde, Knochen',
      muster: 'Inschrift, Risse',
      schnallen: 'keine',
      abnutzung: 'Moos und Risse',
      accessoires: 'Grablicht-Schirm und Kranzschleife (Teamzonen)',
    },
    face: 'Kein Gesicht; die Inschrift ist ein Grinsen aus Rissen.',
    weapon: 'Keine eigene Waffe; die Skeletthand und das Grablicht sind die einzigen beweglichen Teile, die Skelette kommen aus der Erde.',
    anim: {
      idle: ['die Hand winkt, das Grablicht flackert'],
      walk: ['keine Fortbewegung'],
      attack: ['`char.spawnUnit`: Erde bricht auf, Skelette klettern heraus'],
      hit: ['Steinsplitter'],
      spawn: ['Stein fällt herab und bohrt sich in die Erde'],
      death: ['Stein zerbricht, vier Skelette springen heraus'],
    },
  },
};
