// Design-Briefs: Helden (Basisfigur + Rang-Merkmal + Spezial-Pose)
export default {
  'knight-hero': {
    concept: 'Der Ritter als Held ist derselbe sture Schildträger, jetzt in roségoldener Rüstung mit einem Löwenmähnen-Kragen und langem Heldenumhang. Mit seinem triumphalen Spott zwingt er alle Gegner in der Nähe, ihn anzugreifen. Dabei schützt ihn ein Schild aus Licht.',
    unique: 'Der Löwenmähnen-Kragen mit Umhang ist das Rang-Merkmal, das kein anderer Ritter trägt; Gesicht, Pflaster und Zinnenschild verraten den Basis-Ritter. Durch Roségold statt Zinn und die goldene Krone auf dem Schild ist er klar vom normalen Ritter zu unterscheiden. Heldenritter anderer Spiele tragen nur Gold; dieser hat Roségold und eine Löwenmähne.',
    silhouette: 'Wie der Ritter (breites Trapez mit Zinnenschild), zusätzlich ein wallender Umhang hinten und ein zottiger Mähnenkragen, der die Schultern noch breiter macht.',
    mainName: 'Roségold (Rüstung)',
    accName: 'Heldengold (Mähne, Schildkrone)',
    materials: [['Mähne', '#d8902a'], ['Wams', '#f0e6d0']],
    signature: 'Ein Kragen aus Löwenmähne aus Goldfäden, an dem ein langer Heldenumhang (Teamzone) hängt.',
    details: {
      kleidung: 'Nasalhelm mit Goldkamm, roségoldene Platten, Löwenmähnen-Kragen, Heldenumhang',
      material: 'Roségold, Goldfäden, Samt, Stein',
      muster: 'Löwenpranken-Gravur, Steinfugen am Schild',
      schnallen: 'Löwenkopf-Schließe am Umhang',
      abnutzung: 'polierte Kratzer',
      accessoires: 'Umhang und Schildfeld (Teamzonen), goldene Krone auf dem Zinnenschild',
    },
    face: 'Das Gesicht des Ritters mit Pflaster, jetzt mit herausforderndem Grinsen und hochgerecktem Kinn.',
    weapon: 'Breitklinge mit Löwenknauf und der Zinnenschild mit Goldkrone.',
    anim: {
      idle: ['Spott-Pose: schlägt das Schwert auf den Schild und winkt Gegner heran', 'Mähne weht'],
      walk: ['Marsch wie der Ritter, der Umhang schwingt groß'],
      attack: ['Schild vor, Hieb von oben (wie Basis, mit Umhangschwung)'],
      hit: ['grinst trotzig, der Schild leuchtet kurz'],
      spawn: ['landet mit Umhang-Bausch und Mähnen-Schütteln'],
      death: ['sinkt auf den Schild gestützt nieder, der Umhang deckt ihn zu'],
    },
    special: { pose: 'Triumphaler Spott: Schwert hoch, Schild gegen die Brust geschlagen, Brüll-Mund; Event `char.ability.knight-hero` erzeugt einen Spott-Ring und einen goldenen Schildschimmer. Rang-Merkmal: Löwenmähnen-Kragen mit Heldenumhang.' },
  },
  'giant-hero': {
    concept: 'Der Riese als Held ist der stolze Erntekönig: eine Krone aus Weizenähren statt der Bommelmütze und ein Steppdecken-Umhang. Er packt die stärkste gegnerische Truppe und schleudert sie quer über die Arena.',
    unique: 'Die Erntekrone aus Weizenähren und der Steppdecken-Umhang sind sein Rang-Merkmal; Latzhose, Handschuhe und Gesicht zeigen den Basis-Riesen. Er ist goldener und heller als der normale Riese. Heldenriesen anderer Spiele tragen Rüstung; dieser trägt Weizen und Quilt.',
    silhouette: 'Wie der Riese (Berg mit kleinem Kopf, riesigen Handschuhen), oben eine zackige Ährenkrone, hinten ein karierter Quilt-Umhang.',
    mainName: 'Erntebraun (Latzhose)',
    accName: 'Weizengold',
    materials: [['Quilt', '#c86a4a'], ['Haut', '#e9a97a']],
    signature: 'Eine Krone aus gebundenen Weizenähren.',
    details: {
      kleidung: 'Ährenkrone, Latzhose mit Goldflicken, Steppdecken-Umhang, Handschuhe',
      material: 'Stroh, Denim, Steppstoff, Leder',
      muster: 'Quiltkaros, Ährenbündel',
      schnallen: 'Latzknöpfe aus Messing',
      abnutzung: 'Strohhalme im Umhang',
      accessoires: 'Steppdecken-Umhang und Bommel am Krempelband (Teamzonen)',
    },
    face: 'Das gutmütige Gesicht des Riesen, jetzt mit stolz gerecktem Kinn und Grashalm.',
    weapon: 'Fäuste; die Fähigkeit packt ganze Truppen.',
    anim: {
      idle: ['Heldenwurf-Pose: packt in die Luft und holt weit aus'],
      walk: ['Stampfgang mit `char.step`, Umhang schwingt'],
      attack: ['Hammerfaust von oben'],
      hit: ['brummt, Ähren rascheln'],
      spawn: ['landet schwer, Ähren stieben'],
      death: ['setzt sich und kippt, die Krone fällt'],
    },
    special: { pose: 'Heldenwurf: Greifen (Anticipation weit zurück), Wurf mit ganzer Drehung, Follow-through; Event `char.ability.giant-hero` mit Wurf-Staubwirbel. Rang-Merkmal: Erntekrone aus Weizen.' },
  },
  'mini-pekka-hero': {
    concept: 'Mini-P.E.K.K.A. als Held ist ein patinagrüner Kessel-Automat mit einem Pfannkuchen-Turm samt Sirupflasche auf dem Rücken. Er füllt durch Treffer drei Pfannkuchen-Leisten. Mit seiner Fähigkeit verschlingt er die Pfannkuchen und wird stärker.',
    unique: 'Der Pfannkuchen-Turm mit Sirupflasche und Füllleisten ist ein einmaliges Rang-Merkmal; Zyklopenauge, Dampfpfeife und Rohrzange zeigen den Basis-Mini. Patina statt Zinn trennt ihn farblich. Helden-Roboter anderer Spiele bekommen Rüstung; dieser bekommt Frühstück.',
    silhouette: 'Wie der Mini (Kessel mit Pfeife), dazu ein hoher Pfannkuchen-Stapel auf dem Rücken.',
    mainName: 'Patinagrün (Kessel)',
    accName: 'Sirupgold',
    materials: [['Pfannkuchen', '#e8b060'], ['Serviette', '#f4f0e6']],
    signature: 'Ein Turm aus drei Pfannkuchen auf einem Teller, mit Sirupflasche, auf dem Rücken.',
    details: {
      kleidung: 'Kessel, Serviette um den Hals, Tellerhalter',
      material: 'Kupfer mit Patina, Teig, Glas',
      muster: 'Füllleisten am Teller',
      schnallen: 'Tellerklammern',
      abnutzung: 'Sirupkleckse',
      accessoires: 'Brustplakette und Serviette (Teamzonen)',
    },
    face: 'Zyklopenauge mit verfressen-begeistertem Blick; die Klappe zuckt beim Schnuppern.',
    weapon: 'Riesen-Rohrzange mit Gabel-Gravur am Griff; im Pfannkuchen-Modus dient sie als Pfannenwender.',
    anim: {
      idle: ['Pfannkuchen-Pose: schnuppert am Stapel, die Pfeife trällert'],
      walk: ['Tippelgang, der Stapel wackelt'],
      attack: ['Rohrzangen-Schlag mit Pfiff'],
      hit: ['Stapel wackelt gefährlich'],
      spawn: ['landet, ein Pfannkuchen hüpft hoch'],
      death: ['kippt um, Pfannkuchen rollen davon'],
    },
    special: { pose: 'Pfannkuchen-Power: Er reißt den Deckel auf und schaufelt den Stapel hinein (Pose); Event `char.ability.mini-pekka-hero` erzeugt Dampf und Stern-Funken. Rang-Merkmal: Pfannkuchen-Turm mit Sirup.' },
  },
  'musketeer-hero': {
    concept: 'Die Musketierin als Heldin ist eine tüchtige Ingenieurin in waldgrünem Reitrock mit einem Werkzeuggürtel samt Kurbel und Bauplan-Rolle. Mit ihrer Fähigkeit wirft sie einen Bausatz nach vorn, der zu einem Geschützturm aufklappt.',
    unique: 'Der Werkzeuggürtel mit Bauplan-Rolle und Kurbel ist ihr Rang-Merkmal; Gabel, Muskete und Kavaliershut zeigen die Basis-Musketierin. Waldgrün statt Ocker-Oliv trennt sie farblich. Helden-Schützinnen anderer Spiele tragen Orden; diese trägt Werkzeug.',
    silhouette: 'Wie die Musketierin, dazu ein breiter Gürtel mit Werkzeugen und eine Rolle quer über den Rücken.',
    mainName: 'Waldgrün (Reitrock)',
    accName: 'Messinggold (Werkzeug, Orden)',
    materials: [['Bauplan', '#f0e6d0'], ['Musketenholz', '#7a4a2a']],
    signature: 'Ein Werkzeuggürtel mit Kurbel, Schraubenschlüssel und einer Bauplan-Rolle.',
    details: {
      kleidung: 'Federhut mit Orden, Reitrock, Werkzeuggürtel, Stiefel',
      material: 'Wolle, Messing, Pergament, Leder',
      muster: 'Bauplan-Linien, Spitze',
      schnallen: 'Gürtelschnalle in Zahnradform',
      abnutzung: 'Ölflecken',
      accessoires: 'Hutfeder und Schärpe (Teamzonen)',
    },
    face: 'Das Gesicht der Musketierin, konzentriert, mit Bleistift hinter dem Ohr.',
    weapon: 'Muskete mit Gabel; der Turm-Bausatz für die Fähigkeit.',
    anim: {
      idle: ['Bauplan-Pose: entrollt den Plan und zeigt nach vorn'],
      walk: ['ruhiger Schritt, Werkzeuge klappern'],
      attack: ['Gabel aufstellen, Schuss'],
      hit: ['hält den Hut fest'],
      spawn: ['landet, rollt den Plan aus'],
      death: ['sinkt nieder, der Plan flattert davon'],
    },
    special: { pose: 'Treuer Geschützturm: Sie wirft den Bausatz in hohem Bogen (Pose mit Wurfarm); Event `char.ability.musketeer-hero` am Aufschlag. Rang-Merkmal: Werkzeuggürtel mit Bauplan.' },
  },
  'ice-golem-hero': {
    concept: 'Der Eisgolem als Held trägt eine Eiskrone mit Schneeflocken-Zacken und eine Frostschärpe, und um seinen Bauch kreist ein kleiner Schneesturm. Mit seiner Fähigkeit stößt er dreimal Eis in die Runde.',
    unique: 'Die Eiskrone und der kreisende Schneewirbel sind sein Rang-Merkmal; der eingefrorene Fisch und der Schal zeigen den Basis-Eisgolem. Die hellere Eisfarbe und das Gold der Krone trennen ihn farblich. Eis-Helden anderer Spiele sind Kristallriesen; dieser trägt eine Krone über einem Fisch.',
    silhouette: 'Wie der Eisgolem (Kugel mit Fisch), oben eine zackige Krone, um den Bauch ein Wirbelring.',
    mainName: 'Gletscherweiß',
    accName: 'Kronengold',
    materials: [['Fisch', '#ff9a62']],
    signature: 'Eine Krone aus Eiszacken in Schneeflockenform mit Goldrand.',
    details: {
      kleidung: 'Eiskrone, Frostschärpe, Strickschal',
      material: 'Eis, Gold, Wolle',
      muster: 'Schneeflocken',
      schnallen: 'keine',
      abnutzung: 'Schmelztropfen',
      accessoires: 'Frostschärpe und Strickschal (Teamzonen)',
    },
    face: 'Majestätisch-verschlafen, gähnt mit hochgezogenen Brauen.',
    weapon: 'Kopfstoß und Eisstöße.',
    anim: {
      idle: ['Schneesturm-Pose: Arme hoch, der Wirbel kreist'],
      walk: ['Watschelgang, der Wirbel folgt'],
      attack: ['Kopfstoß'],
      hit: ['Eis splittert'],
      spawn: ['landet mit Schneewirbel'],
      death: ['zerspringt, die Krone bleibt liegen'],
    },
    special: { pose: 'Schneesturm: drei Stampfer mit Armen hoch; Event `char.ability.ice-golem-hero` pro Stoß. Rang-Merkmal: Eiskrone.' },
  },
  'wizard-hero': {
    concept: 'Der Magier als Held ist ein großspuriger Feuermagier in fuchsiafarbener Robe, dessen Flammenumhang sich zu Flügeln öffnet. Mit seiner Fähigkeit fliegt er kurz und erzeugt Feuerwirbel, die Gegner anziehen.',
    unique: 'Der Flammenumhang, der zu Flügeln aufgeht, ist sein Rang-Merkmal; das fliegende Zauberbuch und die Ballonärmel zeigen den Basis-Magier. Fuchsia statt Weinrot trennt ihn farblich. Fliegende Helden-Magier anderer Spiele reiten Besen; dieser fliegt mit seinem Umhang.',
    silhouette: 'Wie der Magier (Dreieck, Buch), dazu ein breiter Umhang mit Flammenrand, im Flug als Flügel ausgebreitet.',
    mainName: 'Fuchsia (Robe)',
    accName: 'Flammenorange (Umhang)',
    materials: [['Buch', '#5a3a28'], ['Bart', '#d8d0c4']],
    signature: 'Ein Umhang mit Flammenrand, der sich zu zwei Feuerflügeln öffnet.',
    details: {
      kleidung: 'Robe, Flammenumhang, Hut mit Flamme',
      material: 'Samt, Feuer',
      muster: 'Flammenstickerei',
      schnallen: 'Flammenbrosche',
      abnutzung: 'angesengter Saum',
      accessoires: 'Gürtelschärpe und Hutband (Teamzonen)',
    },
    face: 'Das Magiergesicht, großspurig mit hochgerecktem Bart.',
    weapon: 'Feuerspuckendes Buch.',
    anim: {
      idle: ['Flug-Pose: Umhang bauscht sich, die Füße heben leicht ab'],
      walk: ['wehender Schritt'],
      attack: ['Taktstock hoch, das Buch spuckt'],
      hit: ['Umhang flackert'],
      spawn: ['landet mit Flammenring'],
      death: ['Umhang erlischt, er sinkt zusammen'],
    },
    special: { pose: 'Feuriger Flug: Umhang zu Flügeln, Füße hoch (Flug-Zustand über `FLY`); Event `char.ability.wizard-hero` erzeugt Flammenflügel. Rang-Merkmal: Flammenumhang.' },
  },
  'goblins-hero': {
    concept: 'Die Kobolde als Helden sind eine kriegerische Bannerbrigade mit Kriegsbemalung und pflaumenbraunen Lederwesten. Jeder trägt ein Brigade-Banner auf dem Rücken. Fällt der letzte, rammt er das Banner in den Boden und ruft Verstärkung.',
    unique: 'Das Brigade-Banner auf dem Rücken ist ihr Rang-Merkmal; Löffeldolch und Riesenohren zeigen die Basis-Kobolde. Pflaumenbraun und Kriegsbemalung trennen sie farblich. Helden-Kobolde anderer Spiele tragen Helme; diese tragen Banner.',
    silhouette: 'Wie die Kobolde, dazu eine Bannerstange doppelt so hoch wie der Kobold.',
    mainName: 'Pflaumenbraun (Weste)',
    accName: 'Goldgelb (Bannerspitze, Ringe)',
    materials: [['Haut', '#7fae4a'], ['Kriegsbemalung', '#f2efe6']],
    signature: 'Ein Banner an einer Stange mit Löffel als Spitze.',
    details: {
      kleidung: 'Lederweste, Kriegsbemalung, Halstuch',
      material: 'Leder, Stoff, Zinn',
      muster: 'Bemalungsstreifen',
      schnallen: 'Bannerhalter',
      abnutzung: 'zerrissenes Banner',
      accessoires: 'Bannertuch und Halstuch (Teamzonen)',
    },
    face: 'Kriegerisch-freches Grinsen mit Bemalung.',
    weapon: 'Löffeldolch; das Banner.',
    anim: {
      idle: ['Banner-Pose: schwenkt das Banner'],
      walk: ['Trippeln, das Banner flattert'],
      attack: ['Löffeldolch-Stich'],
      hit: ['Banner zuckt'],
      spawn: ['landen mit wehenden Bannern'],
      death: ['fallen, das Banner sinkt'],
    },
    special: { pose: 'Bannerbrigade: rammt das Banner in den Boden (Pose); Event `char.ability.goblins-hero`. Rang-Merkmal: Brigade-Banner.', variants: 'wie Kobolde' },
  },
  'mega-minion-hero': {
    concept: 'Der Megalakai als Held trägt einen Visierhelm mit Heldenstern und eine Goldgravur auf dem Steinbauch. Er fixiert sein Ziel. Mit seiner Fähigkeit teleportiert er sich zum schwächsten Gegner.',
    unique: 'Visierhelm mit Heldenstern ist sein Rang-Merkmal; Steinbauch und Wasserspeier-Hörner zeigen den Basis-Megalakai. Helleres Grau-Lila und Gold trennen ihn farblich.',
    silhouette: 'Wie der Megalakai, dazu ein Helm mit Visier und Stern.',
    mainName: 'Lavendelgrau',
    accName: 'Heldengold',
    materials: [['Stein', '#b0a8c0']],
    signature: 'Ein Visierhelm mit goldenem Heldenstern.',
    details: {
      kleidung: 'Visierhelm, Steinbauch mit Gravur',
      material: 'Stein, Gold, Stahl',
      muster: 'Goldgravur',
      schnallen: 'Helmriemen',
      abnutzung: 'Kratzer',
      accessoires: 'Armbinde und Helmbusch (Teamzonen)',
    },
    face: 'Hinter dem Visier zwei fixierende Augen.',
    weapon: 'Sturzfaust aus Stein mit Goldbändern und Heldenstern; beim Teleport glüht sie weiß.',
    anim: {
      idle: ['Sprung-Pose: duckt sich in der Luft zum Teleport'],
      walk: ['schwerer Flug'],
      attack: ['Sturzfaust'],
      hit: ['Visier klappert'],
      spawn: ['erscheint in einem Lichtblitz'],
      death: ['stürzt'],
    },
    special: { pose: 'Verwundender Sprung: zusammengeduckt, dann Teleport; Event `char.ability.mega-minion-hero` mit Lichtriss. Rang-Merkmal: Visierhelm mit Heldenstern.' },
  },
  'magic-archer-hero': {
    concept: 'Der Magieschütze als Held trägt einen Sternbild-Mantel, auf dem sich drei leuchtende Pfeilsterne bewegen. Mit seiner Fähigkeit springt er zurück, lässt einen Lockvogel aus Sternenstaub stehen und schießt drei weite Pfeile.',
    unique: 'Der Sternbild-Mantel mit beweglichen Pfeilsternen ist sein Rang-Merkmal; Fernrohr-Bogen und Astrolabium-Hut zeigen den Basis-Magieschützen. Helleres Sternenviolett trennt ihn farblich.',
    silhouette: 'Wie der Magieschütze, dazu ein langer, weiter Mantel mit Sternmuster.',
    mainName: 'Sternenviolett',
    accName: 'Sternlicht',
    materials: [['Messing', '#c8a046']],
    signature: 'Ein Mantel mit drei leuchtenden Pfeil-Sternbildern.',
    details: {
      kleidung: 'Sternbild-Mantel, Astrolabium-Hut',
      material: 'Samt, Messing, Licht',
      muster: 'Sternbilder',
      schnallen: 'Sternschließe',
      abnutzung: 'keine',
      accessoires: 'Hutband und Umhangfutter (Teamzonen)',
    },
    face: 'Gerissen-verspielter Blick, ein Mundwinkel hoch.',
    weapon: 'Fernrohr-Bogen mit drei Sternensehnen, mit denen er beim Dreifachschuss drei Lichtpfeile auffächert.',
    anim: {
      idle: ['Dreifach-Pose: fächert drei Pfeile auf'],
      walk: ['schlendernd'],
      attack: ['Lichtpfeil'],
      hit: ['Sterne flackern'],
      spawn: ['landet in Sternenstaub'],
      death: ['löst sich in Sternbilder auf'],
    },
    special: {
      pose: 'Dreifachgefahr: Rückwärtssprung (Pose), dann drei Pfeile; Event `char.ability.magic-archer-hero` mit Sternenspur. Rang-Merkmal: Sternbild-Mantel.',
      forms: { decoy: 'Lockvogel: halb durchsichtiger Doppelgänger aus Sternenstaub in Mintschimmer, der still steht und funkelt.' },
    },
  },
  'balloon-hero': {
    concept: 'Der Ballon als Held ist ein lachsfarbener Zwiebelkuppel-Ballon mit einem Fallschirm-Ausleger am Korb. Neben dem Gnom-Piloten sitzt ein Skelett-Kadett, der mit Fallschirm auf Bodentruppen abspringt.',
    unique: 'Der Skelett-Kadett im Korb ist sein Rang-Merkmal; Zwiebelkuppel und Gnom zeigen den Basis-Ballon. Lachs statt Pflaume trennt ihn farblich.',
    silhouette: 'Wie der Ballon, dazu ein Ausleger und ein zweiter Kopf im Korb.',
    mainName: 'Lachs (Hülle)',
    accName: 'Nachtblau-Grau (Nähte)',
    materials: [['Korb', '#a8763e']],
    signature: 'Ein Skelett-Kadett mit Fallschirm sitzt im Korb.',
    details: {
      kleidung: 'Gnom mit Fliegermütze, Kadett mit Brille',
      material: 'Stoff, Weide, Knochen',
      muster: 'Flicken',
      schnallen: 'Ausleger-Seile',
      abnutzung: 'Flicken',
      accessoires: 'Wimpelkette und Korbrand (Teamzonen)',
    },
    face: 'Gnom kichernd, Kadett salutierend.',
    weapon: 'Eisenbomben mit Flossen und der Skelett-Kadett, der als lebendes Geschoss abspringt.',
    anim: {
      idle: ['Absprung-Pose: der Kadett klettert auf den Korbrand'],
      walk: ['gleitet'],
      attack: ['Bombenabwurf'],
      hit: ['Hülle bebt'],
      spawn: ['schwebt herab'],
      death: ['trudelt, Todesbombe'],
    },
    special: { pose: 'Sargkadetten: Kadett springt mit Schirm (Pose am Korbrand); Event `char.ability.balloon-hero`. Rang-Merkmal: Skelett-Kadett mit Fallschirm.' },
  },
  'bowler-hero': {
    concept: 'Der Bowler als Held ist ein triumphierender Kegelkönig aus weißem Marmor mit einer Krone aus Kegeln. Mit seiner Fähigkeit stellt er sich auf und wirft Felsen wie ein Mörser.',
    unique: 'Die Kegelkrone ist sein Rang-Merkmal; Hosenträger und Runenkugel zeigen den Basis-Bowler. Marmorweiß statt Moosgrün trennt ihn farblich.',
    silhouette: 'Wie der Bowler, oben eine Krone aus kleinen Kegeln.',
    mainName: 'Marmorweiß',
    accName: 'Kronengold',
    materials: [['Kegel', '#f6f2ea'], ['Kugel', '#6a7a8a']],
    signature: 'Eine Krone aus neun kleinen Kegeln.',
    details: {
      kleidung: 'Kegelkrone, Hemd, Hosenträger',
      material: 'Marmor, Holz, Wolle',
      muster: 'Marmoradern',
      schnallen: 'Hosenträgerklemmen',
      abnutzung: 'angeschlagener Kegel',
      accessoires: 'Hosenträger und Kegelband (Teamzonen)',
    },
    face: 'Triumphierendes Grinsen mit Hauern.',
    weapon: 'Runenkugel; Felsbrocken im Mörserwurf.',
    anim: {
      idle: ['Mörser-Pose: stemmt einen Felsen über den Kopf'],
      walk: ['schlurfend'],
      attack: ['Kegelwurf'],
      hit: ['Kegel klappern'],
      spawn: ['landet, Kegel wackeln'],
      death: ['zerbröselt, die Krone fällt'],
    },
    special: { pose: 'Steinwurf: breitbeinig, Felsen über dem Kopf, Wurf im hohen Bogen; Event `char.ability.bowler-hero`. Rang-Merkmal: Kegelkrone.' },
  },
  'dark-prince-hero': {
    concept: 'Der Dunkle Prinz als Held reitet ein gepanzertes Nashorn und trägt eine Sichelmond-Krone über dem Visier. Mit seiner Fähigkeit springt er ab. Das Nashorn stürmt allein zu Gebäuden, der Prinz kämpft zu Fuß weiter.',
    unique: 'Die Sichelmond-Krone ist sein Rang-Merkmal; Morgenstern und Sichelschild zeigen den Basis-Prinzen. Das Nashorn statt des Warans macht die Silhouette breiter.',
    silhouette: 'Breites Nashorn mit Reiter, oben eine Sichelkrone.',
    mainName: 'Nachtgrün (Rüstung)',
    accName: 'Limette',
    materials: [['Nashorn', '#8a8f80']],
    signature: 'Eine Krone in Sichelmond-Form über dem Visier.',
    details: {
      kleidung: 'Visierhelm mit Sichelkrone, Plattenrüstung',
      material: 'brünierter Stahl, Silber',
      muster: 'Sichelgravuren',
      schnallen: 'Sattelgurte',
      abnutzung: 'Kratzer',
      accessoires: 'Schabracke und Schildmitte (Teamzonen)',
    },
    face: 'Limettengrüne Augenschlitze, eiskalt.',
    weapon: 'Morgenstern und Sichelschild.',
    anim: {
      idle: ['Absprung-Pose: steht in den Steigbügeln'],
      walk: ['Nashorn trabt mit `char.step`'],
      attack: ['Morgenstern-Rundumschlag'],
      hit: ['Nashorn schnaubt'],
      spawn: ['landet schwer'],
      death: ['fällt vom Nashorn'],
    },
    special: { pose: 'Zerstörerischer Absprung: Sprung aus dem Sattel mit Landung (Pose); Event `char.ability.dark-prince-hero` mit Landeschaden-Ring. Rang-Merkmal: Sichelmond-Krone.', extra: '**Zu Fuß (nach dem Absprung):** Teile des Nashorns entfallen, der Prinz läuft mit dem Morgenstern.' },
  },
  'berserker-hero': {
    concept: 'Die Berserkerin als Heldin trägt einen Bärenfell-Umhang mit Bärenkopf-Kapuze über dem Kochtopf. Mit ihrer Fähigkeit erscheint ein Bärengeist um sie herum, und sie schlägt rasend schnell zu.',
    unique: 'Bärenfell-Umhang mit Bärenkopf ist ihr Rang-Merkmal; Kochtopf und Pfannen zeigen die Basis-Berserkerin. Bärenbraun statt Kupfer trennt sie farblich.',
    silhouette: 'Wie die Berserkerin, dazu ein zottiger Umhang mit Bärenkopf.',
    mainName: 'Bärenbraun',
    accName: 'Moosgrün',
    materials: [['Kochtopf', '#c96f3b'], ['Pfannen', '#3e3c42']],
    signature: 'Ein Bärenfell-Umhang mit Bärenkopf-Kapuze über dem Topf.',
    details: {
      kleidung: 'Bärenfell, Kochtopf, Kleid, Schürze',
      material: 'Fell, Kupfer, Gusseisen',
      muster: 'Fellstriche',
      schnallen: 'Krallenschließe',
      abnutzung: 'zerzaustes Fell',
      accessoires: 'Schürze und Zopfbänder (Teamzonen)',
    },
    face: 'Wilder Blick, brüllender Mund.',
    weapon: 'Zwei Bratpfannen mit Bärenkrallen-Kerben am Rand, die in der Raserei glühen.',
    anim: {
      idle: ['Wut-Pose: Pfannen hoch, der Bärenkopf brüllt'],
      walk: ['hüpfender Laufschritt'],
      attack: ['Pfannenwirbel'],
      hit: ['Fell sträubt sich'],
      spawn: ['landet brüllend'],
      death: ['sinkt unter dem Fell zusammen'],
    },
    special: { pose: 'Wilde Wut: Bärengeist-Schemen umhüllt sie (Pose); Event `char.ability.berserker-hero`. Rang-Merkmal: Bärenfell-Umhang.' },
  },
  'valkyrie-hero': {
    concept: 'Die Walküre als Heldin trägt einen Sturmflügelhelm mit großen goldenen Schwingen, und an ihrer Radaxt hängen Windbänder. Mit ihrer Fähigkeit wirbelt sie dreieinhalb Sekunden lang wie ein Wirbelwind.',
    unique: 'Der Sturmflügelhelm mit goldenen Schwingen ist ihr Rang-Merkmal; Radaxt und Zöpfe zeigen die Basis-Walküre. Helleres Sturmgrau trennt sie farblich.',
    silhouette: 'Wie die Walküre, mit viel größeren Helmflügeln und flatternden Bändern.',
    mainName: 'Sturmgrau',
    accName: 'Schwingengold',
    materials: [['Zöpfe', '#f2e6c4']],
    signature: 'Ein Helm mit großen goldenen Sturmschwingen.',
    details: {
      kleidung: 'Sturmflügelhelm, Schuppenpanzer, Windbänder',
      material: 'Gold, Stahl, Seide',
      muster: 'Wolkenornament',
      schnallen: 'Radschnalle',
      abnutzung: 'keine',
      accessoires: 'Gürtel und Windbänder (Teamzonen)',
    },
    face: 'Das Gesicht der Walküre mit Sommersprossen, im Sturm lachend mit offenem Mund und blitzenden Augen.',
    weapon: 'Radaxt mit Windbändern.',
    anim: {
      idle: ['Wirbelwind-Pose: Axt über dem Kopf kreisend'],
      walk: ['kraftvoller Schritt'],
      attack: ['Drehschlag'],
      hit: ['Bänder flattern'],
      spawn: ['landet mit einem Windstoß'],
      death: ['dreht sich aus'],
    },
    special: { pose: 'Wilder Wirbelwind: Dauerdrehung (Fähigkeits-Zustand); Event `char.ability.valkyrie-hero` mit Windwirbel. Rang-Merkmal: Sturmflügelhelm.' },
  },
  'ice-wizard-hero': {
    concept: 'Der Eismagier als Held ist ein großväterlicher Zauberer mit einem kleinen Schneemann-Gehilfen auf der Schulter. In seiner Schneekugel tanzt ein Schneemann. Mit seiner Fähigkeit beschwört er einen großen Schneemann, der Gegner einfriert.',
    unique: 'Der Schneemann-Gehilfe auf der Schulter ist sein Rang-Merkmal; Eiszapfenbart und Schneekugel-Stab zeigen den Basis-Eismagier. Ein reineres Weiß mit Eistürkis trennt ihn farblich.',
    silhouette: 'Wie der Eismagier, mit einer kleinen runden Figur auf der Schulter.',
    mainName: 'Schneeweiß',
    accName: 'Eistürkis',
    materials: [['Rübe', '#ff8a3a']],
    signature: 'Ein kleiner Schneemann-Gehilfe sitzt auf seiner Schulter.',
    details: {
      kleidung: 'Pelzmantel, Pelzmütze, Schal',
      material: 'Pelz, Schnee, Glas',
      muster: 'Schneeflocken',
      schnallen: 'Eiszapfen-Knöpfe',
      abnutzung: 'Raureif',
      accessoires: 'Schal und Mantelsaum (Teamzonen)',
    },
    face: 'Großväterliches Lachen, rosige Wangen.',
    weapon: 'Birkenstab mit einer größeren Schneekugel, in der ein winziger Schneemann tanzt; Eiszapfen hängen am Kugelsockel.',
    anim: {
      idle: ['Frostkerl-Pose: formt einen Schneeball'],
      walk: ['gemächlich'],
      attack: ['Eissplitter-Fächer'],
      hit: ['der Gehilfe wackelt'],
      spawn: ['landet mit Frostschlag'],
      death: ['friert ein, der Gehilfe rollt davon'],
    },
    special: { pose: 'Frostkerl: wirft den Schneeball nach vorn, der zum Schneemann wird (Pose); Event `char.ability.ice-wizard-hero`. Rang-Merkmal: Schneemann-Gehilfe.' },
  },
  'tombstone-hero': {
    concept: 'Der Grabstein als Held ist ein kleines Mausoleum mit Säulen und einer Krone über dem Portal. Alle paar Sekunden schlurfen Skelette heraus. Mit seiner Fähigkeit öffnet sich das Tor für die Grabkönigin.',
    unique: 'Ein Mausoleum mit Säulen und Krone ist das Rang-Merkmal; der normale Grabstein ist ein schiefer Stein mit Hand. Grabbauten anderer Spiele sind Krypten; dieses trägt eine Krone.',
    silhouette: 'Kleiner Tempel mit Dreiecksgiebel, zwei Säulen, Tor und Krone.',
    mainName: 'Schiefergrau',
    accName: 'Kronengold',
    materials: [['Moos', '#6a8a3a'], ['Tor', '#3a3540']],
    signature: 'Ein Mausoleum mit zwei Säulen und einer Krone über dem Portal.',
    details: {
      kleidung: 'Säulen, Giebel, Tor',
      material: 'Stein, Gold, Eisen',
      muster: 'Inschrift, Säulenkannelur',
      schnallen: 'Torbeschläge',
      abnutzung: 'Moos und Risse',
      accessoires: 'Torbanner und Kranzschleife (Teamzonen)',
    },
    face: 'Kein Gesicht; im Tor leuchten zwei Augen.',
    weapon: 'Keine eigene Waffe; das zweiflügelige Eisentor öffnet sich, und Nebel und Skelette quellen heraus.',
    anim: {
      idle: ['Tor knarrt, Licht flackert'],
      walk: ['keine Fortbewegung'],
      attack: ['`char.spawnUnit`: Skelette schlurfen heraus'],
      hit: ['Steinsplitter'],
      spawn: ['steigt aus dem Boden'],
      death: ['stürzt ein'],
    },
    special: { pose: 'Königliche Wiederkehr: das Tor öffnet sich weit, Nebel quillt heraus (Pose); Event `char.ability.tombstone-hero`. Rang-Merkmal: Krone über dem Portal.' },
  },
};
