// Design-Briefs: Kobolde
export default {
  goblins: {
    concept: 'Die Kobolde sind vier flinke, gierige Racker mit riesigen Ohren voller Goldringe. Sie stechen mit geschliffenen Löffeln zu. Wo es glänzt, sind sie zuerst.',
    unique: 'Der Löffeldolch ist eine Waffe, die nur sie tragen; zusammen mit den beringten Riesenohren bilden sie eine eigene winzige Silhouette. Speerkobolde tragen Anglerhüte und Speerbündel, der Busch-Kobold einen Tarnanzug. Gängige Kobolde haben Messer und Lendenschurz; diese tragen Lumpenwesten, Halstücher und Besteck.',
    silhouette: 'Winzig mit großem Kopf; die Ohren stehen waagerecht ab wie Flügel, der Löffel ragt nach vorn.',
    mainName: 'Lederbraun (Lumpenweste)',
    accName: 'Knochenweiß (Löffel, Zähne)',
    materials: [['Ohrringe (Gold)', '#f2c14e'], ['Hose', '#5a4a3a']],
    signature: 'Ein zu einer Klinge geschliffener Esslöffel mit verbogenem Stiel und Wicklung am Griff.',
    details: {
      kleidung: 'Lumpenweste mit Flicken, kurze Hose, nackte Füße',
      material: 'Leder, Sackleinen, Zinn',
      muster: 'grobe Kreuzstiche, Flicken',
      schnallen: 'Knotengürtel',
      abnutzung: 'Löcher in der Weste',
      accessoires: 'Halstuch und Gürtelknoten (Teamzonen), Ohrringe, Beutel mit Glitzerkram',
    },
    face: 'Spitze Nase, breites gieriges Grinsen mit spitzen Zähnen, große gelbe Augen. Je nach Variante Zahnlücke oder Nasenring.',
    weapon: 'Löffeldolch: geschliffener Löffel mit Laffe als Klinge.',
    anim: {
      idle: ['hüpfen von Fuß zu Fuß, lecken am Löffel'],
      walk: ['schnelles Trippeln, Ohren schlackern'],
      attack: ['kurzer Ausfallschritt, schneller Stich mit dem Löffel'],
      hit: ['Ohren klappen nach hinten'],
      spawn: ['purzeln aus dem Fall und springen auf'],
      death: ['fallen um, der Löffel klappert weg'],
    },
    special: { variants: 'Ohrring links, Ohrring rechts, Zahnlücke, Nasenring; Farbton ±6°, Größe ±5 %' },
  },
  'spear-goblins': {
    concept: 'Die Speerkobolde sind drei eifrige Fischer-Kobolde mit Anglerhüten, an deren Krempe Haken hängen. Auf dem Rücken tragen sie ein Bündel Bambusspeere, die sie auf Boden- und Luftziele werfen.',
    unique: 'Das Bambusspeer-Bündel auf dem Rücken (5 Speere wie ein Fächer) und der Anglerhut geben eine hohe, gestreifte Silhouette; keine andere Kobold-Figur trägt Hut und Bündel. Speerwerfer anderer Spiele werfen einzelne Speere aus der Hand; diese ziehen aus einem Rückenbündel.',
    silhouette: 'Schlank mit flachem, breitkrempigem Hut, hinter dem Rücken ragen schräge Bambusspeere über den Kopf.',
    mainName: 'Kürbisorange (Weste)',
    accName: 'Schilf-Khaki (Hut, Bambus)',
    materials: [['Haut', '#93b844'], ['Speerspitzen', '#a8b0ba'], ['Angelhaken', '#c8ccd2']],
    signature: 'Fünf Bambusspeere mit Federn als Bündel in einer Schnur auf dem Rücken.',
    details: {
      kleidung: 'Anglerhut mit Haken, Weste mit vielen Taschen, kurze Hose, Gummisandalen',
      material: 'Bambus, Filz, Leinen, Eisen',
      muster: 'Bambusknoten, Hutkrempe mit Stichen',
      schnallen: 'Schnurknoten am Bündel',
      abnutzung: 'durchlöcherter Hut',
      accessoires: 'Hutband und Speerwimpel (Teamzonen), Angelhaken am Hut',
    },
    face: 'Breites Gesicht, herausgestreckte Zunge, ein zugekniffenes Auge beim Zielen, Ohren unter der Krempe.',
    weapon: 'Leichter Bambusspeer mit Eisenspitze und Federn am Ende.',
    anim: {
      idle: ['zählen die Speere im Bündel'],
      walk: ['schnelles Tippeln, Speere klappern'],
      attack: ['greift über die Schulter (Anticipation), weit ausholender Wurf mit Hüpfer'],
      hit: ['Hut fliegt kurz hoch'],
      spawn: ['landen und rücken den Hut zurecht'],
      death: ['Speere fallen aus dem Bündel, er sinkt zusammen'],
    },
    special: { variants: 'Haken am Hut, Feder am Hut, Flicken am Hut; Farbton ±6°, Größe ±5 %' },
  },
  'dart-goblin': {
    concept: 'Der Blasrohrkobold ist ein hibbeliger, hagerer Dschungel-Kobold mit einem Blasrohr, das doppelt so lang ist wie er selbst. Er schießt sehr schnell aus großer Entfernung und bläst dabei die Backen auf wie ein Kugelfisch.',
    unique: 'Das extrem lange Blasrohr bildet eine waagerechte Linie durch die ganze Silhouette; die aufgeblasenen Backen sind sein Angriffs-Ausdruck. Er trägt Magenta und Limette mit Federschmuck; andere Kobolde tragen Braun, Orange oder Tarnung. Blasrohr-Schützen anderer Spiele sind maskiert; dieser zeigt sein Gesicht.',
    silhouette: 'Geduckt nach vorn, die lange gerade Röhre waagerecht vor dem Gesicht, hinten ein Federbusch.',
    mainName: 'Magenta (Lendentuch, Federbusch)',
    accName: 'Limette (Federn, Pfeilbeutel)',
    materials: [['Haut', '#6fb08a'], ['Blasrohr (Bambus)', '#c8b06a'], ['Kürbisbeutel', '#e08a3a']],
    signature: 'Ein Bambus-Blasrohr mit Mundstück und Schnurwicklung, doppelt so lang wie der Kobold.',
    details: {
      kleidung: 'Lendentuch, Federkragen, Armbänder aus Samen',
      material: 'Bambus, Federn, Kürbisschale',
      muster: 'Federreihen, Bambusknoten',
      schnallen: 'Samenketten',
      abnutzung: 'gerupfte Federn',
      accessoires: 'Stirnband und Federschmuck (Teamzonen), Kürbis-Pfeilbeutel',
    },
    face: 'Hageres Gesicht mit großen Schielaugen, Backen, die sich beim Schuss zu Kugeln aufblasen, und spitzen Ohren mit Federn.',
    weapon: 'Langes Blasrohr; die Pfeile tragen Distelflaum.',
    anim: {
      idle: ['pustet Staub aus dem Rohr, schielt'],
      walk: ['schnelles Huschen in geduckter Haltung'],
      attack: ['Backen aufblasen (Anticipation, Squash des Kopfes), Pfeil, Backen fallen zusammen'],
      hit: ['verschluckt sich und hustet'],
      spawn: ['landet in der Hocke, Rohr im Anschlag'],
      death: ['kippt um, das Rohr rollt weg'],
    },
    special: { evo: 'Gift-Evo: Ein Giftfrosch sitzt auf der Schulter, die Pfeile haben grüne Tropfspitzen, dazu kommt eine Gift-Kürbisflasche. Grüne Giftbläschen bilden die Partikelhülle, die Federn werden giftgrün gesäumt.' },
  },
  'goblin-demolisher': {
    concept: 'Der Goblin Demolisher ist ein fröhlich-leichtsinniger Sprengmeister in einem kugelrunden, gepolsterten Bombenanzug mit Bullaugen-Helm. Er wirft Dynamit. Bei halbem Leben zündet er die Lunte am Helm und rennt auf das nächste Gebäude zu.',
    unique: 'Der Bullaugen-Helm (runde Glasscheibe mit Schrauben) auf einem Polsteranzug ist eine Taucher-ähnliche Silhouette, die sonst nicht vorkommt; die Warnstreifen sind Teamzone. Sprengmeister anderer Spiele tragen Kopftücher; dieser steckt komplett im Schutzanzug.',
    silhouette: 'Kugelrund, oben ein runder Helm mit Glasscheibe, kurze Arme und Beine; in der Hand eine Dynamitstange.',
    mainName: 'Khaki (Polsteranzug)',
    accName: 'Warngelb (Streifen, Lampe)',
    materials: [['Haut (hinter Glas)', '#7fae4a'], ['Dynamit', '#d4442a'], ['Helmmessing', '#c8a046']],
    signature: 'Ein Messinghelm mit großem Bullauge und acht Schrauben.',
    details: {
      kleidung: 'gepolsterter Bombenanzug mit Steppnähten, Bullaugen-Helm, dicke Handschuhe',
      material: 'Segeltuch, Polster, Messing, Glas',
      muster: 'Steppkaros, Warnstreifen',
      schnallen: 'Helmschrauben, Gürtel mit Dynamithalter',
      abnutzung: 'Brandlöcher',
      accessoires: 'Warnstreifen und Helmlampe (Teamzonen), Dynamitgürtel',
    },
    face: 'Hinter dem Bullauge ein grinsendes Koboldgesicht mit großen Augen, das gegen das Glas drückt.',
    weapon: 'Dynamitstangen mit kurzer Lunte.',
    anim: {
      idle: ['klopft an die Helmscheibe'],
      walk: ['watschelnd, der Anzug wippt'],
      attack: ['Dynamit über Kopf (Anticipation), Wurf'],
      hit: ['Polster beult ein'],
      spawn: ['plumpst, federt im Polster nach'],
      death: ['Anzug fällt in sich zusammen, Helm rollt'],
    },
    special: { forms: { kamikaze: 'Ansturm-Form: Die Lunte auf dem Helm brennt mit Funken, die Arme zeigen nach hinten, die Augen sind aufgerissen; das Glas beschlägt rot, und bei der Explosion bleibt nur der Helm.' } },
  },
  'goblin-brawler': {
    concept: 'Der Kobold-Raufbold ist ein wütender, muskulöser Kobold, der aus seinem Käfig ausgebrochen ist. An beiden Handgelenken hängen noch gesprengte Handschellen mit Kettenresten. Er boxt mit Fäusten groß wie sein Kopf.',
    unique: 'Die gesprengten Handschellen mit Kettenresten sind sein Merkmal, das sonst niemand trägt; zusammen mit der Keil-Silhouette wirkt er wie ein Boxer. Andere Kobolde sind winzig. Ausbrecher anderer Spiele tragen Sträflingsstreifen; dieser trägt Boxerhosen und Kettenwickel.',
    silhouette: 'Keil mit riesigen Schultern und Fäusten, gebückter Boxerstand, Kettenstücke baumeln.',
    mainName: 'Rostbraun (Boxerhose)',
    accName: 'Eisengrau (Handschellen, Ketten)',
    materials: [['Haut', '#6e9c40'], ['Faustwickel', '#e8dcc0']],
    signature: 'Zwei geöffnete Eisenschellen mit drei Kettengliedern, die bei jedem Schlag klirren.',
    details: {
      kleidung: 'Boxerhose mit Bund, Faustwickel, nackter Oberkörper mit Narben',
      material: 'Eisen, Leinen, Haut',
      muster: 'Narben, Wickelmuster',
      schnallen: 'Scharniere der Schellen',
      abnutzung: 'aufgeschürfte Knöchel',
      accessoires: 'Boxerhosen-Bund und Faustwickel (Teamzonen)',
    },
    face: 'Wütende Augen unter dicken Brauen, schnaubende Nüstern, Unterbiss mit Hauern, ein eingerissenes Ohr.',
    weapon: 'Fäuste mit Handschellen als Schlagringe.',
    anim: {
      idle: ['schattenboxt, Ketten klirren'],
      walk: ['tänzelnder Boxerschritt'],
      attack: ['Haken-Kombination: links, rechts, Kette schwingt nach'],
      hit: ['schüttelt den Kopf und grinst'],
      spawn: ['bricht mit gestreckten Armen heraus, Ketten fliegen'],
      death: ['fällt vornüber, Ketten rasseln'],
    },
  },
  'bush-goblin': {
    concept: 'Der Busch-Kobold ist ein verschwörerischer Späher in einem Tarnanzug aus Zweigen und Blättern. Er springt aus dem verdächtigen Busch und sticht zu. Er flüstert ständig.',
    unique: 'Der Ganzkörper-Tarnanzug aus Blättern mit Zweigen auf dem Kopf ist eine buschige Silhouette auf Beinen; nur er sieht so aus. Andere Kobolde tragen Westen. Tarnkämpfer anderer Spiele sind Soldaten in Tarnfarbe; dieser ist ein Blätterhaufen mit Augen.',
    silhouette: 'Geduckt; ein Blätterhaufen mit dicken Büscheln am Kopf, unten kurze Beine, vorn ein Dolch.',
    mainName: 'Blattgrün (Tarnanzug)',
    accName: 'Fruchtorange (Beeren, Augen)',
    materials: [['Haut', '#86b84f'], ['Zweige', '#6b4a2a']],
    signature: 'Tarnanzug aus überlappenden Blättern mit Zweigen auf dem Kopf.',
    details: {
      kleidung: 'Blätteranzug, Zweigkrone, Fußwickel',
      material: 'Blätter, Zweige, Rinde',
      muster: 'überlappende Blattschuppen',
      schnallen: 'Rindenbänder',
      abnutzung: 'welke Blätter',
      accessoires: 'Stirnband und Gürtel (Teamzonen), Beeren',
    },
    face: 'Nur zwei leuchtende Augen und ein verschmitztes Grinsen schauen aus den Blättern.',
    weapon: 'Dornendolch aus einem Rosenstiel.',
    anim: {
      idle: ['schaut sich verstohlen um, Blätter rascheln'],
      walk: ['schleicht in Hockstellung'],
      attack: ['Sprung aus der Hocke (Anticipation), Stich'],
      hit: ['Blätter fliegen weg'],
      spawn: ['springt aus dem Busch, Blätterregen'],
      death: ['zerfällt in einen Laubhaufen'],
    },
  },
  'decoy-goblin': {
    concept: 'Der Lockvogel-Kobold steckt in einem albernen Lockenten-Kostüm aus grau bemaltem Holz mit gelbem Holzschnabel. Er landet als Ablenkung im Feld, quakt und sticht frech zu.',
    unique: 'Das Lockenten-Kostüm mit Holzschnabel-Kapuze ist ein Wortspiel auf „Lockvogel“ und gibt eine runde Enten-Silhouette mit Schnabel; nur er hat sie. Lockvögel anderer Spiele sind Kopien des Originals; dieser ist eine verkleidete Ente.',
    silhouette: 'Winzig und rund wie eine Ente, mit Schnabel vorn und Schwanzbürzel hinten; unten Koboldfüße.',
    mainName: 'Lockenten-Grau (Holzkostüm)',
    accName: 'Entenkopf-Grün (Streifen)',
    materials: [['Schnabel', '#f0c030'], ['Haut', '#97c25a']],
    signature: 'Kapuze in Form eines Entenkopfs mit gelbem Holzschnabel und aufgemaltem grünem Halsring.',
    details: {
      kleidung: 'Holzenten-Kostüm mit Schnabelkapuze, Schwimmhäute als Schuhe',
      material: 'bemaltes Holz, Leinen',
      muster: 'aufgemalte Federn',
      schnallen: 'Lederriemen am Kostüm',
      abnutzung: 'abgeplatzte Farbe',
      accessoires: 'Schnabelband und Halstuch (Teamzonen)',
    },
    face: 'Koboldgesicht unter dem Schnabel mit albernem Grinsen und runden Augen.',
    weapon: 'Holzschnabel als Stoßwaffe und kurzer Dolch.',
    anim: {
      idle: ['watschelt auf der Stelle, quakt'],
      walk: ['Watschelgang'],
      attack: ['Schnabel-Kopfstoß, dann Stich'],
      hit: ['Kostüm splittert ein wenig'],
      spawn: ['landet mit Flatterbewegung'],
      death: ['Kostüm fällt auseinander, Federn wirbeln'],
    },
  },
  'goblin-giant': {
    concept: 'Der Koboldriese ist ein tumber, gutmütiger Riesenkobold mit Ohrringen groß wie Fassreifen. Auf dem Rücken trägt er ein Fass als Krähennest, in dem zwei Speerkobolde sitzen und unabhängig werfen. Fällt er, springen sie ab.',
    unique: 'Ein Fass-Krähennest mit zwei Passagieren auf dem Rücken ist eine einzigartige Rücken-Silhouette; die Speerkobolde darin zanken sich. Andere Riesen haben Mütze, Kanone oder Tafel. Riesenkobolde anderer Spiele tragen Rucksäcke; dieser trägt ein Fass mit Fähnchen.',
    silhouette: 'Massig mit grünem Kopf und riesigen Ohren; das Fass ragt über den Kopf, oben zwei kleine Köpfe mit Speeren.',
    mainName: 'Olivgrün (Haut)',
    accName: 'Fassholz-Braun',
    materials: [['Lederhose', '#5a4a3a'], ['Fassreifen', '#7a7a80']],
    signature: 'Ein Fass mit Ausguck-Rand, kleiner Fahnenstange und zwei Speerkobolden darin.',
    details: {
      kleidung: 'Lederhose mit Gürtel, Tragegurte, nackter Bauch',
      material: 'Fassholz, Leder, Eisen',
      muster: 'Fassdauben, Gurtnähte',
      schnallen: 'Eisenreifen, Gurtschnallen',
      abnutzung: 'Flicken am Fass',
      accessoires: 'Krähennest-Fähnchen und Gürtel (Teamzonen), Ohrringe wie Fassreifen',
    },
    face: 'Großes, freundlich-dummes Gesicht mit schiefem Grinsen, Zahnlücken und hängenden Lidern.',
    weapon: 'Fäuste; oben werfen die Speerkobolde.',
    anim: {
      idle: ['die Speerkobolde zanken sich, er schaut nach oben'],
      walk: ['schwerer Gang mit `char.step`, Fass schaukelt'],
      attack: ['schwerer Schwinger mit der Faust (Anticipation weit hinten)'],
      hit: ['Fass wackelt, die Kobolde klammern sich fest'],
      spawn: ['landet, die Kobolde ploppen hoch'],
      death: ['fällt vornüber, die Kobolde springen ab'],
    },
    special: { evo: 'Kobold-Sack-Evo: Ein großer Sack voller strampelnder Kobolde hängt am Gürtel, das Fass ist eisenbeschlagen, dazu ein Kriegsbemalungs-Streifen. Unter halbem Leben wirft er Kobolde aus dem Sack, Strohhalme bilden die Partikelhülle.' },
  },
  'goblin-machine': {
    concept: 'Die Goblin Machine ist ein stampfender Kampfanzug aus Schrott und Kesselblech, den ein jauchzender Kobold aus einer Glaskanzel steuert. Sie schlägt mit einer Kolbenfaust mit Dampfzylinder zu. Ein Raketenwerfer auf der Schulter feuert unabhängig.',
    unique: 'Die übergroße Kolbenfaust mit sichtbarem Dampfzylinder und der kleine Pilot in der Kanzel ergeben eine asymmetrische Mech-Silhouette; nur sie hat einen Piloten im Kopf. Andere Maschinen sind Automaten ohne Fahrer. Kampfmaschinen anderer Spiele sind glatte Roboter; diese ist ein genieteter Schrotthaufen.',
    silhouette: 'Breiter Kesselrumpf auf Stampfbeinen, rechts eine riesige Faust, links ein kleinerer Greifarm; oben Kanzel und Raketenrohr.',
    mainName: 'Rostbraun (Blech)',
    accName: 'Türkis (Kanzelglas, Dampf)',
    materials: [['Pilot-Haut', '#7fae4a'], ['Nieten', '#c8ccd2'], ['Raketen', '#e8b030']],
    signature: 'Eine Kolbenfaust mit Dampfzylinder; beim Schlag schießt sie zischend nach vorn.',
    details: {
      kleidung: 'Pilot mit Lederkappe und Brille in der Glaskanzel',
      material: 'Kesselblech, Nieten, Glas, Gummischläuche',
      muster: 'Nietreihen, Schweißnähte',
      schnallen: 'Klammern, Ventile',
      abnutzung: 'Rostflecken, Beulen',
      accessoires: 'Raketenwimpel und Pilotenhelm (Teamzonen), Auspuffrohr',
    },
    face: 'Der Pilot jauchzt mit weit offenem Mund; die Maschine hat zwei Scheinwerfer als Augen.',
    weapon: 'Kolbenfaust (Nahkampf) und Schulter-Raketenwerfer (Fernkampf).',
    anim: {
      idle: ['Auspuff pufft, der Pilot kurbelt an Hebeln'],
      walk: ['stampfender Gang mit `char.step`, Rumpf schaukelt'],
      attack: ['Kolben zieht zurück (Anticipation), Faust schnellt vor mit Dampfstoß', 'Raketen starten unabhängig'],
      hit: ['Funken, der Pilot duckt sich'],
      spawn: ['landet mit Dampfwolke'],
      death: ['Maschine fällt auseinander, der Pilot springt mit Schirm heraus'],
    },
  },
  goblinstein: {
    concept: 'Goblinstein ist ein größenwahnsinniger Kobold-Doktor im weißen Laborkittel mit dicker Schweißerbrille. Er steuert sein Monster mit einem Fernsteuerkasten samt Blitzantenne und schießt selbst Blitze. Er lacht irre.',
    unique: 'Der Fernsteuerkasten mit Antenne und die Schweißerbrille auf dem weißen Kittel sind einmalig; nur er bildet mit einer zweiten Figur (dem Monster) ein Paar. Verrückte Wissenschaftler anderer Spiele haben wilde Haare und Kolben; dieser hat eine Funkantenne.',
    silhouette: 'Schlank im langen Kittel, Kopf mit großer Brille, die Antenne ragt hoch über den Kopf.',
    mainName: 'Laborweiß (Kittel)',
    accName: 'Blitzviolett',
    materials: [['Haut', '#8fbf6a'], ['Kasten', '#5a5f6b'], ['Brillengläser', '#9ff0ff']],
    signature: 'Ein Fernsteuerkasten mit zwei Hebeln, Knöpfen und einer Teleskopantenne, die beim Blitz leuchtet.',
    details: {
      kleidung: 'Laborkittel mit Rissen, Gummihandschuhe, Schürze, Stiefel',
      material: 'Baumwolle, Gummi, Messing, Glas',
      muster: 'Brandlöcher, Kittelfalten',
      schnallen: 'Kittelknöpfe, Brillenriemen',
      abnutzung: 'verkohlter Ärmel',
      accessoires: 'Armbinde und Brillenband (Teamzonen), Kugelschreiber in der Tasche',
    },
    face: 'Schmales Koboldgesicht mit vergrößerten Augen hinter der Brille, irrem Grinsen und zerzausten Haarbüscheln.',
    weapon: 'Fernsteuerkasten mit Blitzantenne.',
    anim: {
      idle: ['drückt Knöpfe am Kasten, die Antenne funkt'],
      walk: ['eiliger, gebückter Gang'],
      attack: ['reckt die Antenne (Anticipation), Blitz auf das Ziel'],
      hit: ['Brille rutscht'],
      spawn: ['landet, lacht irre'],
      death: ['Kasten explodiert in seinen Händen, Rauch'],
    },
    special: {
      ability: 'Blitzverbindung: Er stemmt den Kasten hoch und dreht beide Hebel (Pose). Event `char.ability.goblinstein` lässt einen Blitzbogen zum Monster springen, der 3,5 s pulsiert.',
      aura: 'Violette Bodenaura mit Funkwellen; `char.release` erzeugt Funken an der Antenne.',
    },
  },
  'goblinstein-monster': {
    concept: 'Das Monster ist Goblinsteins sanfter, genähter Riesenkobold aus Flicken mit ungleich großen Armen. Auf dem Rücken trägt es einen Akku, von dem Kabel zu Kupferklemmen am Hals laufen. Es stapft zu Gebäuden und brummt Wiegenlieder.',
    unique: 'Der Rücken-Akku mit Kabeln zu Halsklemmen und der Flickenkörper mit sichtbaren Nähten sind einmalig. Andere Riesen tragen Kleidung. Monster anderer Werke haben Schrauben im Hals; dieses hat einen Akku auf dem Rücken und Klemmen.',
    silhouette: 'Massig und schief: ein Arm größer als der andere, kleiner Kopf, Akku-Kasten hinten.',
    mainName: 'Grünlich-Grau (Flickenhaut)',
    accName: 'Kupfer (Klemmen, Kabel)',
    materials: [['Akku', '#3a3d44'], ['Nähte', '#2a2a30'], ['Hose', '#3a3a4a']],
    signature: 'Ein Akku mit Kurbel auf dem Rücken, zwei Kabel zu Kupferklemmen am Hals.',
    details: {
      kleidung: 'zerrissene Hose, Hosenträger aus Kabeln',
      material: 'Flickenhaut, Kupfer, Gummi',
      muster: 'Kreuznähte, Flickenränder',
      schnallen: 'Klemmen, Nieten am Akku',
      abnutzung: 'Brandflecken an den Klemmen',
      accessoires: 'Hosenbund und Armbinde (Teamzonen)',
    },
    face: 'Kleines Gesicht mit sanften, ungleichen Augen, einer Naht über der Stirn und einem schüchternen Lächeln.',
    weapon: 'Zwei ungleich große Fäuste: links eine Flickenfaust mit Kreuznähten, rechts eine riesige Pranke mit Kupferring.',
    anim: {
      idle: ['Funken an den Klemmen, wiegt den Kopf'],
      walk: ['schwankender Gang mit `char.step`'],
      attack: ['beide Arme hoch (Anticipation), schwerfälliger Doppelschlag'],
      hit: ['zuckt, Funken'],
      spawn: ['erwacht: Funken, er öffnet die Augen'],
      death: ['Akku geht aus, er sackt zusammen'],
    },
  },
  'goblin-hut': {
    concept: 'Die Koboldhütte ist eine schiefe Flickwerk-Hütte aus Brettern und Tüchern mit einem krummen Kürbis-Schornstein. Aus dem Türvorhang springen Speerkobolde, sobald Gegner nahe sind.',
    unique: 'Der Kürbis als Schornstein und die Flickwerk-Wände sind einmalig; die Barbarenhütte ist ein Soden-Langhaus. Koboldhütten anderer Spiele sind Holzhütten mit Speeren; diese ist ein Flickwerk mit Kürbis.',
    silhouette: 'Schiefes Haus mit hängendem Dach, oben ein runder Kürbis mit Rauchloch, vorn ein Vorhang.',
    mainName: 'Lehmbraun (Bretter)',
    accName: 'Kürbisorange',
    materials: [['Tücher', '#c8b07a'], ['Stroh', '#d8c070']],
    signature: 'Ein ausgehöhlter Kürbis als Schornstein, aus dessen Gesicht Rauch quillt.',
    details: {
      kleidung: 'Bretterwände, Stoffflicken, Strohdach',
      material: 'Holz, Stoff, Kürbis, Stroh',
      muster: 'Flickennähte, Bretterfugen',
      schnallen: 'Nägel, Schnüre',
      abnutzung: 'Löcher im Dach',
      accessoires: 'Türvorhang und Dachfahne (Teamzonen), Speere an der Wand',
    },
    face: 'Kein Gesicht; der Kürbis hat ein geschnitztes Grinsen.',
    weapon: 'Keine; Speerkobolde kommen heraus.',
    anim: {
      idle: ['Schornstein raucht, Vorhang wackelt'],
      walk: ['keine Fortbewegung'],
      attack: ['`char.spawnUnit`: Vorhang fliegt auf, ein Speerkobold springt heraus'],
      hit: ['Bretter klappern'],
      spawn: ['Hütte fällt zusammengeklappt herunter und richtet sich auf'],
      death: ['Hütte bricht zusammen, der Kürbis rollt'],
    },
  },
  'goblin-cage': {
    concept: 'Der Koboldkäfig ist ein vergoldeter Vogelkäfig auf einem Sockel, in dem ein Kobold-Raufbold tobt. Er dient als Köder. Wird er zerstört, stürmt der Raufbold heraus.',
    unique: 'Ein verzierter, vergoldeter Vogelkäfig mit gefangenem Kobold ist eine einmalige Bauwerk-Form; andere Spawner sind Hütten und Grabmale. Käfige anderer Spiele sind Holzkäfige; dieser ist ein goldener Vogelkäfig.',
    silhouette: 'Glockenförmiger Käfig mit Ring oben, darin eine Figur hinter Stäben, darunter ein runder Sockel.',
    mainName: 'Vergoldet',
    accName: 'Eisendunkel (Sockel, Schloss)',
    materials: [['Raufbold-Haut', '#6e9c40'], ['Sockelstein', '#8a8478']],
    signature: 'Ein goldener Vogelkäfig mit Kuppel und Ring, innen der rüttelnde Raufbold.',
    details: {
      kleidung: 'Käfig mit Zierranken, Kuppel, Sockel',
      material: 'vergoldetes Eisen, Stein',
      muster: 'Rankenornament, Stäbe',
      schnallen: 'riesiges Vorhängeschloss',
      abnutzung: 'verbogene Stäbe',
      accessoires: 'Käfigschild und Wimpel (Teamzonen)',
    },
    face: 'Kein eigenes Gesicht; der Raufbold darin zeigt Wut.',
    weapon: 'Keine; der Raufbold kommt heraus.',
    anim: {
      idle: ['der Raufbold rüttelt an den Stäben, der Käfig wackelt'],
      walk: ['keine Fortbewegung'],
      attack: ['Evo: Stäbe öffnen sich und ziehen einen Gegner hinein'],
      hit: ['Käfig klingelt, Gold blättert ab'],
      spawn: ['Käfig landet mit Glockenklang'],
      death: ['Käfig platzt auf, der Raufbold springt heraus'],
    },
    special: { evo: 'Fang-Evo: Die Stäbe werden zu greifenden Ranken, der Käfig ist größer mit Dornenkuppel und grünem Leuchten. Grüne Ranken-Funken bilden die Partikelhülle; beim Fang schnappt eine Ranke zu.' },
  },
  'goblin-drill': {
    concept: 'Der Koboldbohrer ist ein Bohrturm aus Kupfer mit einer Riesenschraube, die sich überall durch den Boden gräbt. Ein Kobold-Fahrer sitzt oben, und aus einer Luke hüpfen ständig Kobolde.',
    unique: 'Riesenschraube plus Bohrturm mit Fahrersitz ist eine einmalige Bauwerk-Form; die Erdbrocken beim Auftauchen sind sein Effekt. Bohrer anderer Spiele sind graue Maschinen; dieser ist ein kupferner Turm mit Fahrer.',
    silhouette: 'Spitzer Kegel (Schraube) mit Kupferturm darüber, Fahrer oben, Luke an der Seite.',
    mainName: 'Kupfer-Rost (Turm)',
    accName: 'Goldgelb (Schraube, Lampen)',
    materials: [['Schraube (Stahl)', '#a8b0ba'], ['Erde', '#6b4a32']],
    signature: 'Riesige Schraubenspitze mit Gewindegängen und ein Kobold-Fahrer mit Helm.',
    details: {
      kleidung: 'Bohrturm mit Kabine, Kurbel, Lampen',
      material: 'Kupfer, Stahl, Glas',
      muster: 'Gewinde, Nieten',
      schnallen: 'Lukenriegel',
      abnutzung: 'Erdreste, Kratzer',
      accessoires: 'Turmfahne und Fahrerhelm (Teamzonen)',
    },
    face: 'Der Fahrer hat eine Brille und schreit vor Freude.',
    weapon: 'Keine; Kobolde kommen heraus.',
    anim: {
      idle: ['Schraube dreht, Erdbrocken fliegen'],
      walk: ['keine Fortbewegung'],
      attack: ['`char.spawnUnit`: Luke springt auf, ein Kobold hüpft heraus'],
      hit: ['Rattert, Funken'],
      spawn: ['bohrt sich mit Erdfontäne aus dem Boden'],
      death: ['Schraube bricht, der Turm kippt'],
    },
    special: { evo: 'Wander-Evo: Eine Doppelschraube mit leuchtenden Gewindegängen, der Fahrer bekommt eine Grubenlampe und eine Karte. Erdfunken bilden die Partikelhülle; beim Abtauchen und Auftauchen gibt es eigene Wirbel.' },
  },
};
