// Design-Briefs: Krone (Ritter, Schützinnen, Prinzen, Rekruten, Türme)
export default {
  knight: {
    concept: 'Der Ritter ist ein sturer, pflichtbewusster Schildträger aus der Burgwache, der jeden Angriff mit seinem Zinnenschild abfängt und dann kurz und trocken zurückschlägt. Er ist günstig, robust und immer zuerst da. Er wirkt wie ein kleiner, wandelnder Burgturm.',
    unique: 'Kein anderer Ritter im Spiel trägt einen Schild in Form eines Burgturms mit Zinnen und Schießscharte. Golden Knight trägt Sonnenkranz und Rapier, Megaritter einen Glockenhelm, Guardienne eine Tür. Gängige Fantasy-Ritter setzen auf Topfhelm, Kreuzschild und Schnurrbart; dieser hat einen Nasalhelm mit Wimpel, ein Pflaster quer über der Nase und den Turm-Schild, der fast seine ganze Front verdeckt.',
    silhouette: 'Breites Trapez: Rechts ragt der hohe Zinnenschild über die Schulter hinaus, links steht die kurze Breitklinge schräg nach oben. Die Beine sind kurz und der Stand breit, oben sitzt der Nasalhelm mit kleinem Wimpel.',
    mainName: 'Zinn (Helm, Schulterplatten, Beinschienen)',
    accName: 'Sattelleder (Gürtel, Riemen, Stiefel)',
    materials: [['Wams (Leinen)', '#d9cdb4'], ['Schildstein', '#b9b2a4']],
    signature: 'Der Schild ist ein Mauerstück mit drei Zinnen, schwarzer Schießscharte und eingesetztem Teamfeld; in der Mitte sitzt das Teamsymbol.',
    details: {
      kleidung: 'Nasalhelm mit Kinnriemen, gepolstertes Leinenwams unter einem Zinn-Brustpanzer mit zwei Plattenreihen, Schulterplatten, Beinschienen, kurze Stulpenstiefel',
      material: 'Zinn mit Hammerschlag-Glanz, Leinen, Sattelleder, gemauerter Stein am Schild',
      muster: 'Steinfugen auf dem Schild, Steppnähte am Wams, Doppelnaht am Gürtel',
      schnallen: 'große quadratische Gürtelschnalle, Nieten an den Schulterplatten, eingeritzter Turm auf dem Helm-Nasal',
      abnutzung: 'Kerben in den Zinnen, abgeschlagene Ecke am Schild, Kratzer am Brustpanzer',
      accessoires: 'Helmwimpel (Teamzone), Pflaster auf der Nase, kleiner Schlüsselbund am Gürtel',
    },
    face: 'Kantiges Gesicht mit breitem Kinn, buschigen geraden Brauen, kleinen entschlossenen Augen und schmalem Mund; das Pflaster sitzt quer über der Nase. Im Angriff zieht er die Brauen zusammen und beißt die Zähne aufeinander, getroffen kneift er ein Auge zu.',
    weapon: 'Kurze, breite Klinge mit dreieckiger Spitze und quaderförmigem Knauf, eher Schlachtermesser als Langschwert; die Parierstange ist ein schlichter Eisenbalken.',
    anim: {
      idle: ['Schild ruht auf dem Boden, er atmet tief', 'alle paar Sekunden zwei Klopfer mit dem Knauf an den Schild', 'späht über die Zinnen, der Wimpel schwingt nach'],
      walk: ['schwerer, gleichmäßiger Marsch', 'Schild bleibt vorn, wippt mit jedem Schritt', 'Wimpel und Gürtelenden schwingen nach'],
      attack: ['Anticipation: Schild hoch, Klinge nach hinten', 'Schildstoß nach vorn, gleich danach kurzer Hieb von oben hinter dem Schild hervor', 'Follow-through: Klinge federt nach, Schild zurück vor den Körper'],
      hit: ['Schild ruckt zurück, Körper staucht sich zusammen', 'ein Auge zugekniffen'],
      spawn: ['fällt mit dem Schild voran und landet mit Squash', 'stellt den Schild mit einem dumpfen Ruck auf'],
      death: ['kippt nach hinten, der Schild fällt flach auf ihn', 'Helm rollt zur Seite, dann löst er sich in Staub auf'],
    },
    special: {
      evo: 'Steinwacht-Evo: Der Schild wird zu einem höheren Turm mit leuchtenden Fenstern, dazu kommen Steinplatten auf Schultern und Brust mit hellblauen Leuchtfugen. Die Fugen glühen stärker, solange er nicht angreift (60 % weniger Schaden), und ein Staubschleier dient als Partikelhülle.',
    },
  },
  archers: {
    concept: 'Die Bogenschützen sind zwei sportliche Schwestern aus dem Schützenverein, die ihre Pfeile in einem radförmigen Köcher tragen, der auf Hüfthöhe wie ein Pfauenrad nach hinten auffächert. Sie treffen Boden und Luft aus mittlerer Entfernung, flink und gut gelaunt.',
    unique: 'Der Fächerköcher bildet auf Hüfthöhe ein Rad aus Pfeilen, das wie ein Pfauenschwanz nach hinten absteht; keine andere Figur hat diese Silhouette. Bewusst sitzt er tief und zeigt Schäfte mit Nocken, damit er nicht wie Kopfschmuck wirkt. Andere Schützinnen im Spiel haben Mondsichel-Armbrust, Harfenbogen oder Fernrohr-Bogen. Übliche Bogenschützinnen tragen Kapuze und Umhang; diese tragen ein ockerfarbenes Sportwams mit langem Schal und Kurzbogen.',
    silhouette: 'Schlank und aufrecht; hinter der Hüfte fächern sieben Pfeile um eine Holznabe nach hinten auf, vorn der kurze Recurve-Bogen; der lange Schal flattert seitlich.',
    mainName: 'Ocker (Wams, Hose)',
    accName: 'Petrol (Bogen, Stiefel, Fächerkranz)',
    materials: [['Federn', '#f4ead2'], ['Haar (Zopf)', '#5a3424'], ['Haar (Dutt)', '#2e2230']],
    signature: 'Die Pfeile stecken mit der Spitze in einer Holznabe mit Messingkern und fächern mit bunten Nocken und Befiederung nach hinten auf.',
    details: {
      kleidung: 'kurzes Wams mit Gürtel, enge Hose, Stulpenstiefel, Armschutz am Bogenarm, Halbhandschuhe',
      material: 'Wolle, Leder, polierter Holzbogen, Federn an den Pfeilen',
      muster: 'Rautenstich am Wamssaum, Wicklung am Bogengriff',
      schnallen: 'runde Messingschnalle am Gürtel, Nieten am Fächerkranz',
      abnutzung: 'aufgeschürfte Knie, ausgefranste Schalenden',
      accessoires: 'langer Schal (Teamzone), Köcherband (Teamzone), Haarband',
    },
    face: 'Runde Gesichter mit großen, mandelförmigen Augen, Stupsnase und frechem Grinsen; beim Zielen kneift eine ein Auge zu, die andere streckt die Zunge in den Mundwinkel.',
    weapon: 'Kurzer Recurve-Bogen mit nach außen gebogenen Spitzen und dicker Griffwicklung; Pfeile mit dreieckigen Federn in Creme.',
    anim: {
      idle: ['wippen locker auf den Zehen', 'zupfen an der Sehne und lauschen dem Ton', 'der Pfeilfächer an der Hüfte zittert leicht'],
      walk: ['leichte, federnde Schritte', 'Schal weht hinterher, der Fächer klappert'],
      attack: ['greift nach hinten in den Fächer an der Hüfte (Anticipation)', 'spannt weit, der Körper streckt sich (Stretch)', 'Schuss, dann federt der Körper nach hinten nach'],
      hit: ['zuckt zusammen, Fächer klappt kurz zu'],
      spawn: ['landet auf einem Bein mit Hüpfer', 'Fächer klappt auf'],
      death: ['setzt sich auf den Hosenboden, die Pfeile fallen aus dem Fächer', 'verblasst'],
    },
    special: {
      evo: 'Kraftschuss-Evo: Ein Kranz aus Messing-Pfeilspitzen glüht um den Fächer, dazu kommen Schulterschützer aus Leder und eine leuchtende Pfeilspitze bei Fernschüssen. Die Partikelhülle besteht aus goldenen Federflocken.',
      variants: 'Schwester A mit langem Zopf, Schwester B mit Dutt und Haarnadel; Farbton ±6°, Größe ±5 %',
    },
  },
  musketeer: {
    concept: 'Die Musketierin ist eine ruhige Präzisionsschützin in einem ockerolivfarbenen Reitrock mit Spitzenkragen. Vor jedem Schuss stellt sie ihre lange Muskete auf eine Stützgabel. Sie ist zuverlässig, unaufgeregt und trifft aus großer Entfernung.',
    unique: 'Die Musketengabel als Stütze ist ein Gerät, das sonst niemand trägt, und gibt ihr beim Schießen eine unverwechselbare Dreiecks-Silhouette. Die drei Musketierinnen tragen Dreispitze und kurze Karabiner, die Prinzessin einen Harfenbogen. Klassische Musketiere tragen Kreuzumhang und Degen; sie trägt stattdessen einen Kavaliershut mit Teamfeder, einen gestärkten Spitzenkragen und eine Muskete, die länger ist als sie selbst.',
    silhouette: 'Schlank und hoch; die Muskete bildet eine lange Waagerechte bzw. Diagonale, die Gabel steht senkrecht davor. Oben sitzt der breite Hut mit hoch aufragender Feder.',
    mainName: 'Ocker-Oliv (Reitrock)',
    accName: 'Spitzenweiß (Kragen, Manschetten)',
    materials: [['Musketenholz', '#7a4a2a'], ['Eisen', '#5f6672'], ['Haar', '#2a1c1c']],
    signature: 'Die Gabel ist eine zweizinkige Holzstütze mit Messingkappe, die beim Laufen am Rücken hängt und zum Schießen aufgestellt wird.',
    details: {
      kleidung: 'Kavaliershut mit breiter Krempe, Reitrock mit langen Schößen, gestärkter Spitzenkragen, Stulpenhandschuhe, hohe Reitstiefel',
      material: 'Wollfilz, Spitze, Leder, Nussholz, Eisen',
      muster: 'Paspel an den Schößen, Spitzenzacken am Kragen',
      schnallen: 'Messingknöpfe in zwei Reihen, Schulterriemen mit Pulverflaschen',
      abnutzung: 'Rußspuren an der Mündung, Pulverflecken am Handschuh',
      accessoires: 'Hutfeder (Teamzone), Schärpe (Teamzone), drei Pulverflaschen am Bandelier',
    },
    face: 'Schmales Gesicht mit halb gesenkten Lidern, einer hochgezogenen Augenbraue und feinem Lächeln; ein dunkler Zopf hängt unter dem Hut hervor. Beim Schuss schließt sie ein Auge, getroffen hebt sie empört beide Brauen.',
    weapon: 'Lange Luntenschloss-Muskete mit achteckigem Lauf, Kolben mit Messingplatte und gebogenem Abzugsbügel; die Gabel steht vorn.',
    anim: {
      idle: ['steht mit aufgestellter Gabel, eine Hand auf der Muskete', 'pustet über die Mündung', 'Feder wippt im Wind'],
      walk: ['ruhiger, aufrechter Schritt', 'Muskete über der Schulter, Gabel schwingt am Rücken'],
      attack: ['Gabel aufstellen, Muskete auflegen (Anticipation)', 'Zielen mit geschlossenem Auge, Schuss mit Rauchring', 'Rückstoß drückt die Schulter zurück, die Feder federt nach'],
      hit: ['Hut verrutscht, sie hält ihn fest'],
      spawn: ['landet in Hockstellung, stellt sofort die Gabel auf'],
      death: ['sinkt auf ein Knie, die Muskete kippt weg', 'der Hut rollt davon'],
    },
    special: {
      evo: 'Scharfschützen-Evo: Ein Messing-Zielfernrohr kommt auf den Lauf, der Rock wird zum Gehrock mit Goldlitzen. Drei leuchtende Patronen am Hutband zeigen die Scharfschüsse an, die Mündung glüht hellblau, und Funken kreisen um die Gabel.',
    },
  },
  'three-musketeers': {
    concept: 'Die drei Musketierinnen sind ein eingespieltes Schwestern-Trio in petrolfarbenen Waffenröcken, mit Dreispitzen und großen Kokarden. Sie schießen mit kurzen Karabinern und wechseln aus der Nähe zum Bajonett. Gemeinsam wirken sie wie eine kleine Parade.',
    unique: 'Die übergroßen Kokarden am Dreispitz sind ihr Erkennungszeichen, und die aufgepflanzten Bajonette unterscheiden sie von der einzelnen Musketierin mit Gabel und Kavaliershut. Andere Dreispitz-Figuren gibt es im Spiel nicht. Sie tragen keine Kreuzumhänge und keine Degen, sondern Karabiner mit Klappbajonett.',
    silhouette: 'Drei schlanke Figuren mit dreieckigen Hutkanten; die kurzen Karabiner zeigen schräg nach oben, das Bajonett bildet eine Spitze. Jede hat eine eigene Frisur als Kontur hinter dem Kopf.',
    mainName: 'Petrol (Waffenrock)',
    accName: 'Creme (Westen, Hutlitze)',
    materials: [['Karabinerholz', '#6b4128'], ['Messing', '#c9a24a']],
    signature: 'Jede Kokarde ist eine gefaltete Rosette in Teamfarbe mit Metallknopf, fast so groß wie der Kopf.',
    details: {
      kleidung: 'Dreispitz mit Litzenrand, Waffenrock mit umgeschlagenen Ärmeln, cremefarbene Weste, Kniebundhose, Gamaschen',
      material: 'Filz, Wolle, Messing, Nussholz',
      muster: 'Litzen in Creme, Knopfleisten, Faltenrosetten',
      schnallen: 'Gamaschenknöpfe, Messingschnallen an den Patronentaschen',
      abnutzung: 'eingedellter Hutrand, Pulverflecken',
      accessoires: 'Kokarde und Schärpe (Teamzonen), Patronentaschen, Klappbajonett',
    },
    face: 'Drei Schwestergesichter mit gleichem verschmitztem Grinsen und runden Augen. Die Unterschiede liegen in Augenbrauen (gerade, gebogen, buschig) und Frisur.',
    weapon: 'Kurzer Karabiner mit trompetenförmiger Mündung und Klappbajonett unter dem Lauf; das Bajonett springt beim Nahkampf vor.',
    anim: {
      idle: ['drehen den Karabiner wie einen Taktstock', 'tauschen Blicke, eine richtet ihre Kokarde'],
      walk: ['Gleichschritt mit leichtem Hüpfer', 'Karabiner geschultert'],
      attack: ['Anlegen an die Wange, kurzer Schuss mit Mündungswolke', 'aus der Nähe: Bajonett klappt vor, Ausfallschritt mit Stich'],
      hit: ['Dreispitz rutscht in die Stirn'],
      spawn: ['landen nacheinander, salutieren kurz'],
      death: ['fallen zur Seite, der Dreispitz bleibt stehen und verblasst'],
    },
    special: { variants: 'A mit Zopf und geraden Brauen, B mit Locken und gebogenen Brauen, C mit Kurzhaar und buschigen Brauen' },
  },
  'royal-recruits': {
    concept: 'Die Königsrekruten sind sechs junge Freiwillige mit viel zu großen Schüsselhelmen, die ihnen ständig über die Augen rutschen. Mit Rundschild und Pike stehen sie tapfer in einer breiten Reihe. Sie sind nervös, aber entschlossen, so etwas wie eine Schulklasse in Rüstung.',
    unique: 'Der übergroße, rutschende Schüsselhelm macht die Kopf-Silhouette breiter als die Schultern; das hat sonst niemand. Der Ritter trägt einen Nasalhelm und einen Turmschild, die Wächter sind Skelette mit Sargdeckeln. Rekruten anderer Spiele sind meist Mini-Ritter; diese tragen salbeigraue Kittel, einen Rundschild und Holzpiken mit Wimpelknoten.',
    silhouette: 'Breiter, flacher Halbkreis-Helm über kleinem Körper, vorn der Rundschild, die Pike steht senkrecht hoch über den Kopf hinaus.',
    mainName: 'Salbeigrau (Kittel)',
    accName: 'Holzbraun (Pike, Schildrand)',
    materials: [['Helm (Messing)', '#c8a046'], ['Leinen', '#e6dcc4']],
    signature: 'Der Messing-Schüsselhelm ist doppelt so breit wie der Kopf und hat innen ein sichtbares Polster; er wackelt bei jedem Schritt.',
    details: {
      kleidung: 'Schüsselhelm, Gambeson-Kittel mit Gürtel, Wickelgamaschen, Holzschuhe',
      material: 'Messing, Leinen, Holz, Rohleder',
      muster: 'Rautensteppung am Kittel',
      schnallen: 'Schildbuckel aus Messing, Riemen am Helm',
      abnutzung: 'Dellen im Helm, Kratzer am Schildrand',
      accessoires: 'Rundschild-Feld und Halstuch (Teamzonen), Brotbeutel',
    },
    face: 'Junge Gesichter mit großen Augen unter dem Helmrand und offenem Mund. Je nach Variante gibt es Sommersprossen, eine Zahnlücke oder eine runde Brille; im Angriff schreien sie mit zugekniffenen Augen.',
    weapon: 'Lange Holzpike mit blattförmiger Eisenspitze und einem Wimpelknoten unter der Spitze; der Rundschild hat einen großen Messingbuckel.',
    anim: {
      idle: ['schieben den Helm hoch, er rutscht wieder herunter', 'treten von einem Fuß auf den anderen'],
      walk: ['etwas ungelenker Marsch, Helm wackelt', 'Pike schwankt'],
      attack: ['Pike zurück (Anticipation), Stoß über den Schildrand', 'Helm klappert nach'],
      hit: ['Helm rutscht ganz über die Augen'],
      spawn: ['landen mit Squash, Helm hüpft hoch und fällt wieder'],
      death: ['fallen um, der Helm dreht sich wie ein Kreisel und verblasst'],
    },
    special: {
      evo: 'Sturm-Evo: Die Helme bekommen einen Kamm und Wangenklappen, Eisenringe fassen die Schilde ein. Ist der Schild zerstört, leuchten Sturmstreifen an Kittel und Pike, und Staubfunken hängen an den Füßen.',
      variants: 'Sommersprossen, Zahnlücke, Brille; Farbton ±6°, Größe ±5 %',
    },
  },
  prince: {
    concept: 'Der Prinz ist ein edler, ungeduldiger Turnierreiter mit einem froschgrünen Stechhelm, der wie ein Froschmaul aussieht und eine kleine Krone obenauf trägt. Er reitet einen Apfelschimmel und stürmt mit gesenkter, gestreifter Lanze los. Er ist halb Ritter, halb Märchen-Froschkönig.',
    unique: 'Der Froschmaul-Stechhelm mit Krönchen und das Frühlingsgrün machen ihn einmalig. Der dunkle Prinz reitet einen Waran, die Widderreiterin einen Widder, der Schweinereiter ein Schwein. Übliche Turnierprinzen tragen Federbusch und Goldrüstung; dieser hat einen grünen Frosch-Helm und eine spiralgestreifte Lanze.',
    silhouette: 'Pferd im Halbprofil mit hohem Hals, darüber der Reiter mit runder Helmkuppel und breitem Maulspalt; die Lanze ragt weit nach vorn über den Pferdekopf hinaus.',
    mainName: 'Froschgrün (Helm, Waffenrock)',
    accName: 'Gold (Krönchen, Beschläge)',
    materials: [['Apfelschimmel', '#d6d8d2'], ['Schimmel-Flecken', '#9ea29a'], ['Lanzenstreifen', '#f4efe2']],
    signature: 'Der Stechhelm hat die Form eines Froschkopfs mit breitem Sehschlitz als Maul und zwei Augenbuckeln; oben sitzt ein winziges Goldkrönchen.',
    details: {
      kleidung: 'Froschmaul-Stechhelm, grüner Waffenrock über einem Kettenhemd, Plattenhandschuhe, Sporenstiefel',
      material: 'grün lackierter Stahl, Kettengeflecht, Samt, Gold',
      muster: 'Seerosen-Stickerei am Waffenrock, Kettenringe',
      schnallen: 'Goldbeschläge an Sattel und Zaumzeug',
      abnutzung: 'Lanzenkerben, Lackabplatzer am Helm',
      accessoires: 'Schabracke und Lanzenwimpel (Teamzonen), Glöckchen am Zaumzeug',
    },
    face: 'Hinter dem Sehschlitz zwei funkelnde Augen; das „Gesicht“ ist der Froschhelm mit großen Augenbuckeln. Der Ausdruck kommt über die Augen (verengt im Angriff, kugelrund getroffen) und über die Pferdemimik.',
    weapon: 'Turnierlanze mit Spiralstreifen in Creme und Grün, Brechscheibe am Griff und stumpfer Krönchenspitze.',
    anim: {
      idle: ['Pferd scharrt und schüttelt die Mähne', 'Prinz richtet die Lanze aus und zupft am Krönchen'],
      walk: ['Trab mit wippender Lanze, Schabracke schwingt'],
      attack: ['Lanze nach hinten (Anticipation), Stoß im Vorbeireiten', 'Pferd bäumt sich leicht auf'],
      hit: ['Pferd tänzelt zur Seite, Helmklappe klappert'],
      spawn: ['galoppiert aus dem Fall heraus an, Hufe schlagen auf'],
      death: ['Pferd knickt ein, der Prinz rollt ab', 'das Krönchen kullert und verblasst'],
    },
    special: { extra: '**Ansturm (`charge`):** Lanze gesenkt, Pferd im gestreckten Galopp, Schabracke flach im Wind; beim Flusssprung zieht das Pferd die Hufe an.' },
  },
  princess: {
    concept: 'Die Prinzessin ist eine verträumte Musikerin im pfirsichfarbenen Glockenkleid. Sie schießt mit einem Harfenbogen, dessen Saiten beim Spannen zu brennenden Pfeilen werden. Sie trifft aus riesiger Entfernung und summt dabei.',
    unique: 'Der Harfenbogen ist eine Mischung aus Lyra und Bogen, die nur sie trägt; zusammen mit dem weiten Glockenkleid ergibt das eine Dreieck-Silhouette mit geschwungenem Rahmen daneben. Andere Schützinnen haben Armbrust, Fächerköcher oder Muskete. Märchenprinzessinnen tragen sonst oft Rosa mit Langbogen; diese trägt Pfirsich und Minze und spielt einen Harfenbogen.',
    silhouette: 'Breites Glockendreieck unten, kleiner Oberkörper, Kopf mit Diadem; der Harfenbogen bildet seitlich einen hohen geschwungenen Rahmen mit Saiten.',
    mainName: 'Pfirsich (Kleid)',
    accName: 'Minze (Schleifen, Saiten-Glimmen)',
    materials: [['Gold (Harfenrahmen)', '#e2b84a'], ['Haar', '#f2d27a']],
    signature: 'Der Bogen ist ein vergoldeter Harfenrahmen mit fünf Saiten; die mittlere glüht beim Spannen und fliegt als brennender Pfeil davon.',
    details: {
      kleidung: 'Glockenkleid mit Puffärmeln, Mieder mit Schnürung, Diadem, Schnallenschuhe',
      material: 'Seide, Brokat, Gold',
      muster: 'Schuppenrüschen am Saum, Blütenstickerei am Mieder',
      schnallen: 'Schnürung am Mieder, Goldspangen an den Schuhen',
      abnutzung: 'Grasflecken am Saum',
      accessoires: 'Schleife am Kleid und Diadem-Stein (Teamzonen), Notenblatt-Täschchen',
    },
    face: 'Weiches Gesicht mit langen Wimpern, geschlossenen Lidern beim Summen und rundem Mund; beim Zielen öffnet sie ein Auge weit. Die Haare sind zu zwei Schnecken gedreht.',
    weapon: 'Harfenbogen: geschwungener Goldrahmen in Lyraform mit Saiten in Minze und einem Griff aus Perlmutt.',
    anim: {
      idle: ['zupft eine Saite und lauscht', 'Kleid schwingt leicht hin und her'],
      walk: ['trippelt, das Kleid wogt'],
      attack: ['zieht die mittlere Saite weit nach hinten (Anticipation), die Saite glüht', 'lässt los, ein brennender Pfeil fliegt im hohen Bogen, die Saiten schwingen nach'],
      hit: ['Kleid bauscht sich, sie hält das Diadem fest'],
      spawn: ['landet wie ein Fallschirm mit gebauschtem Kleid'],
      death: ['sinkt elegant zusammen, das Kleid fällt wie eine Glocke', 'Notenblätter wirbeln auf'],
    },
    special: { evo: 'Frost-Evo: Die Saiten werden eisblau, ein Kristall-Diadem und Pelzbesatz am Kleid kommen hinzu. Schneeflocken bilden die Partikelhülle, beim verlangsamenden Schuss leuchtet der Rahmen kalt.' },
  },
  'golden-knight': {
    concept: 'Der Goldene Ritter ist ein eitler Sonnenritter in polierter Goldrüstung mit einem Strahlenkranz als Helmzier. Er ficht mit einem schlanken Rapier und springt mit seiner Fähigkeit wie ein Lichtstrahl von Gegner zu Gegner. Er posiert mehr, als er müsste, und strahlt dabei buchstäblich.',
    unique: 'Der Strahlenkranz hinter dem Kopf ist eine Sonnenscheibe aus spitzen Goldstrahlen; keine andere Figur hat ihn. Der Ritter trägt den Zinnenschild, Megaritter einen Glockenhelm. Goldene Ritter tragen sonst meist schwere Langschwerter; dieser ist schlank, ficht elegant mit dem Rapier und trägt einen cremefarbenen Umhang mit Sonnensaum.',
    silhouette: 'Schlank und gerade mit leichtem Hohlkreuz; hinter dem Kopf ein Kreis aus Strahlen, das Rapier eine feine lange Linie, der Umhang fällt in Falten.',
    mainName: 'Polier-Gold (Rüstung)',
    accName: 'Creme (Umhang, Rapierkorb)',
    materials: [['Haar', '#f3df90'], ['Stahl (Klinge)', '#dfe6ee']],
    signature: 'Zwölf goldene Strahlen an einem Reif hinter dem Helm, abwechselnd lang und kurz; bei der Fähigkeit glühen sie hell.',
    details: {
      kleidung: 'offener Helm mit Strahlenkranz, Goldbrustpanzer mit Sonnengravur, Schulterflügel, Kettenrock, Stiefel mit Goldkappen',
      material: 'poliertes Gold, Seide, Stahl',
      muster: 'Sonnengravur, Strahlen-Ornament am Umhangsaum',
      schnallen: 'Sonnenbrosche am Umhang, Goldnieten',
      abnutzung: 'keine (er poliert ständig)',
      accessoires: 'Umhang und Brustemblem (Teamzonen), Polierlappen am Gürtel',
    },
    face: 'Markantes Kinn mit Grübchen, strahlend weißes Lächeln, wellige Strähne in der Stirn; die Augen halb geschlossen wie bei einem Selbstbewunderer. Im Angriff ist er hochkonzentriert.',
    weapon: 'Schlankes Rapier mit kugeligem Korbgefäß in Sonnenform und langer feiner Klinge.',
    anim: {
      idle: ['poliert die Klinge mit dem Lappen', 'pustet sich eine Strähne aus dem Gesicht', 'Strahlen funkeln nacheinander'],
      walk: ['stolzer Schritt mit geradem Rücken, Umhang schwingt'],
      attack: ['Fechtstellung (Anticipation), schneller Ausfall mit Stich', 'Rückzug in die Grundstellung, Klinge zittert nach'],
      hit: ['empörter Ruck, Strähne fällt ins Gesicht'],
      spawn: ['landet in Pose, Strahlen blitzen auf'],
      death: ['fällt theatralisch auf ein Knie und dann um', 'Strahlen erlöschen einzeln'],
    },
    special: {
      ability: 'Schnellsprung: Er duckt sich in Fechtstellung (Pose), die Strahlen glühen, dann wird er zu einem goldenen Lichtschemen, der von Ziel zu Ziel springt. Event `char.ability.golden-knight` liefert Lichtstrahlen-Nachbilder.',
      aura: 'Goldene Bodenaura mit rotierenden Strahlen; `char.windup` blitzt an der Rapierspitze.',
    },
  },
  'archer-queen': {
    concept: 'Die Bogenschützen-Königin ist eine kühle, elegante Herrscherin in Smaragd und Gold mit steifer Spitzenkrause und einer Armbrust in Form einer Mondsichel. Mit ihrer Fähigkeit hüllt sie sich in die Schleppe ihres Umhangs, wird unsichtbar und schießt doppelt so schnell.',
    unique: 'Die Mondsichel-Armbrust (Bogenarme als Sichel, Schaft wie ein Szepter) und die bis über die Ohren reichende Spitzenkrause gibt es nur bei ihr. Andere Schützinnen haben Fächerköcher, Muskete oder Harfenbogen. Bekannte Bogenköniginnen tragen Langbogen und Tiara mit buntem Haar; diese trägt eine Hochsteckfrisur mit Mondnadel und schießt mit einer Sichel-Armbrust.',
    silhouette: 'Hoch und schmal; oben die hohe Frisur mit Mondnadel und die Krause wie ein Fächer um den Hals, unten eine lange Schleppe, vorn die Armbrust mit sichelförmigem Bogen.',
    mainName: 'Smaragd (Kleid, Umhang)',
    accName: 'Gold (Sichel, Krone, Stickerei)',
    materials: [['Spitze', '#f6f0e4'], ['Haar', '#3a2236'], ['Mondsilber', '#dfe6f2']],
    signature: 'Die Bogenarme bilden eine Mondsichel aus Gold mit Silberkante; der Schaft endet in einem Kronen-Knauf.',
    details: {
      kleidung: 'langes Kleid mit Schleppe, enges Mieder, Spitzenkrause, Halbhandschuhe, Umhang mit Schleppe',
      material: 'Samt, Spitze, Gold, Mondsilber',
      muster: 'Mondphasen-Stickerei am Saum, Spitzenmuster an der Krause',
      schnallen: 'Mondbrosche am Umhang, Goldknöpfe am Mieder',
      abnutzung: 'keine sichtbare, königlich gepflegt',
      accessoires: 'Schleppe des Umhangs und Kronenjuwel (Teamzonen), Mondnadel im Haar',
    },
    face: 'Schmales Gesicht mit hohen Wangenknochen, eine hochgezogene Augenbraue, schmale Lippen; der Blick halb gesenkt. Beim Zielen verengen sich die Augen, getroffen öffnet sie empört den Mund.',
    weapon: 'Mondsichel-Armbrust mit Goldbogen, Silberkante, Kurbel am Schaft und Bolzen mit Mond-Federn.',
    anim: {
      idle: ['prüft die Sehne mit spitzen Fingern', 'Umhang weht, sie streicht die Krause glatt'],
      walk: ['gemessener Schritt, Schleppe zieht nach'],
      attack: ['Armbrust anlegen (Anticipation), kurzes Zielen mit geneigtem Kopf', 'Schuss mit Rückstoß, die Sichel federt'],
      hit: ['Kopf zur Seite, die Krause wackelt'],
      spawn: ['schwebt mit gebauschter Schleppe herab'],
      death: ['sinkt auf die Knie, die Krone rutscht', 'Schleppe deckt sie zu, dann verblasst sie'],
    },
    special: {
      ability: 'Tarnumhang: Sie wirft die Schleppe wie einen Mantel über sich (Pose), wird halbdurchsichtig mit leuchtenden Augen und schießt schnell. Event `char.ability.archer-queen` erzeugt einen Schleier aus Mondfunken.',
      aura: 'Smaragdgrüne Bodenaura mit Mondsicheln; `char.release` lässt Goldfunken an der Sichel aufblitzen.',
    },
  },
  'little-prince': {
    concept: 'Der Little Prince ist ein verwöhnter Kinderprinz in einem petrolfarbenen Samtmantel, dem eine riesige Krone ständig über die Augen rutscht. Er kurbelt an einer Repetier-Armbrust, die immer schneller schießt, je länger er stehen bleibt. Wird es brenzlig, pfeift er seine Leibwächterin Guardienne herbei.',
    unique: 'Die übergroße, rutschende Krone ist breiter als der ganze Prinz; die Rekruten haben rutschende Helme, aber keine Krone. Die Kurbel-Armbrust mit Trommelmagazin trägt nur er. Kinderprinzen anderer Spiele fahren oft Streitwagen; dieser steht auf einem Schemelchen und kurbelt.',
    silhouette: 'Winzig mit riesigem Kopf und noch größerer Krone, darunter ein Samtmantel mit Hermelinkragen; die Armbrust mit Trommel steht vor ihm.',
    mainName: 'Petrol-Samt (Mantel)',
    accName: 'Creme (Hermelin, Strümpfe)',
    materials: [['Krone (Gold)', '#f0c040'], ['Haar', '#e6b84a']],
    signature: 'Die Krone mit fünf Zacken und Samtkissen ist so groß, dass sie auf seinen Ohren aufliegt und bei jeder Bewegung nach vorn kippt.',
    details: {
      kleidung: 'Samtmantel mit Hermelinkragen, Pluderhose, weiße Strümpfe, Schnallenschuhe',
      material: 'Samt, Hermelin, Gold, Holz',
      muster: 'Hermelinschwänzchen-Punkte',
      schnallen: 'große Goldschnallen an den Schuhen',
      abnutzung: 'Krone verbeult vom Herunterfallen',
      accessoires: 'Umhang und Kronenkissen (Teamzonen), Trillerpfeife an einer Kordel',
    },
    face: 'Kugelrundes Kindergesicht mit Schmollmund und vorgeschobener Unterlippe, große Augen unter dem Kronenrand. Im Angriff zieht er die Brauen ehrgeizig zusammen.',
    weapon: 'Repetier-Armbrust mit Trommelmagazin und Handkurbel; je schneller er kurbelt, desto schneller dreht die Trommel.',
    anim: {
      idle: ['schiebt die Krone hoch, verschränkt die Arme, stampft', 'Krone rutscht wieder herunter'],
      walk: ['wichtiger Watschelgang mit erhobener Nase'],
      attack: ['kurbelt (Anticipation), Bolzen fliegt', 'mit jedem Schuss kurbelt er hektischer'],
      hit: ['Krone fällt über die Augen'],
      spawn: ['plumpst herunter, Krone springt hoch und landet schief'],
      death: ['setzt sich hin und weint, Krone rollt davon', 'verblasst'],
    },
    special: {
      ability: 'Königliche Rettung: Er pfeift mit der Trillerpfeife und zeigt nach vorn (Pose). Event `char.ability.little-prince` erzeugt Pfiff-Ringe, Guardienne stürmt mit ihrer Tür heran.',
      aura: 'Petrolfarbene Bodenaura mit kleinen Kronen; die Kurbelgeschwindigkeit ist sichtbar am Drehtempo der Trommel.',
    },
  },
  guardienne: {
    concept: 'Guardienne ist die wortkarge Leibwächterin des Little Prince. Sie trägt eine echte Holztür als Schild und eine Hellebarde. Auf Pfiff stürmt sie mit der Tür voran heran und schiebt alles beiseite.',
    unique: 'Eine Haustür mit Klinke, Briefschlitz und Fensterchen als Schild hat sonst keine Figur. Der Ritter hat einen Zinnenschild, die Wächter Sargdeckel, die Rekruten Rundschilde. Leibwächterinnen anderer Spiele tragen Turmschilde aus Metall; diese trägt eine Holztür.',
    silhouette: 'Keil: breite Schultern mit gepolsterten Schulterkappen, schmale Hüfte. Die hochrechteckige Tür verdeckt eine Körperseite, die Hellebarde ragt diagonal darüber.',
    mainName: 'Lavendel-Violett (Waffenrock, Schulterkappen)',
    accName: 'Leinen-Creme (Polster, Stiefel)',
    materials: [['Tür (Eiche)', '#8a5a32'], ['Türbeschläge', '#4a4f58']],
    signature: 'Eine Eichentür mit Klinke, Briefschlitz, Türklopfer und Fensterchen samt Vorhang (Teamzone).',
    details: {
      kleidung: 'gepolsterter Waffenrock, Schulterkappen, Halsberge, schwere Stiefel, Federhelm mit Nackenschutz',
      material: 'Eichenholz, Eisen, Wolle, Leder',
      muster: 'Holzmaserung und Bretterfugen an der Tür, Steppmuster',
      schnallen: 'Türbänder, Klinke, Briefschlitz, Nieten an den Kappen',
      abnutzung: 'Kratzer und Stiefelabdrücke auf der Tür',
      accessoires: 'Vorhang im Türfenster und Schärpe (Teamzonen), Hausnummer „3“ auf der Tür',
    },
    face: 'Ernstes Gesicht mit schmalen Augen, gerader Nase und festem Kinn; ein kurzer Zopf schaut hinter dem Helm hervor. Im Ansturm reißt sie die Augen auf.',
    weapon: 'Hellebarde mit halbmondförmigem Beil und Haken; der Schaft ist mit Lederbändern umwickelt.',
    anim: {
      idle: ['stellt die Tür ab und lehnt sich daran', 'späht durch das Türfenster'],
      walk: ['schwerer Schritt, die Tür wird getragen wie ein Brett'],
      attack: ['Tür vor, Hellebarde zurück (Anticipation), Stoß über die Tür'],
      hit: ['Tür vibriert, der Vorhang flattert'],
      spawn: ['stürmt mit der Tür voran herein und bremst schlitternd'],
      death: ['die Tür fällt auf sie wie ein Deckel und verblasst'],
    },
    special: { extra: '**Ansturm (`charge`):** Tür waagerecht vor dem Körper, Kopf eingezogen; beim Aufprall schwingt die Tür kurz auf.' },
  },
  'tower-king': {
    concept: 'Der Turmkönig ist ein rundlicher, gemütlicher Monarch auf dem Königsturm mit einer Krone in Form eines kleinen Turms mit Zinnen. Solange niemand seinen Turm angreift, schläft er mit Zipfelmütze über der Krone; wach zeigt er mit dem Zepter auf Ziele, und die Turmkanone feuert.',
    unique: 'Die Zinnenkrone wiederholt die Turmform des Spielfelds, und die Zipfelmütze im Schlaf ist sein Zustandsmerkmal. Andere gekrönte Figuren haben Geweih-, Kegel- oder Riesenkronen. Turmkönige anderer Spiele haben meist Vollbart und Faust; dieser hat einen runden Bauch, Hermelin und ein Zepter als Zeigestock.',
    silhouette: 'Dreieck aus weitem Hermelinmantel mit rundem Bauch; oben die kleine Turmkrone, seitlich das Zepter.',
    mainName: 'Königspurpur (Mantel)',
    accName: 'Kronengold',
    materials: [['Hermelin', '#f5f1e8'], ['Bart', '#e8e2d6']],
    signature: 'Die Krone ist ein runder Mini-Turm mit vier Zinnen und einem Fenster, in dem ein Juwel steckt.',
    details: {
      kleidung: 'Hermelinmantel, Brokatwams über dem Bauch, Goldgürtel, Pantoffeln',
      material: 'Samt, Hermelin, Brokat, Gold',
      muster: 'Hermelinpunkte, Brokatranken',
      schnallen: 'große Gürtelschnalle mit Turmwappen',
      abnutzung: 'Hermelin leicht zerzaust',
      accessoires: 'Hermelinkragen-Saum und Zepterstein (Teamzonen), Zipfelmütze (nur im Schlaf)',
    },
    face: 'Rundes Gesicht mit roten Bäckchen, weißem Rauschebart und buschigen Brauen; im Schlaf ein offener Mund mit Blubber, wach ein energischer Blick. Getroffen bläst er die Backen auf.',
    weapon: 'Zepter mit Turmspitze und Juwel als Zeigestock.',
    anim: {
      idle: ['schläft: Kopf sinkt, Zipfelmütze nickt, „z“ steigen auf', 'wach: Hände auf dem Bauch, wippt auf den Fersen'],
      walk: ['keine Fortbewegung (steht auf dem Turm)'],
      attack: ['reißt das Zepter hoch (Anticipation), zeigt auf das Ziel; der Turm feuert'],
      hit: ['hält sich die Krone fest'],
      spawn: ['erwacht: Zipfelmütze fliegt weg, er streckt sich'],
      death: ['Turm stürzt; er purzelt rückwärts hinunter und ist weg'],
    },
  },
  'tower-guard': {
    concept: 'Die Turmwache steht auf den Prinzessinnentürmen und hält mit Langbogen und Signalhorn Ausschau. Sie ist streng, aufmerksam und schießt schnell. Sie trägt ein moosgrünes Lodenwams und eine Schirmkappe.',
    unique: 'Das Signalhorn am Schulterriemen mit Teamwimpel ist ihr Merkmal; keine andere Schützin trägt ein Horn. Die Bogenschützen haben einen Fächerköcher, die Prinzessin einen Harfenbogen. Turmwachen sonst sind oft Prinzessinnen; diese ist eine Wachsoldatin mit Kappe und Horn.',
    silhouette: 'Schlank, Kappe mit Schirm, das Horn als Bogen über der Schulter, der Langbogen höher als sie selbst.',
    mainName: 'Moosgrau-Grün (Lodenwams)',
    accName: 'Pergament (Hemd, Federn)',
    materials: [['Horn (Messing)', '#d0a040'], ['Bogenholz', '#7a4a2a']],
    signature: 'Ein gebogenes Messing-Signalhorn mit Wimpel (Teamzone) am Schulterriemen.',
    details: {
      kleidung: 'Lodenwams mit Kapuzenkragen, Schirmkappe, Hose mit Wickelgamaschen',
      material: 'Loden, Leder, Messing, Eibenholz',
      muster: 'grobe Lodenstruktur, Saumnaht',
      schnallen: 'Riemen mit Messingschnalle',
      abnutzung: 'verbeultes Horn',
      accessoires: 'Wimpel am Horn und Kappe (Teamzonen)',
    },
    face: 'Schmale wache Augen, gerunzelte Stirn, kleiner Mund. Beim Horn-Blasen bläht sie die Backen.',
    weapon: 'Langer Turmbogen aus Eibe mit Hornspitzen.',
    anim: {
      idle: ['späht mit der Hand über den Augen', 'bläst kurz ins Horn'],
      walk: ['keine Fortbewegung (steht auf dem Turm)'],
      attack: ['Pfeil auflegen, schneller Schuss, nachfedern'],
      hit: ['duckt sich hinter die Zinne'],
      spawn: ['tritt an die Zinne und salutiert'],
      death: ['Turm stürzt; sie springt mit einem Hornstoß hinab'],
    },
  },
  'mega-knight': {
    concept: 'Der Megaritter ist ein wuchtiger Koloss in schwerer Plattenrüstung mit einem Helm in Form einer Kirchenglocke, der bei jeder Landung dröhnend läutet. Statt Waffen trägt er riesige gusseiserne Kugelfäuste. Er springt auf Gegner und walzt alles platt.',
    unique: 'Der Glockenhelm mit Klöppel im Inneren ist ein klarer Kopf-Umriss, den niemand sonst hat; die Kugelfäuste ersetzen jede Waffe. Andere schwere Ritter tragen Hörner- oder Spitzhelme mit Keulen; dieser hat eine Glocke als Kopf und Kugeln als Hände.',
    silhouette: 'Breiter Berg mit Glocke obenauf, die Schultern sind riesige Platten, die Fäuste zwei Kugeln fast in Kopfgröße, die Beine kurze dicke Säulen.',
    mainName: 'Gusseisen-Grau (Rüstung)',
    accName: 'Bronze (Glocke, Beschläge)',
    materials: [['Glockenklöppel', '#3a3d44'], ['Kettenrock', '#7a828e']],
    signature: 'Der Helm ist eine Bronzeglocke mit Sehschlitz und Klöppel; bei der Landung schwingt sie und erzeugt Klangringe.',
    details: {
      kleidung: 'Glockenhelm, Brustpanzer wie ein Fass, Schulterplatten mit Nieten, Kettenrock, Plattenstiefel',
      material: 'Gusseisen, Bronze, Kettenringe',
      muster: 'Nietenreihen, Glockeninschrift als Gravur',
      schnallen: 'Gurte mit Doppelschnallen über der Brust',
      abnutzung: 'Rost an den Nieten, Dellen im Brustpanzer',
      accessoires: 'Schulterumhang und Helmband (Teamzonen)',
    },
    face: 'Nur zwei glimmende Augen im Sehschlitz der Glocke, deren Form sich mit dem Ausdruck ändert: zufrieden geschwungen, im Angriff schmale Schlitze, getroffen kreisrund.',
    weapon: 'Zwei gusseiserne Kugelfäuste mit Fingerrillen und Bronzeringen am Handgelenk.',
    anim: {
      idle: ['lässt die Kugelfäuste aneinanderklacken', 'Glocke summt leise beim Atmen'],
      walk: ['stampfender Gang mit `char.step`, Boden bebt'],
      attack: ['beide Fäuste hoch (Anticipation, Stretch), Doppelhammer nach unten (Squash)'],
      hit: ['Glocke dröhnt kurz, Körper schwankt'],
      spawn: ['Landung mit `char.land`: Glocke läutet, Klangring breitet sich aus'],
      death: ['kippt vornüber, die Glocke rollt davon und verklingt'],
    },
    special: {
      evo: 'Aufwärtshaken-Evo: Die rechte Kugelfaust wird zu einem Bronzefausthammer mit Raketenring, der Helm bekommt eine zweite, kleinere Glocke. Leuchtende Schallwellen dienen als Leuchtkanten, Klangfunken als Partikelhülle.',
      extra: '**Sprung (`charge`/`JUMP`):** Knie tief, Sprung mit Stretch, Landung mit Glockenläuten.',
    },
  },
  'hog-rider': {
    concept: 'Der Schweinereiter ist ein übermütiger Jockey in rautengemusterter Rennseide mit Rennbrille, der auf einem Borstenschwein zu Gebäuden galoppiert. Vor der Schweineschnauze baumelt an einer Angel eine Karotte. Er spielt Polo mit Türmen und jauchzt dabei.',
    unique: 'Die Karottenangel vor dem Reittier ist ein einmaliges Merkmal. Der Prinz reitet ein Pferd, der dunkle Prinz einen Waran, die Widderreiterin einen Widder. Schweinereiter anderer Spiele sind grobe Krieger mit Hammer; dieser ist ein schmaler Jockey mit Rennbrille und Polo-Schläger.',
    silhouette: 'Rundes Schwein im Halbprofil mit kurzen Beinen und großer Schnauze; darüber der kleine, nach vorn gebeugte Jockey. Die Angel ragt als Bogen nach vorn, die Karotte hängt vor der Schnauze.',
    mainName: 'Borstenschwein-Braunrosa',
    accName: 'Karottenorange',
    materials: [['Rennseide (weiß)', '#f4f0e6'], ['Sattelleder', '#6b3e22'], ['Brille (Messing)', '#c8a046']],
    signature: 'Eine Bambusangel am Sattel, an deren Schnur eine Karotte mit Grün direkt vor der Schnauze baumelt.',
    details: {
      kleidung: 'Rennseide mit Rautenmuster, Jockeymütze mit Schirm, Rennbrille, Reithose, Stiefel',
      material: 'Seide, Leder, Messing, Bambus, Borsten',
      muster: 'Rauten auf der Seide (Teamzone), Borstenstriche am Schwein',
      schnallen: 'Sattelgurt, Brillenriemen',
      abnutzung: 'Schlammspritzer an Stiefeln und Schweinebeinen',
      accessoires: 'Rennseide-Rauten und Satteldecke (Teamzonen), Startnummer am Rücken',
    },
    face: 'Jockey mit breitem Grinsen und Zahnlücke, die Augen hinter der Rennbrille; das Schwein mit Hängeohren und gierigem Blick auf die Karotte. Beim Sprung reißen beide die Münder auf.',
    weapon: 'Polo-Schläger mit langem Bambusstiel und zylindrischem Holzkopf.',
    anim: {
      idle: ['Schwein scharrt und schnüffelt nach der Karotte', 'Jockey wippt im Sattel'],
      walk: ['Galopp mit Wellen durch den Schweinerücken', 'Karotte schaukelt vor der Schnauze'],
      attack: ['Schläger weit nach hinten (Anticipation), seitlicher Polo-Schlag', 'Follow-through über den Kopf'],
      hit: ['Schwein quiekt, die Ohren fliegen hoch'],
      spawn: ['galoppiert aus der Landung an'],
      death: ['Schwein setzt sich auf den Hintern, der Jockey purzelt ab', 'die Karotte bleibt kurz liegen und verblasst'],
    },
    special: { extra: '**Flusssprung (`JUMP`):** Schwein streckt alle vier Beine, die Ohren flattern, die Karotte schwingt nach oben.' },
  },
  'dark-prince': {
    concept: 'Der Dunkle Prinz ist ein arroganter Ritter in dunkelvioletter Rüstung auf einem gepanzerten Waran mit Stachelkamm. Er schwingt einen Morgenstern im Kreis und stürmt nach kurzem Anlauf los. Sein Sichelmond-Schild glänzt im Halbdunkel.',
    unique: 'Das Reittier ist ein langgestreckter Waran mit Krallen statt eines Pferdes. Der Prinz reitet ein Pferd, die Widderreiterin einen Widder. Dunkle Prinzen anderer Spiele sitzen auf schwarzen Rössern; dieser reitet eine Echse, und sein Schild hat die Form eines Sichelmonds.',
    silhouette: 'Flaches, langes Echsen-Rechteck mit Schwanz auf kurzen gespreizten Beinen; darüber der gerüstete Reiter mit spitzer Stachelschulter. Seitlich der Sichelmond-Schild, oben pendelt der Morgenstern.',
    mainName: 'Dunkelviolett (Rüstung, Waranschuppen)',
    accName: 'Giftlimette (Echsenaugen, Edelsteine)',
    materials: [['Waranbauch', '#a39a7a'], ['Stahl', '#5a5f6b']],
    signature: 'Ein Waran mit Panzerplatten auf dem Rücken, gelben Schlitzaugen und gespaltener Zunge; die Krallen kratzen über den Boden.',
    details: {
      kleidung: 'Visierhelm mit Hörnerkamm, Plattenrüstung mit Stachelschulter, Kettenrock',
      material: 'brünierter Stahl, Schuppen, Leder',
      muster: 'Schuppenmuster am Waran, Gravur in Sichelform',
      schnallen: 'Sattelgurte mit Stachelnieten',
      abnutzung: 'Kratzer am Schild',
      accessoires: 'Schabracke und Schildmitte (Teamzonen)',
    },
    face: 'Hinter dem Visier leuchten zwei limettengrüne Augenschlitze, darüber eine Stirn wie eine Gewitterwolke. Der Waran züngelt und hat ein spöttisches Schlitzlächeln.',
    weapon: 'Morgenstern mit kurzer Kette und Stachelkugel; der Sichelmond-Schild sitzt am linken Arm.',
    anim: {
      idle: ['Waran züngelt und hebt den Kopf', 'Morgenstern pendelt locker'],
      walk: ['Schlängelgang des Warans, der Schwanz schwingt gegenläufig'],
      attack: ['Morgenstern über den Kopf kreisen lassen (Anticipation), Rundumschlag'],
      hit: ['Waran faucht, der Schild wird hochgerissen'],
      spawn: ['Waran landet auf allen vieren und peitscht mit dem Schwanz'],
      death: ['Waran rollt sich zur Seite, der Prinz fällt', 'Rüstung zerfällt in Staub'],
    },
    special: { extra: '**Ansturm (`charge`):** Waran rennt hochbeinig, der Prinz hält den Morgenstern gestreckt nach vorn; beim Flusssprung peitscht der Schwanz.' },
  },
};
