// Design-Briefs: Nordvolk (Barbaren, Walküre, Holzfäller, Widderreiterin) und Riesen
export default {
  barbarians: {
    concept: 'Die Barbaren sind fünf laute Draufgänger aus dem Nordvolk, jeder trägt eine Wolfskopf-Kapuze mit offenem Maul über dem Kopf. Sie schwingen breite Hackschwerter und haben gewaltige, mit Leder umwickelte Unterarme. Sie kommen als brüllende Meute.',
    unique: 'Die Wolfskopf-Kapuze rahmt das Gesicht mit Oberkiefer und Zähnen; keine andere Figur trägt einen Tierkopf als Kapuze (Elitebarbaren haben einen Bärenschädel auf der Schulter, die Berserkerin einen Kochtopf). Gängige Barbaren tragen Hörnerhelme und Schnurrbart; diese tragen Wolfsfell, Hackschwerter und fünf verschiedene Bart- und Haarvarianten.',
    silhouette: 'Breit und kurz: Die Kapuze bildet einen spitzen Wolfskopf mit aufgestellten Ohren über dem Kopf, die Unterarme sind dicke Keulen, das Hackschwert eine breite Platte schräg nach oben.',
    mainName: 'Wolfsgrau-Braun (Kapuze, Fell)',
    accName: 'Gerbleder (Wickel, Gürtel)',
    materials: [['Haut', '#e2a878'], ['Bart (Varianten)', '#b5632a'], ['Hackschwert', '#9aa3ad']],
    signature: 'Wolfskopf-Kapuze mit Oberkiefer, Reißzähnen über der Stirn und abstehenden Ohren; das Fell fällt als Kragen über die Schultern.',
    details: {
      kleidung: 'Wolfskapuze mit Fellkragen, ärmellose Fellweste, Lendenschurz über einer Wollhose, Fellstiefel',
      material: 'Wolfsfell, Gerbleder, Wolle, geschmiedetes Eisen',
      muster: 'Fellsträhnen am Kragen, Kreuzwicklung an den Unterarmen',
      schnallen: 'Knochenknebel statt Schnallen, Eisenring am Gürtel',
      abnutzung: 'Scharten in der Klinge, zerzaustes Fell',
      accessoires: 'Gürtelschärpe und Armwickel (Teamzonen), Zahnkette',
    },
    face: 'Breites Gesicht mit großer Nase, wildem Blick und weit aufgerissenem, brüllendem Mund; Bart und Haar je nach Variante. Im Idle grinsen sie breit, getroffen fletschen sie die Zähne.',
    weapon: 'Hackschwert: breite, fast rechteckige Klinge mit abgeschrägter Spitze, Griff mit Lederwicklung und Knochenknauf.',
    anim: {
      idle: ['rollen die Schultern und klopfen sich auf die Brust', 'Wolfsohren wackeln mit'],
      walk: ['breitbeiniger, federnder Stampfschritt', 'Fellkragen schwingt nach'],
      attack: ['Anticipation: Körper weit nach hinten, Schwert über den Kopf', 'Hieb bis zum Boden mit Squash', 'Follow-through: Klinge federt hoch, Kapuze nickt nach'],
      hit: ['Kopf ruckt zurück, Kapuze rutscht ins Gesicht'],
      spawn: ['landen mit gespreizten Beinen und brüllen'],
      death: ['fallen rücklings, die Kapuze bleibt als Wolfskopf liegen und verblasst'],
    },
    special: {
      evo: 'Rasende Evo: Die Wolfsaugen der Kapuze leuchten bernsteinfarben, blitzförmige Kriegsbemalung kommt auf Arme und Wangen, die Klingen werden zu doppelt gezackten Hackschwertern. Nach jedem Treffer ziehen kurze Geschwindigkeitsstreifen hinterher, Funken bilden die Partikelhülle.',
      variants: 'Rauschebart, Narbe über dem Auge, Zöpfe, Glatze, Schnauzer; Farbton ±6°, Größe ±5 %',
    },
  },
  'elite-barbarians': {
    concept: 'Die Elitebarbaren sind zwei angeberische Champions des Nordvolks mit bernsteinfarbener Kriegsbemalung und einem Bärenschädel als Schulterpanzer. Sie schwingen Flamberge, also Wellenschwerter, und sind schnell und hart. Sie grinsen dabei überlegen.',
    unique: 'Der Bärenschädel-Schulterpanzer mit Unterkiefer sitzt asymmetrisch auf einer Schulter und macht die Keil-Silhouette einmalig; das Flamberge mit Wellenklinge führt nur er. Die Barbaren tragen Wolfskapuzen, die Walküre eine Rad-Axt. Elite-Krieger anderer Spiele tragen Hörnerhelme; diese tragen den Schädel auf der Schulter und den Kopf frei mit Zopfbart oder Irokese.',
    silhouette: 'Keil: eine Schulter mit großem Bärenschädel, die andere frei, schmale Hüfte. Das Wellenschwert liegt diagonal über der Schulter.',
    mainName: 'Bernstein (Felle, Bemalung)',
    accName: 'Dunkles Leder (Gurte, Stiefel)',
    materials: [['Bärenschädel', '#e8dcc0'], ['Haut', '#d99a6a'], ['Klinge', '#b8c0c8']],
    signature: 'Ein gebleichter Bärenschädel mit Unterkiefer dient als Schulterpanzer; die Eckzähne zeigen nach vorn.',
    details: {
      kleidung: 'Bernsteinfell-Umhang auf einer Schulter, Lederharnisch, Wickelhose, Fellstiefel',
      material: 'Bärenknochen, Fell, Leder, Damaststahl',
      muster: 'Damastwellen auf der Klinge, Kriegsbemalung in Streifen',
      schnallen: 'Gurte mit Knochenknebeln, Eisenringe',
      abnutzung: 'Risse im Schädel',
      accessoires: 'Gürtelschärpe und Griffwicklung (Teamzonen), Ohrringe aus Zähnen',
    },
    face: 'Kantiges Gesicht mit schmalen Augen, hochgezogener Oberlippe und Kriegsbemalung; Zopfbart oder Irokese je nach Variante. Im Angriff ein Kampfschrei mit gefletschten Zähnen.',
    weapon: 'Flamberge: zweihändiges Schwert mit gewellter Klinge, Parierhaken und langem Ledergriff.',
    anim: {
      idle: ['Schwert lässig auf der Schulter, dehnt den Nacken', 'grinst den Gegner an'],
      walk: ['schneller, kraftvoller Schritt mit vorgeschobenem Kinn'],
      attack: ['Anticipation: Drehung nach hinten', 'zweihändiger Diagonalhieb mit halber Drehung', 'Follow-through mit nachschwingendem Umhang'],
      hit: ['schüttelt den Kopf, Schädelkiefer klappert'],
      spawn: ['landen Rücken an Rücken und posieren'],
      death: ['fallen auf die Knie, der Bärenschädel rollt herunter und verblasst'],
    },
    special: {
      evo: 'Wut-Speer-Evo: Ein Knochenspeer mit Wut-Wimpel kommt auf den Rücken, der Bärenschädel bekommt glühende Augen, die Bemalung wird zu leuchtenden Wut-Streifen in Violett. Violette Wutfunken bilden die Partikelhülle; der Speerwurf hat eigene Anticipation.',
      variants: 'Zopfbart, Irokese; Farbton ±6°, Größe ±5 %',
    },
  },
  valkyrie: {
    concept: 'Die Walküre ist eine kampflustige Kriegerin mit Flügelhelm und einer Doppelaxt, deren Kopf wie ein Wagenrad mit Speichen gebaut ist. Sie wirbelt mit der Axt einmal um sich herum und trifft alles in ihrer Nähe. Sie lacht beim Wirbeln.',
    unique: 'Die Rad-Doppelaxt mit Speichen und Nabe hat sonst niemand; die schiefergraue Rüstung mit orangefarbenen Akzenten gibt es nur bei ihr. Die Barbaren tragen Hackschwerter, die Elitebarbaren Flamberge. Walküren anderer Spiele haben orangefarbene Zöpfe; diese hat weißblonde Zöpfe und kämpft mit einer Radaxt.',
    silhouette: 'Breit mit runder Radaxt als großem Kreis neben dem Körper; der Helm hat zwei kleine Flügel, die Zöpfe stehen seitlich ab.',
    mainName: 'Schiefer (Schuppenpanzer, Rock)',
    accName: 'Kupferorange (Axtnabe, Riemen)',
    materials: [['Zöpfe (weißblond)', '#f2e6c4'], ['Axtstahl', '#b8c2cc'], ['Helmflügel', '#f6f2ea']],
    signature: 'Der Axtkopf ist ein Rad mit sechs Speichen; die Klingen sitzen am Radkranz wie halbe Monde.',
    details: {
      kleidung: 'Flügelhelm, Schuppenpanzer, Faltenrock aus Leder, Armstulpen, Fellstiefel',
      material: 'Stahlschuppen, Leder, Federn, Kupfer',
      muster: 'Schuppenreihen, Flechtmuster an den Zöpfen',
      schnallen: 'Kupfer-Gürtelschnalle in Radform',
      abnutzung: 'eine abgebrochene Feder am Helm',
      accessoires: 'Gürtel und Helmflügel-Spitzen (Teamzonen), Zopfringe aus Kupfer',
    },
    face: 'Breites Lächeln mit Lachfalten, Sommersprossen, kräftige Brauen; zwei dicke Zöpfe. Im Wirbel lacht sie mit offenem Mund, getroffen knurrt sie.',
    weapon: 'Rad-Doppelaxt mit Holzstiel, Kupfernabe, sechs Speichen und zwei mondförmigen Klingen am Kranz.',
    anim: {
      idle: ['stützt die Axt auf und wirft einen Zopf zurück', 'das Rad dreht sich langsam nach'],
      walk: ['kraftvoller Schritt, Axt auf der Schulter, Zöpfe schwingen'],
      attack: ['Anticipation: Ausholen mit Hüftdrehung', 'ganzer Körper dreht sich einmal mit der Axt (Spin), Zöpfe fliegen waagerecht', 'Follow-through mit Taumeln'],
      hit: ['Zöpfe schlagen nach, sie schnaubt'],
      spawn: ['landet mit einer halben Drehung'],
      death: ['dreht sich aus und fällt, die Axt rollt wie ein Rad davon'],
    },
    special: { evo: 'Wirbelsturm-Evo: Kranz und Klingen leuchten sturmblau, dazu kommen Windbänder an Helm und Axt und ein Gürtel mit Wolkenschnalle. Kleine Luftwirbel bilden die Partikelhülle, jeder Schlag erzeugt einen Wirbelring.' },
  },
  lumberjack: {
    concept: 'Der Holzfäller ist ein schlaksiger, hektischer Waldarbeiter mit einem Bart voller Tannenzweige und einer Holzkraxe auf dem Rücken. Darin stecken Scheite und eine Wutflasche. Er hackt blitzschnell mit seiner Fällaxt, und fällt er, zerbricht die Flasche zu einer Wutpfütze.',
    unique: 'Die Holzkraxe mit Scheiten und Flasche ist eine Rücken-Silhouette, die sonst nicht vorkommt; der Tannenzweig-Bart ist sein übertriebenes Merkmal. Die Barbaren und die Walküre kämpfen anders. Holzfäller anderer Spiele tragen rot-schwarzes Karo und Mütze; dieser trägt grünes Karo und eine Pudelmütze ohne Bommel.',
    silhouette: 'Hoch und schmal mit langen Beinen; hinten die rechteckige Kraxe, die über den Kopf ragt, vorn die Fällaxt mit langem Stiel und schmalem Blatt.',
    mainName: 'Tannengrün (Karohemd)',
    accName: 'Rost (Mütze, Hosenträger)',
    materials: [['Bart', '#8a5a2a'], ['Kraxe (Holz)', '#a8763e'], ['Wutflasche', '#c45cff']],
    signature: 'Eine Holzkraxe aus Latten mit drei Scheiten und einer violetten Wutflasche mit Korken.',
    details: {
      kleidung: 'grünes Karohemd mit hochgekrempelten Ärmeln, Hosenträger, Arbeitshose, Schnürstiefel, Strickmütze',
      material: 'Flanell, Wolle, Leder, Holz, Glas',
      muster: 'Karomuster, Holzmaserung, Flicken am Knie',
      schnallen: 'Hosenträgerknöpfe, Kraxengurte',
      abnutzung: 'Sägespäne im Bart, Harzflecken',
      accessoires: 'Halstuch und Mützenband (Teamzonen), Bleistift hinter dem Ohr',
    },
    face: 'Langes Gesicht mit großer Nase, wildem Bart mit eingesteckten Zweigen, aufgerissenen Augen und breitem Grinsen; die Brauen tanzen. Im Angriff ist er hektisch konzentriert.',
    weapon: 'Fällaxt mit langem gebogenem Stiel und schmalem, keilförmigem Blatt mit Kerbe.',
    anim: {
      idle: ['wirft die Axt hoch und fängt sie', 'zupft einen Zweig aus dem Bart'],
      walk: ['schnelle lange Schritte, Kraxe hüpft'],
      attack: ['schneller Hieb wie beim Holzhacken mit kurzer Anticipation', 'zweiter Hieb direkt hinterher'],
      hit: ['Scheite klappern in der Kraxe'],
      spawn: ['landet, die Kraxe rumpelt nach'],
      death: ['fällt um, die Wutflasche zerbricht mit violettem Spritzer', 'verblasst'],
    },
    special: {
      evo: 'Geister-Evo: Die Kraxe bekommt eine zweite, leuchtende Flasche, die Axt eine violette Schneide, der Bart violette Glühwürmchen. Zweige mit violettem Glimmen bilden die Partikelhülle.',
      forms: { ghost: 'Geist nach dem Tod: halb durchsichtiger, violett leuchtender Holzfäller ohne Beine mit glühender Axt, der in der Wutpfütze weiterhackt.' },
    },
  },
  'battle-ram': {
    concept: 'Der Rammbock ist ein Baumstamm mit geschnitztem Widderkopf und eisernen Spiralhörnern auf zwei Holzrädern, geschoben von zwei schnaufenden Wolfskapuzen-Barbaren. Er rammt das nächste Gebäude. Danach kämpfen die Schieber zu Fuß weiter.',
    unique: 'Die Kombination aus Stamm, geschnitztem Widderkopf und eisernen Spiralhörnern auf Rädern gibt es nur hier; die Widderreiterin hat einen echten Widder. Rammböcke anderer Spiele werden getragen; dieser fährt auf Rädern und hat einen geschnitzten Kopf.',
    silhouette: 'Langer liegender Stamm auf zwei Speichenrädern, vorn der breite Widderkopf mit eingerollten Hörnern, dahinter zwei gebeugte Figuren mit Wolfsohren.',
    mainName: 'Eichenstamm',
    accName: 'Eisen (Hörner, Bänder)',
    materials: [['Rinde', '#4f3220'], ['Schnitzholz', '#b07a48'], ['Wolfskapuze', '#857565']],
    signature: 'Ein grob geschnitzter Widderkopf mit Schlitzaugen und eisernen, eingerollten Hörnern am Stammende.',
    details: {
      kleidung: 'zwei Schieber in Wolfskapuzen und Fellwesten',
      material: 'Eiche, Rinde, Eisen, Fell',
      muster: 'Jahresringe an der Stirnseite, Rindenrillen, Schnitzkerben',
      schnallen: 'Eisenbänder um den Stamm, Achsnägel',
      abnutzung: 'Splitter und Risse am Widderkopf',
      accessoires: 'Wimpel am Stamm und Schärpen der Schieber (Teamzonen), Seilgriffe',
    },
    face: 'Der Widderkopf hat schmale, grimmige Schlitzaugen und geblähte Nüstern; die Schieber schnaufen mit roten Wangen und zusammengebissenen Zähnen.',
    weapon: 'Der Stamm selbst mit eisenbeschlagener Stirn.',
    anim: {
      idle: ['Schieber stampfen auf der Stelle, Stamm wippt'],
      walk: ['Räder drehen, Schieber laufen gebeugt'],
      attack: ['Anlauf (Anticipation: alle lehnen sich zurück), Rammstoß mit Squash des Stammes und Splitterwolke'],
      hit: ['Stamm ruckt, Wimpel zuckt'],
      spawn: ['rollt aus dem Fall an'],
      death: ['Stamm zerbricht in der Mitte, die beiden Schieber springen ab'],
    },
    special: {
      evo: 'Durchbruch-Evo: Eisenbeschläge bedecken den ganzen Widderkopf, die Hörner glühen, Stacheln sitzen an den Rädern. Funken und Rindensplitter bilden die Partikelhülle, beim Abprallen gibt es einen Rückwärts-Hüpfer.',
      extra: '**Ansturm (`charge`):** Schieber rennen, der Stamm ist leicht angehoben, Staubfahne hinter den Rädern.',
    },
  },
  berserker: {
    concept: 'Die Berserkerin ist eine wilde Kampfköchin des Nordvolks mit einem kupfernen Kochtopf als Helm, dessen Henkel wie Hörner abstehen. Sie schlägt mit zwei riesigen Bratpfannen sehr schnell abwechselnd zu und lacht dabei gackernd.',
    unique: 'Kochtopf-Helm und Bratpfannen sind Küchenwaffen, die nur sie trägt; der Doppelschlag mit Pfannen ist einmalig. Die Barbaren haben Hackschwerter, die Walküre eine Radaxt. Berserker anderer Spiele sind riesige Männer mit Äxten; sie ist eine flinke Köchin mit Zöpfen und Schürze.',
    silhouette: 'Keil mit breiten Schultern; oben der runde Topf mit seitlichen Henkeln, an den Armen zwei runde Pfannen wie große Scheiben.',
    mainName: 'Kupfer (Topf, Pfannenböden)',
    accName: 'Tannengrün (Kleid)',
    materials: [['Gusseisen (Pfannen)', '#3e3c42'], ['Zöpfe', '#e3c06b'], ['Schürze (weiß)', '#f4efe2']],
    signature: 'Kupferkochtopf mit zwei seitlichen Henkeln und Deckelknauf als Helmspitze.',
    details: {
      kleidung: 'Kochtopf-Helm, grünes Wollkleid, Schürze (Teamzone), gestreifte Strümpfe, Holzclogs',
      material: 'Kupfer, Gusseisen, Wolle, Leinen',
      muster: 'Streifenstrümpfe, Schürzentaschen',
      schnallen: 'Topfnieten, Schürzenknoten',
      abnutzung: 'Ruß an den Pfannenböden, Dellen im Topf',
      accessoires: 'Schürze und Zopfbänder (Teamzonen), Kochlöffel im Gürtel',
    },
    face: 'Runde Wangen, wilde Augen, weit offener lachender Mund mit Zahnlücke, wirre Zöpfe unter dem Topf. Getroffen schreit sie empört.',
    weapon: 'Zwei Gusseisen-Bratpfannen mit langen Griffen; eine größer als die andere.',
    anim: {
      idle: ['schlägt die Pfannen gegeneinander, Funken springen', 'Topf wackelt'],
      walk: ['hüpfender Laufschritt, Pfannen schwingen'],
      attack: ['abwechselnde Pfannenschläge links und rechts, sehr schnell (kurze Anticipation)', 'Topf klappert im Takt'],
      hit: ['Topf rutscht über die Augen'],
      spawn: ['landet, schlägt die Pfannen zusammen'],
      death: ['setzt sich hin, der Topf fällt herunter und dreht sich aus'],
    },
  },
  'barbarian-hut': {
    concept: 'Die Barbarenhütte ist ein gedrungenes Langhaus mit tief heruntergezogenem Grassodendach und einem Wolfsschädel über dem Tor. Aus dem Dachloch steigt Rauch, drinnen wird gelärmt. Alle paar Sekunden fliegt das Tor auf und Barbaren stürmen heraus.',
    unique: 'Ein grün bewachsenes Sodendach über dunklen Teerbalken mit Wolfsschädel ist bei keinem anderen Bauwerk zu finden; die Koboldhütte ist eine Flickwerk-Hütte, der Grabstein ein Stein. Barbarenhütten anderer Spiele sind Holzhütten mit Strohdach; diese ist ein Soden-Langhaus.',
    silhouette: 'Flacher, breiter Hügel aus Grassoden mit Dachloch, vorn ein tiefes Tor mit Wolfsschädel, an der Seite Holzstapel und eine Fahnenstange.',
    mainName: 'Grassoden-Grün (Dach)',
    accName: 'Teerschwarz (Balken)',
    materials: [['Wolfsschädel', '#e6dcc8'], ['Steinsockel', '#8a8478'], ['Torbehang', '#857565']],
    signature: 'Ein Wolfsschädel mit Unterkiefer hängt über dem Tor, darunter ein Behang aus Fell.',
    details: {
      kleidung: 'Sodendach mit Grasbüscheln, Teerbalken, Steinsockel',
      material: 'Grassoden, geteertes Holz, Stein, Knochen, Fell',
      muster: 'Grasbüschel, Balkenfugen, Steinfugen',
      schnallen: 'Eisenbeschläge am Tor',
      abnutzung: 'eingestürzte Sodenecke bei geringer Gesundheit, Rissspuren im Stein',
      accessoires: 'Torbehang und Dachfahne (Teamzonen), Holzstapel, Schild am Tor',
    },
    face: 'Kein Gesicht; der Wolfsschädel wirkt als Gesicht, seine Augenhöhlen glimmen, wenn Barbaren kommen.',
    weapon: 'Keine Waffe; das Tor ist der Ausgang der Barbaren.',
    anim: {
      idle: ['Rauch steigt aus dem Dachloch', 'Torbehang weht, die Fahne flattert'],
      walk: ['keine Fortbewegung'],
      attack: ['`char.spawnUnit`: Tor fliegt auf, Staub, Barbaren rennen heraus'],
      hit: ['Grasbüschel wackeln, Staub rieselt'],
      spawn: ['wächst aus dem Boden: erst Sockel, dann Balken, dann das Dach plumpst drauf'],
      death: ['Dach sackt ein, Balken stürzen, Wolfsschädel rollt'],
    },
  },
  'ram-rider': {
    concept: 'Die Widderreiterin ist eine abenteuerlustige Hirtin aus den Bergen auf einem Widder mit riesigen Doppelspiral-Hörnern und Kristallglöckchen. Der Widder stürmt auf Gebäude. Sie selbst fesselt Gegner mit ihrer Bola.',
    unique: 'Die Doppelspiral-Hörner sind größer als Wagenräder, und zusammen mit den Glöckchen und dem cremeweißen Wollkörper ergibt das ein Reittier, das niemand sonst hat. Der Rammbock hat nur einen geschnitzten Widderkopf. Widderreiterinnen anderer Spiele tragen Lila; diese trägt einen petrolfarbenen Wollmantel.',
    silhouette: 'Wolliges, rundliches Tier mit zwei riesigen spiralförmigen Kreisen am Kopf; obenauf die Reiterin mit kreisender Bola.',
    mainName: 'Wollcreme (Widder)',
    accName: 'Petrol (Mantel, Sattel)',
    materials: [['Hörner', '#b08a5a'], ['Zöpfe', '#e8743b'], ['Bola-Kugeln', '#7a7a80']],
    signature: 'Zwei Doppelspiral-Hörner mit Rillen und drei Kristallglöckchen an einem Halsband.',
    details: {
      kleidung: 'petrolfarbener Wollmantel, Fellmütze, Reithose, Fellstiefel',
      material: 'Wolle, Horn, Kristall, Leder',
      muster: 'Wolllocken, Hornrillen, Rautenmuster am Mantel',
      schnallen: 'Hornknöpfe, Sattelgurte',
      abnutzung: 'Kerben in den Hörnern',
      accessoires: 'Satteldecke und Zopfbänder (Teamzonen), Glöckchen',
    },
    face: 'Reiterin mit roten Zöpfen, Sommersprossen und rufendem offenem Mund; der Widder mit halbgeschlossenen, sturen Augen und vorgeschobenem Kinn.',
    weapon: 'Bola mit drei Steinkugeln an Lederschnüren; der Widder rammt mit den Hörnern.',
    anim: {
      idle: ['Widder schüttelt die Glöckchen', 'Reiterin lässt die Bola kreisen'],
      walk: ['Widder trabt mit wippender Wolle'],
      attack: ['Widder senkt den Kopf (Anticipation) und rammt', 'Reiterin wirbelt die Bola über dem Kopf und wirft'],
      hit: ['Glöckchen bimmeln, die Wolle bauscht sich'],
      spawn: ['landet mit allen vier Hufen, Glöckchen klingeln'],
      death: ['Widder legt sich hin, die Reiterin gleitet herunter', 'Wollflocken wirbeln'],
    },
    special: { extra: '**Ansturm (`charge`):** Widder mit gesenkten Hörnern im Galopp; beim Flusssprung fliegen die Glöckchen hoch.' },
  },
  giant: {
    concept: 'Der Riese ist ein gutmütiger, schnaufender Bauernriese mit einer gestrickten Bommelmütze, geflickter Latzhose und riesigen Arbeitshandschuhen. Er stapft langsam auf Gebäude zu und haut mit beiden Fäusten darauf. Er ist zäh wie ein alter Baumstumpf.',
    unique: 'Die Bommelmütze mit riesigem Bommel in Teamfarbe ist auf dem Spielfeld von weitem lesbar; kein anderer Riese trägt eine Strickmütze (Königsriese: Bärenfellmütze, Runenriese: kahler Kopf, Elektroriese: Schweißervisier). Riesen anderer Spiele haben rote Haare und eine braune Weste; dieser trägt Mütze, Latzhose und Arbeitshandschuhe.',
    silhouette: 'Berg aus breiten Schultern mit kleinem Kopf, darauf die hohe Mütze mit Bommel; die Hände sind riesige Handschuhe fast bis zum Boden.',
    mainName: 'Erdbraun (Latzhose)',
    accName: 'Senfgelb (Handschuhe, Flicken)',
    materials: [['Haut', '#e9a97a'], ['Strickmütze', '#7a8a6a'], ['Hemd', '#efe4cc']],
    signature: 'Gestrickte Bommelmütze mit Zopfmuster und einem Bommel so groß wie sein Kopf (Teamzone).',
    details: {
      kleidung: 'Bommelmütze, kragenloses Hemd, Latzhose mit Flicken, Arbeitshandschuhe, Gummistiefel',
      material: 'Strickwolle, Denim, Leder, Gummi',
      muster: 'Zopfmuster an der Mütze, Flicken mit Kreuzstich',
      schnallen: 'große Latzknöpfe',
      abnutzung: 'Löcher an den Knien, abgewetzte Handschuhe',
      accessoires: 'Bommel und Latzhosen-Flicken (Teamzonen), Grashalm im Mundwinkel',
    },
    face: 'Kleiner Kopf mit Knollennase, gutmütigen Knopfaugen, Bartstoppeln und Grashalm im Mund. Im Angriff zieht er die Brauen zusammen und bläst die Backen auf.',
    weapon: 'Seine Fäuste in Arbeitshandschuhen mit verstärkten Knöcheln.',
    anim: {
      idle: ['kratzt sich unter der Mütze', 'Bommel wippt nach'],
      walk: ['schwerer, langsamer Stampfgang mit `char.step`, Bommel schwingt'],
      attack: ['Fäuste über dem Kopf gefaltet (Anticipation, Stretch), Hammerschlag nach unten (Squash)'],
      hit: ['brummt, kneift ein Auge zu'],
      spawn: ['landet schwer mit `char.land`, Mütze hüpft'],
      death: ['setzt sich, kippt dann nach hinten', 'der Bommel rollt davon'],
    },
  },
  'royal-giant': {
    concept: 'Der Königsriese ist ein strenger Leibgardist von riesiger Gestalt mit hoher Bärenfellmütze und einer Schulterkanone mit Löwenmaul-Mündung. Er beschießt Gebäude aus großer Entfernung. Bei jedem Schuss geht er vor Rückstoß in die Knie.',
    unique: 'Die hohe schwarze Bärenfellmütze macht ihn zur höchsten Kopfform unter den Riesen; die Löwenmaul-Kanone gibt es nur bei ihm. Andere Kanonen im Spiel: Hechtkopf der Kanonenkarre, Kondensator-Schüssel von Funki. Königsriesen anderer Spiele tragen Blau; dieser trägt eine dunkle Olivuniform mit Gold.',
    silhouette: 'Massig mit sehr hoher Mütze; die Kanone liegt waagerecht auf der Schulter und ragt weit nach vorn.',
    mainName: 'Dunkeloliv (Uniformrock)',
    accName: 'Gold (Knöpfe, Litzen, Löwenmaul)',
    materials: [['Bärenfell', '#25222a'], ['Haut', '#e2a078'], ['Kanonenbronze', '#b8863a']],
    signature: 'Eine hohe Bärenfellmütze mit Kinnkette und einer Kordel in Teamfarbe.',
    details: {
      kleidung: 'Uniformrock mit zwei Knopfreihen, Schulterklappen, weiße Hose, Stiefel',
      material: 'Wolle, Bärenfell, Gold, Bronze',
      muster: 'Goldlitzen, Fellstriche',
      schnallen: 'Messingknöpfe, Kanonenriemen mit Löwenschnalle',
      abnutzung: 'Pulverruß am Ärmel',
      accessoires: 'Schärpe und Mützenkordel (Teamzonen), Ladestock am Rücken',
    },
    face: 'Breites Gesicht mit gewaltigem gezwirbeltem Schnurrbart, strengem Blick unter der Mützenkante und zusammengepressten Lippen. Beim Schuss pustet er die Backen auf.',
    weapon: 'Schulterkanone aus Bronze mit Löwenmaul-Mündung, Lafettenriemen und Zündloch.',
    anim: {
      idle: ['salutiert kurz, putzt einen Knopf', 'Schnurrbart zuckt'],
      walk: ['Paradeschritt mit `char.step`'],
      attack: ['Zielen, Lunte (Anticipation), Schuss mit Rückstoß bis in die Knie (Squash)', 'Rauch aus dem Löwenmaul'],
      hit: ['Mütze wackelt, er blinzelt'],
      spawn: ['landet in Habachtstellung'],
      death: ['fällt steif wie ein Brett um, die Mütze rollt'],
    },
    special: { evo: 'Rückstoß-Evo: Ein zweites Rohr (Doppelkanone) und ein Kürass mit Löwenrelief kommen hinzu, die Mütze bekommt ein Gold-Emblem. Bei jedem Schuss breitet sich ein goldener Stoßring aus, Pulverfunken bilden die Partikelhülle.' },
  },
  'rune-giant': {
    concept: 'Der Runenriese ist ein feierlicher Steinmetz-Riese mit leuchtenden Runentätowierungen, der eine riesige Steintafel als Schild und Waffe trägt. Er stapft zu Gebäuden und verzaubert die nächsten Verbündeten, indem er eine Rune in die Tafel meißelt.',
    unique: 'Die Runentafel ist ein Steinrechteck mit Runen und gibt ihm eine Schild-ähnliche, aber eckige Silhouette. Andere Riesen tragen Mütze, Kanone oder Spulen. Runenriesen anderer Spiele haben magische Stäbe; dieser trägt eine Tafel und einen Meißel.',
    silhouette: 'Massig, kahler Kopf mit Bart; vor dem Körper die hohe rechteckige Tafel, in der anderen Hand ein Hammer-Meißel.',
    mainName: 'Granitgrau (Haut, Tafel)',
    accName: 'Runen-Cyan (Glühen)',
    materials: [['Bart', '#c8c2b8'], ['Lendentuch', '#6b5a48'], ['Meißel', '#8a6a4a']],
    signature: 'Eine Steintafel mit drei Runenzeilen, die einzeln aufleuchten, wenn er verzaubert.',
    details: {
      kleidung: 'Lendentuch, Lederschürze, Armreifen, Fußwickel',
      material: 'Granit, Leder, Bronze',
      muster: 'Runentätowierungen auf Armen und Brust, Meißelspuren',
      schnallen: 'Bronzearmreifen mit Runen',
      abnutzung: 'abgesplitterte Tafelecke',
      accessoires: 'Lendentuch und Armreif (Teamzonen), Steinstaub-Beutel',
    },
    face: 'Langer Bart, buschige Brauen, halb geschlossene weise Augen, murmelnder Mund. Beim Verzaubern leuchten die Augen cyan.',
    weapon: 'Runentafel (Schild und Schlagwaffe) und ein kurzer Hammer-Meißel.',
    anim: {
      idle: ['meißelt eine Rune, Steinstaub fällt'],
      walk: ['würdevoller Schritt mit `char.step`, Tafel vor dem Körper'],
      attack: ['Tafel hoch (Anticipation), Tafelstoß nach unten', 'beim Verzaubern leuchtet eine Rune auf'],
      hit: ['Tafel vibriert, Staub rieselt'],
      spawn: ['stellt die Tafel mit dumpfem Schlag ab'],
      death: ['Tafel zerbricht in drei Stücke, er sinkt zusammen'],
    },
  },
  bowler: {
    concept: 'Der Bowler ist ein gemütlicher Steintroll mit moosbewachsenem Rücken, Hosenträgern und einem winzigen Melonenhut auf dem riesigen Kopf. Er rollt Runenkugeln wie beim Kegeln durch die Reihen der Gegner. Vor jedem Wurf poliert er die Kugel am Bauch.',
    unique: 'Der winzige Bowler-Hut auf dem riesigen Moos-Kopf ist ein absurdes, sofort lesbares Detail; kein anderer Riese trägt einen Hut dieser Form. Die Kegelbewegung mit hohem Bein ist sein eigener Angriff. Bowler anderer Spiele sind blaue Riesen mit Felsen; dieser ist ein grüner Steintroll mit Kegelkugel.',
    silhouette: 'Massig mit gebeugtem, moosigem Buckel; oben ein winziger runder Hut, in der Hand eine Kugel mit drei Löchern.',
    mainName: 'Moosgrün (Haut, Moos)',
    accName: 'Anthrazit (Hut, Hose)',
    materials: [['Runenkugel', '#6a7a8a'], ['Hemd', '#e8dfc8'], ['Stein-Haut', '#9aa48a']],
    signature: 'Ein winziger schwarzer Melonenhut mit Hutband (Teamzone), schief auf dem riesigen Kopf.',
    details: {
      kleidung: 'Melonenhut, kurzärmeliges Hemd, Hosenträger, Kniebundhose',
      material: 'Stein, Moos, Wolle, Filz',
      muster: 'Mooskissen, Steinrisse, Nadelstreifen auf der Hose',
      schnallen: 'Hosenträgerklemmen',
      abnutzung: 'Moos wächst aus Rissen',
      accessoires: 'Hosenträger und Hutband (Teamzonen), Polierlappen in der Tasche',
    },
    face: 'Breites Gesicht mit Unterbiss, zwei Hauern, kleinen Augen und konzentriert gespitzten Lippen beim Zielen. Getroffen hebt er überrascht die Brauen.',
    weapon: 'Runenkugel aus Stein mit drei Grifflöchern und leuchtender Rune.',
    anim: {
      idle: ['poliert die Kugel am Bauch', 'rückt den Hut zurecht'],
      walk: ['schlurfender Gang mit `char.step`'],
      attack: ['Anticipation: weit ausholen, tief in die Knie', 'Kugel rollen lassen, Follow-through mit hochgehobenem Bein'],
      hit: ['Hut hüpft hoch'],
      spawn: ['landet, die Kugel rollt kurz nach'],
      death: ['setzt sich schwer hin, der Hut fällt herunter', 'zerbröselt in Moos und Steine'],
    },
  },
};
