// Design-Briefs: Tiere und Drachen
export default {
  'baby-dragon': {
    concept: 'Das Drachenbaby ist ein verspieltes, neugieriges Drachenkind in Türkis, das noch die obere Hälfte seiner Eierschale wie eine Mütze trägt. Es hat einen Kopf so groß wie den Bauch und Stummelflügel. Es spuckt Feuerbälle und hustet danach Rauch.',
    unique: 'Die Eierschalen-Mütze mit Zackenrand ist einmalig; das Türkis unterscheidet es von allen anderen Drachen (Elektrodrache Indigo, Infernodrache Rußrot, Phönix Gold). Drachenbabys anderer Spiele sind grün; dieses ist türkis mit Lätzchen.',
    silhouette: 'Rundlicher Körper mit riesigem Kopf, Zackenschale obenauf, zwei kleine Flügel, kurzer Schwanz.',
    mainName: 'Türkis (Schuppen)',
    accName: 'Creme (Bauch, Schale)',
    materials: [['Hörnchen', '#f0e0c0'], ['Flügelhaut', '#7fd8c8']],
    signature: 'Die obere Eierschale mit Zackenrand sitzt wie eine Mütze auf dem Kopf.',
    details: {
      kleidung: 'Eierschale, Lätzchen',
      material: 'Schuppen, Eierschale, Stoff',
      muster: 'Bauchschuppen-Ringe, Punkte auf der Schale',
      schnallen: 'Lätzchenknoten',
      abnutzung: 'Rußflecken am Lätzchen',
      accessoires: 'Lätzchen (Teamzone)',
    },
    face: 'Große, glänzende Kinderaugen, Stupsnase mit Rauchwölkchen und breites Grinsen mit einem Zahn.',
    weapon: 'Feuerball aus dem Maul.',
    anim: {
      idle: ['schielt nach der Eierschale, Schwanz wedelt', 'Flügelschlag mit `char.flap`'],
      walk: ['flattert, kippelt im Flug'],
      attack: ['holt Luft (Anticipation: Bauch bläht sich, Squash), spuckt Feuerball (Stretch), hustet Rauch'],
      hit: ['Schale rutscht übers Auge'],
      spawn: ['schlüpft aus einem Feuerball'],
      death: ['trudelt, die Schale fällt ab'],
    },
    special: { evo: 'Windstoß-Evo: Ein kleines Windrad auf der Eierschale, gefiederte Flügelspitzen und Windbänder am Schwanz. Luftwirbel bilden die Partikelhülle; jeder Angriff erzeugt einen Windstoß-Ring.' },
  },
  'electro-dragon': {
    concept: 'Der Elektrodrache ist ein nervöser, zuckender Drache in sattem Indigo mit einem Blitzableiter-Horn samt Kupferspule auf der Nase und einer statisch abstehenden Mähne. Sein Blitz springt auf bis zu drei Ziele über.',
    unique: 'Das Blitzableiter-Horn mit Spule ist einmalig; die statische Mähne ist sein Übertreibungsmerkmal. Elektrodrachen anderer Spiele sind blau-weiß; dieser ist indigo mit Kupfer.',
    silhouette: 'Schlanker Drache mit langem Hals, Horn mit Spule vorn, zackige Mähne, lange Flügel.',
    mainName: 'Indigo',
    accName: 'Blitzgelb',
    materials: [['Kupferspule', '#c87a3a'], ['Bauch', '#8a8ad0']],
    signature: 'Ein Blitzableiter-Horn mit Kupferspule auf der Nase.',
    details: {
      kleidung: 'keine',
      material: 'Schuppen, Kupfer',
      muster: 'Blitzzacken auf den Flügeln',
      schnallen: 'Spulenklammer',
      abnutzung: 'angesengte Flügelränder',
      accessoires: 'Flügelsaum (Teamzone)',
    },
    face: 'Zuckende, gelbe Augen und ein offenes Maul mit Funken zwischen den Zähnen.',
    weapon: 'Kettenblitz aus dem Maul.',
    anim: {
      idle: ['Funken zwischen Horn und Schwanzspitze, Mähne knistert'],
      walk: ['ruckartiger Flug mit `char.flap`'],
      attack: ['Horn lädt (Anticipation), Kettenblitz aus dem Maul'],
      hit: ['Mähne zuckt'],
      spawn: ['erscheint aus einem Blitz'],
      death: ['Kurzschluss, trudelt ab'],
    },
    special: { evo: 'Gewitter-Evo: Eine zweite Spule an der Schwanzspitze, leuchtende Blitzadern auf den Flügeln und eine Gewitterwolken-Mähne. Funkenregen bildet die Partikelhülle.' },
  },
  'inferno-dragon': {
    concept: 'Der Infernodrache ist ein brütender, konzentrierter Schmiededrache mit rußroten Schuppen und einem Brennglas in Messingfassung vor dem Maul. Sein Hitzestrahl wird durch die Linse gebündelt und mit jeder Stufe heißer.',
    unique: 'Das Brennglas vor dem Maul ist ein einmaliges Werkzeug; es erklärt den gebündelten Strahl. Infernodrachen anderer Spiele tragen Helme; dieser trägt eine Linse.',
    silhouette: 'Kräftiger Drache mit kurzem Hals, runde Linse vor der Schnauze, breite Flügel.',
    mainName: 'Rußrot',
    accName: 'Glutorange',
    materials: [['Linse', '#e8f4ff'], ['Messing', '#c8a046']],
    signature: 'Ein Brennglas in einer Messingfassung, mit Riemen vor dem Maul befestigt.',
    details: {
      kleidung: 'Halfter mit Linse',
      material: 'Schuppen, Messing, Glas',
      muster: 'glühende Bauchnähte',
      schnallen: 'Halfterschnallen',
      abnutzung: 'Ruß auf der Linse',
      accessoires: 'Halfterriemen (Teamzone)',
    },
    face: 'Schmale glühende Augen und rauchende Nüstern.',
    weapon: 'Hitzestrahl durch das Brennglas.',
    anim: {
      idle: ['Rauch aus den Nüstern, die Linse glänzt'],
      walk: ['schwerer Flug mit `char.flap`'],
      attack: ['Linse ausrichten (Anticipation), Strahl; die Linse glüht heller'],
      hit: ['Linse wackelt'],
      spawn: ['erscheint aus Glut'],
      death: ['Linse zerspringt, er stürzt'],
    },
    special: { evo: 'Schmelz-Evo: Eine Doppellinse (Fernrohr) und glühende Schuppenkanten kommen hinzu, die Flügelränder brennen. Glutfunken bilden die Partikelhülle; die vierte Stufe färbt den Strahl weiß.' },
  },
  phoenix: {
    concept: 'Der Phönix ist ein stolzer, feuriger Vogel in Gold-Orange mit einem Flammenkamm und langen Schleppfedern, die wie Flammenbänder flattern. Stirbt er, explodiert er und wird zum Ei; schlüpft es, kehrt er als Küken zurück.',
    unique: 'Die Flammenband-Schleppfedern und der Flammenkamm sind einmalig; drei Formen (Vogel, Ei, Küken) hat sonst niemand. Feuervögel anderer Spiele sind rot; dieser ist gold mit rosa Spitzen.',
    silhouette: 'Vogel mit weiten Flügeln und drei langen geschwungenen Schwanzbändern.',
    mainName: 'Feuergold',
    accName: 'Rosenrot (Spitzen)',
    materials: [['Schnabel', '#f0c040']],
    signature: 'Drei lange Schleppfedern, die wie Flammenbänder wehen.',
    details: {
      kleidung: 'keine',
      material: 'Federn, Feuer',
      muster: 'Federreihen mit Flammenspitzen',
      schnallen: 'keine',
      abnutzung: 'keine',
      accessoires: 'Fußring (Teamzone)',
    },
    face: 'Stolzer Blick, gebogener Schnabel und Flammenaugenbrauen.',
    weapon: 'Krallenhieb im Flug.',
    anim: {
      idle: ['Federn lodern, Kopfnicken'],
      walk: ['gleitender Flug mit `char.flap`'],
      attack: ['Krallenhieb im Sturz'],
      hit: ['Federn stieben'],
      spawn: ['steigt aus Flammen'],
      death: ['explodiert in Flammen und wird zum Ei'],
    },
    special: { forms: { egg: 'Ei: glühendes Ei mit Rissen, das pulsiert und schlüpft.', reborn: 'Küken: flaumiges Küken mit kleinem Flammenkamm, das zum Phönix heranwächst.' } },
  },
  bats: {
    concept: 'Die Fledermäuse sind fünf hibbelige, quietschende Flieger mit Ohren wie Lindenblätter und einem einzelnen langen Zahn. Sie wohnen im Glockenturm-Hut der Nachthexe und greifen im Sturzflug an.',
    unique: 'Lindenblatt-Ohren größer als der Körper und ein Einzelzahn sind einmalig. Fledermäuse anderer Spiele sind lila; diese sind schieferblau mit rosa Innenohren.',
    silhouette: 'Winzige Kugel mit zwei riesigen blattförmigen Ohren und kleinen gezackten Flügeln.',
    mainName: 'Schieferblau',
    accName: 'Rosa (Ohren innen)',
    materials: [['Flügelhaut', '#3a4560']],
    signature: 'Zwei Ohren in Lindenblatt-Form mit Blattadern und ein einzelner Zahn.',
    details: {
      kleidung: 'keine',
      material: 'Fell, Haut',
      muster: 'Blattadern in den Ohren',
      schnallen: 'keine',
      abnutzung: 'Kerbe im Ohr',
      accessoires: 'Flügelspitzen-Bänder (Teamzone)',
    },
    face: 'Große runde Augen, Stupsnase und der Einzelzahn.',
    weapon: 'Der einzelne lange Zahn, mit dem sie im Sturzflug zubeißen.',
    anim: {
      idle: ['flattern schnell im Kreis mit `char.flap`'],
      walk: ['zickzack-Flug'],
      attack: ['Sturzflug-Biss'],
      hit: ['quietscht'],
      spawn: ['fliegen aus dem Hut'],
      death: ['trudeln ab'],
    },
    special: {
      evo: 'Vampir-Evo: Ein Mini-Umhang und ein rosa leuchtender Zahn, dazu Herzpunkte an den Ohren. Rosa Glitzer bildet die Partikelhülle; jeder Biss heilt sichtbar.',
      variants: 'Ohr geknickt, Zahn links, Bauchfleck; Farbton ±6°, Größe ±5 %',
    },
  },
  minions: {
    concept: 'Die Lakaien sind drei freche, zappelige Flieger aus dem Lakaien-Labor mit einem einzelnen Stirnhorn und einem Schwanz mit Pik-Spitze. Sie spucken glühende Kugeln auf Boden und Luft.',
    unique: 'Einzelnes Stirnhorn und Pik-Schwanz in Violett sind einmalig unter den Fliegern. Lakaien anderer Spiele sind blau; diese sind violett mit orangen Augen.',
    silhouette: 'Kleiner Körper mit Horn, Fledermausflügeln und langem Pik-Schwanz.',
    mainName: 'Violett',
    accName: 'Orange (Augen, Kugeln)',
    materials: [['Flügelhaut', '#5a3a9a']],
    signature: 'Ein einzelnes gebogenes Stirnhorn und eine Pik-Spitze am Schwanz.',
    details: {
      kleidung: 'keine',
      material: 'Haut',
      muster: 'Bauchstreifen',
      schnallen: 'keine',
      abnutzung: 'Kerben in den Flügeln',
      accessoires: 'Halstuch (Teamzone)',
    },
    face: 'Orange leuchtende Augen, freches Grinsen mit Hauern.',
    weapon: 'Glühende Spuckkugel.',
    anim: {
      idle: ['flattern, zeigen auf Ziele'],
      walk: ['wellenförmiger Flug'],
      attack: ['Kopf zurück (Anticipation), spucken eine glühende Kugel'],
      hit: ['überschlagen sich'],
      spawn: ['flattern aus einem Rauchwölkchen'],
      death: ['trudeln ab und verpuffen'],
    },
    special: {
      evo: 'Horden-Evo: Ein zweites, kleineres Horn, Knochen-Armschienen und ein flackernder Schemen-Effekt beim ersten Treffer (unsichtbar). Violette Funken bilden die Partikelhülle.',
      variants: 'Horn gebogen, Horn gerade, Zahnlücke; Farbton ±6°, Größe ±5 %',
    },
  },
  'mega-minion': {
    concept: 'Der Megalakai ist ein grimmiger, schwerer Lakai mit einem Steinbauch-Panzer und Wasserspeier-Hörnern. Seine kleinen Flügel tragen ihn mühsam. Er schlägt mit einer Sturzfaust hart zu.',
    unique: 'Der steinerne Wasserspeier-Panzer und die zu kleinen Flügel unter dem schweren Bauch sind einmalig. Megalakaien anderer Spiele tragen Rüstung; dieser ist halb Wasserspeier.',
    silhouette: 'Breiter, schwerer Körper mit Steinbauch, kleine Flügel, zwei geschwungene Hörner.',
    mainName: 'Stein-Lavendelgrau',
    accName: 'Orange (Augen)',
    materials: [['Stein', '#9a96a8']],
    signature: 'Ein Steinbauch-Panzer mit Wasserspeier-Gesicht auf dem Bauch.',
    details: {
      kleidung: 'Steinpanzer',
      material: 'Stein, Haut',
      muster: 'Moos in den Steinfugen',
      schnallen: 'keine',
      abnutzung: 'Risse im Panzer',
      accessoires: 'Armbinde (Teamzone)',
    },
    face: 'Grimmige Augen und gefletschte Zähne.',
    weapon: 'Sturzfaust aus Stein mit eingelegten Eisenringen, die er im Abwärtsflug auf das Ziel rammt.',
    anim: {
      idle: ['Flügel arbeiten schwer, der Bauch schaukelt'],
      walk: ['schwerfälliger Flug'],
      attack: ['Sturzfaust von oben'],
      hit: ['Steinsplitter'],
      spawn: ['landet in der Luft mit einem Ruck'],
      death: ['stürzt wie ein Stein'],
    },
  },
  'minion-giant': {
    concept: 'Der Minion Giant ist ein träger, verfressener Laborriese mit genähten Flügeln, einer Ohrmarke und einem Kehlsack, der sich vor dem Spucken aufbläht. Er greift Gebäude aus der Ferne mit Giftspucke an.',
    unique: 'Der aufblähende Kehlsack wie bei einem Frosch ist einmalig; die genähten Flügel zeigen die Laborherkunft. Riesenlakaien anderer Spiele sind einfach größere Lakaien; dieser hat Kehlsack und Ohrmarke.',
    silhouette: 'Großer, birnenförmiger Körper mit Kehlsack, genähte Flügel.',
    mainName: 'Giftpurpur',
    accName: 'Giftgrün (Spucke, Kehlsack)',
    materials: [['Nähte', '#2a2a30']],
    signature: 'Ein grüner Kehlsack, der sich vor dem Spucken wie ein Ballon aufbläht.',
    details: {
      kleidung: 'Ohrmarke',
      material: 'Haut, Nähte',
      muster: 'Nahtlinien an den Flügeln',
      schnallen: 'Ohrmarke',
      abnutzung: 'Flicken',
      accessoires: 'Ohrmarke und Armbinde (Teamzonen)',
    },
    face: 'Hängende Lider, Doppelkinn, sabbernder Mund.',
    weapon: 'Giftspucke aus dem aufgeblähten Kehlsack: grüne Klumpen, die im Bogen fliegen und zischend zerplatzen.',
    anim: {
      idle: ['Kehlsack bläht sich langsam'],
      walk: ['schwerfälliger Flug'],
      attack: ['Kehlsack bläht sich auf (Anticipation), Giftspucke im Bogen'],
      hit: ['Kehlsack zischt'],
      spawn: ['plumpst in die Luft'],
      death: ['Kehlsack platzt, er sinkt'],
    },
  },
  'royal-hogs': {
    concept: 'Die Königsschweinchen sind vier stolze, quiekende Ferkel in Rosé-Creme mit Minikronen zwischen den Ohren und Schleifen am Ringelschwanz. Sie greifen Gebäude an und springen über den Fluss.',
    unique: 'Minikrone plus Schleife am Ringelschwanz (Teamzone) sind einmalig. Das Fluch-Schwein trägt einen Hexenhut, das Reitschwein eine Karotte vor der Nase. Königsschweine anderer Spiele sind rosa mit Krone; diese sind rosé-creme mit Schleife.',
    silhouette: 'Kleines rundes Schwein mit großer Schnauze und Krönchen oben.',
    mainName: 'Rosé-Creme',
    accName: 'Kronengold',
    materials: [['Schnauze', '#e8a090'], ['Hufe', '#5a4a40']],
    signature: 'Eine Minikrone mit drei Zacken zwischen den Ohren.',
    details: {
      kleidung: 'Krone, Schwanzschleife',
      material: 'Gold, Seide',
      muster: 'Flecken (Varianten)',
      schnallen: 'keine',
      abnutzung: 'schiefe Krone',
      accessoires: 'Schleife am Ringelschwanz (Teamzone)',
    },
    face: 'Stolze Augen, große Schnauze, Doppelkinn.',
    weapon: 'Kopfstoß mit der Krone.',
    anim: {
      idle: ['schnüffeln, Ohren wackeln'],
      walk: ['trippeln mit wackelndem Hinterteil'],
      attack: ['Kopfstoß mit Kronenspitze'],
      hit: ['quieken'],
      spawn: ['plumpsen herab'],
      death: ['fallen auf den Rücken'],
    },
    special: {
      evo: 'Flug-Evo: kleine Federflügel mit Goldrand und eine Fliegerbrille unter der Krone. Federn bilden die Partikelhülle; beim Absturz macht es Landeschaden.',
      variants: 'Fleck am Ohr, Krone schief, Doppelkinn; Farbton ±6°, Größe ±5 %',
    },
  },
  'cursed-hog': {
    concept: 'Das Fluch-Schwein ist ein verwirrtes, grantiges Ferkel in Fluchlila mit einem Mini-Hexenhut und Fluchsternchen um den Kopf. Es entsteht aus einer verfluchten Truppe und kämpft für die Hexenmutter.',
    unique: 'Der Mini-Hexenhut und die Fluchsternchen sind einmalig unter den Schweinen. Verwandelte Tiere anderer Spiele sind normale Schweine; dieses trägt einen Hexenhut.',
    silhouette: 'Kleines Schwein mit spitzem Hut.',
    mainName: 'Fluchlila',
    accName: 'Giftgrün (Sternchen, Hutband)',
    materials: [['Hut', '#3a2a4a']],
    signature: 'Ein Mini-Hexenhut mit Knick und kreisende Fluchsternchen.',
    details: {
      kleidung: 'Hexenhut',
      material: 'Filz',
      muster: 'Sternchen',
      schnallen: 'keine',
      abnutzung: 'keine',
      accessoires: 'Hutband (Teamzone)',
    },
    face: 'Verwirrter Blick mit Spiralaugen, grantiger Mund.',
    weapon: 'Ein Rammstoß mit dem Schweinekopf, bei dem der Hexenhut nach hinten kippt.',
    anim: {
      idle: ['grunzt, Sternchen kreisen'],
      walk: ['trippeln'],
      attack: ['Rammstoß'],
      hit: ['Hut fliegt hoch'],
      spawn: ['verwandelt sich aus Fluchrauch'],
      death: ['verpufft in Fluchrauch'],
    },
    special: { extra: '**Flusssprung (`JUMP`):** Hut hält er mit den Ohren fest.' },
  },
  rhino: {
    concept: 'Das Nashorn ist das sture, schnaubende Reittier des Dunklen Prinzen als Helden. Es hat ein Doppelhorn mit Sichelmond-Schutzplatte und Panzerfalten wie Plattenrüstung. Springt der Prinz ab, stürmt es allein auf Gebäude.',
    unique: 'Doppelhorn mit Sichelmond-Platte und Satteldecke ist einmalig. Kampfnashörner anderer Spiele sind grau ohne Wappen; dieses trägt das Sichelmond-Wappen des Prinzen.',
    silhouette: 'Breites Vierbeiner-Rechteck mit großem Kopf und zwei Hörnern.',
    mainName: 'Graugrün',
    accName: 'Messing (Platte)',
    materials: [['Satteldecke', '#ff00f1']],
    signature: 'Ein Doppelhorn mit einer Sichelmond-Schutzplatte aus Messing auf der Stirn.',
    details: {
      kleidung: 'Satteldecke, Stirnplatte',
      material: 'Haut, Messing',
      muster: 'Panzerfalten',
      schnallen: 'Gurte',
      abnutzung: 'Kratzer',
      accessoires: 'Satteldecke (Teamzone)',
    },
    face: 'Kleine sture Augen, schnaubende Nüstern.',
    weapon: 'Doppelhorn mit Sichelmond-Platte aus Messing, mit dem es Gebäude rammt.',
    anim: {
      idle: ['scharrt mit dem Huf'],
      walk: ['schwerer Trab mit `char.step`'],
      attack: ['Kopf senken (Anticipation), Hornstoß'],
      hit: ['schnaubt'],
      spawn: ['erscheint, wenn der Prinz abspringt'],
      death: ['fällt auf die Seite'],
    },
    special: { extra: '**Ansturm (`charge`):** gesenkter Kopf, Staubfahne.' },
  },
};
