// Design-Briefs: Werkstatt (Mechanik, Dampf, Elektrik)
export default {
  'electro-giant': {
    concept: 'Der Elektroriese ist ein grimmiger Elektriker im ziegelorangen Arbeitsoverall mit Schweißervisier. Auf seinen Schultern sitzen zwei Teslaspulen als Polster, und er trägt riesige Gummihandschuhe. Wer ihn aus der Nähe angreift, bekommt einen Gegenschlag mit Betäubung.',
    unique: 'Die Teslaspulen auf beiden Schultern mit springenden Funken bilden eine zackige Schulterlinie, die kein anderer Riese hat; das hochgeklappte Schweißervisier ist sein Gesicht. Der Riese trägt eine Bommelmütze, der Runenriese eine Tafel. Elektroriesen anderer Spiele tragen blaue Anzüge; dieser trägt einen ziegelorangen Overall mit Kabeltrommel.',
    silhouette: 'Massig mit zwei hohen Spulen über den Schultern, kleiner Kopf mit Visierplatte, riesige Handschuhe.',
    mainName: 'Ziegelorange (Overall)',
    accName: 'Blitz-Cyan (Funken, Spulenkappen)',
    materials: [['Gummihandschuhe', '#3a3a40'], ['Kupferspulen', '#c87a3a'], ['Visier', '#5a6070']],
    signature: 'Zwei Kupfer-Teslaspulen mit Kugelkappen sitzen als Schulterpolster; zwischen ihnen springen Funken.',
    details: {
      kleidung: 'Arbeitsoverall mit Brusttasche, Schweißervisier, Gummihandschuhe, Sicherheitsstiefel',
      material: 'Drillich, Gummi, Kupfer, Glas',
      muster: 'Warnstreifen am Ärmel, Spulenwicklung',
      schnallen: 'Werkzeuggürtel mit Kabeltrommel',
      abnutzung: 'Brandflecken, verkohlte Ärmelenden',
      accessoires: 'Gürtel und Helmstreifen (Teamzonen), Prüfschraubenzieher in der Brusttasche',
    },
    face: 'Hinter dem hochgeklappten Visier ein grimmiges Gesicht mit Stoppelbart, gerunzelter Stirn und knurrend gefletschten Zähnen. Beim Gegenschlag fällt das Visier herunter und die Gläser blitzen.',
    weapon: 'Fäuste in Gummihandschuhen, die beim Schlag elektrisch aufleuchten.',
    anim: {
      idle: ['Funken springen zwischen den Spulen', 'reibt die Handschuhe'],
      walk: ['schwerer Stampfgang mit `char.step`, Funken'],
      attack: ['Faust hoch, die Spulen laden (Anticipation), Schlag nach unten mit Entladung'],
      hit: ['Spulen blitzen auf (Gegenschlag)'],
      spawn: ['landet, Visier klappt mit Funkenregen herunter'],
      death: ['Kurzschluss: Rauch aus den Spulen, er kippt um'],
    },
  },
  pekka: {
    concept: 'P.E.K.K.A. ist ein schwer gepanzerter, stummer Kampfautomat aus dunkler Bronze. Statt eines Kopfes hat er eine Glaslaterne, in der eine türkisfarbene Flamme brennt. Er schwingt ein Fallbeil-Schwert, das länger ist als sein Rumpf, und ist unaufhaltsam.',
    unique: 'Der Laternenkopf mit Flamme ist eine Kopfform, die keine andere Figur hat, und das Fallbeil-Schwert ist trapezförmig wie eine Guillotine. Mini-P.E.K.K.A. ist ein kleiner Kessel mit Dampfpfeife. Kampfroboter anderer Spiele haben Hörnerhelme und leuchtende Augen; dieser hat eine Laterne mit Flamme.',
    silhouette: 'Hoch und massiv mit spitzen Schulterplatten; oben die sechseckige Laterne, rechts das breite Fallbeil fast bis zum Boden.',
    mainName: 'Dunkelbronze (Panzer)',
    accName: 'Türkisflamme',
    materials: [['Laternenglas', '#bfe8e0'], ['Stahl (Klinge)', '#a8b0ba'], ['Gelenke', '#2e2622']],
    signature: 'Eine sechseckige Laterne mit Messingdach und Gitter, in der eine türkise Flamme flackert; ihre Form zeigt den Ausdruck.',
    details: {
      kleidung: 'Plattenpanzer mit Nietreihen, gestaffelte Schulterplatten, Kniekacheln, Stulpenhandschuhe',
      material: 'Bronze, Stahl, Glas, Leder an den Gelenken',
      muster: 'Nietreihen, Plattenränder mit Gravur',
      schnallen: 'Lederriemen an den Gelenken, Messingklammern',
      abnutzung: 'Grünspan an den Kanten, Kerben im Fallbeil',
      accessoires: 'Brustwappen und Schulterwimpel (Teamzonen)',
    },
    face: 'Die Flamme ist das Gesicht: ruhig züngelnd im Idle, hoch auflodernd und spitz im Angriff, flackernd und klein, wenn getroffen.',
    weapon: 'Fallbeil-Schwert: trapezförmige, schräg geschliffene Klinge an einem langen Griff mit Ring.',
    anim: {
      idle: ['Flamme flackert, Kolben zischen leise', 'Fallbeil hängt schwer neben dem Bein, die Spitze knapp über dem Boden'],
      walk: ['schwerer, ruckhafter Schritt mit `char.step`'],
      attack: ['Klinge weit über den Kopf (Anticipation, Stretch), Fallbeil-Hieb mit Funken (Squash)', 'Flamme lodert auf'],
      hit: ['Flamme duckt sich, Glas klirrt'],
      spawn: ['landet, Flamme entzündet sich'],
      death: ['Flamme erlischt, Panzer fällt in Teile auseinander'],
    },
    special: { evo: 'Seelenfresser-Evo: Die Laterne bekommt eine zweite, innere Flamme, Brustpanzer und Klinge leuchtende türkise Fugen, dazu kommen Ketten über den Schultern. Glühende Funken bilden die Partikelhülle; bei jedem Sieg steigt eine Flamme in die Laterne.' },
  },
  'mini-pekka': {
    concept: 'Mini-P.E.K.K.A. ist ein kleiner, eifriger Kessel-Automat aus Zinn mit einem großen Zyklopenauge und einer Dampfpfeife auf dem Kopf. Er kämpft mit einer Riesen-Rohrzange und pfeift bei jedem Schlag. Er ist tollpatschig, aber trifft verheerend.',
    unique: 'Die Dampfpfeife, die beim Schlag pfeift, und das große Zyklopenauge geben ihm ein freundliches Gesicht, das keine andere Maschine hat; die Rohrzange als Waffe gibt es nur bei ihm. P.E.K.K.A. hat Laterne und Fallbeil. Kleine Kampfroboter anderer Spiele tragen Hörner und Schwerter; dieser ist ein Wasserkessel mit Werkzeug.',
    silhouette: 'Kugeliger Kessel auf kurzen Beinen, oben die Pfeife; die Rohrzange ragt höher als er selbst.',
    mainName: 'Zinngrau (Kessel)',
    accName: 'Glutorange (Pfeife, Auge)',
    materials: [['Rohrzange', '#b03a2a'], ['Auge', '#ffd8a8'], ['Nieten', '#c8ccd2']],
    signature: 'Eine Messing-Dampfpfeife auf dem Kesseldeckel, die beim Schlagen einen Dampfstrahl ausstößt.',
    details: {
      kleidung: 'Kesselkörper mit Deckel, Rohrarme mit Gelenken, Stummelbeine mit breiten Füßen',
      material: 'Zinn, Messing, Gusseisen',
      muster: 'Nietreihen, Wasserstands-Skala am Bauch',
      schnallen: 'Deckelscharnier, Bolzen an den Gelenken',
      abnutzung: 'Kalkflecken, Dellen',
      accessoires: 'Brustplakette und Pfeifenband (Teamzonen), kleines Manometer',
    },
    face: 'Ein großes rundes Zyklopenauge mit Messingrand; das Lid ist eine Klappe, die den Ausdruck formt (eifrig offen, im Angriff schmal, getroffen zugekniffen).',
    weapon: 'Riesen-Rohrzange mit gezahnten Backen und orangem Griff.',
    anim: {
      idle: ['tippelt auf der Stelle, Dampfwölkchen aus der Pfeife', 'Auge blinzelt mit Klappe'],
      walk: ['schneller Tippelgang, Kessel wackelt'],
      attack: ['Zange über den Kopf (Anticipation, Stretch), Schlag mit Pfiff und Dampfstrahl (Squash)'],
      hit: ['Deckel springt kurz hoch'],
      spawn: ['plumpst herunter, die Pfeife pfeift'],
      death: ['Dampf entweicht zischend, er kippt um, der Deckel rollt'],
    },
  },
  sparky: {
    concept: 'Funki ist ein käferförmiger Lade-Panzer mit sechs Beinen und einer großen Kondensator-Schüssel auf dem Rücken. Leuchtende Ladebalken zeigen, wie weit er geladen ist. Ist er voll, entlädt er einen gewaltigen Flächenschuss, der ihn selbst nach hinten wirft.',
    unique: 'Käferpanzer auf sechs Beinen mit Parabolschüssel ist eine Silhouette, die sonst nicht vorkommt; die Ladebalken sind sein Gesicht. Kanonen anderer Figuren sind Fisch- oder Löwenmäuler. Ladekanonen anderer Spiele fahren auf Rädern; diese krabbelt auf Käferbeinen.',
    silhouette: 'Breiter, flacher Käferpanzer auf sechs dünnen Beinen, darüber die große, schräge Schüssel mit Antenne.',
    mainName: 'Käfergrün (Panzer)',
    accName: 'Lade-Cyan (Balken, Spulen)',
    materials: [['Schüssel (Kupfer)', '#c87a40'], ['Beine', '#2c3a2c'], ['Glaskolben', '#d8fbff']],
    signature: 'Eine Kondensator-Schüssel aus Kupfer mit Spule im Brennpunkt und fünf Ladebalken am Rand.',
    details: {
      kleidung: 'Käferpanzer mit Flügeldecken-Naht, Spulen, Kabel',
      material: 'lackiertes Blech, Kupfer, Glas',
      muster: 'Panzerstreifen, Kabelwicklung',
      schnallen: 'Klammern an den Flügeldecken',
      abnutzung: 'Brandflecken an der Schüssel',
      accessoires: 'Panzerstreifen und Antennenwimpel (Teamzonen)',
    },
    face: 'Zwei runde Frontlampen als Augen und die Ladebalken als „Mund“: leer ein gelangweiltes Gesicht, voll ein breites Grinsen.',
    weapon: 'Die Kondensator-Schüssel feuert eine weiße Entladung.',
    anim: {
      idle: ['Ladebalken füllen sich nacheinander, Beine trippeln'],
      walk: ['Krabbeln mit wellenförmigem Beintakt'],
      attack: ['Schüssel richtet sich aus, glüht (Anticipation), gewaltiger Schuss mit Rückstoß, Beine rutschen'],
      hit: ['Balken flackern; Betäubung löscht sie'],
      spawn: ['landet auf dem Rücken und dreht sich auf die Beine'],
      death: ['Kurzschluss, die Schüssel klappt zusammen, Rauch'],
    },
  },
  zappies: {
    concept: 'Die Zappys sind drei kleine, aufgekratzte Zap-Roboter mit Glühbirnen-Köpfen und Batterie-Rucksäcken, die auf Federbeinen hüpfen. Ihre Treffer betäuben kurz, und beim Reden flackern sie.',
    unique: 'Der Glühbirnen-Kopf mit sichtbarem Glühfaden ist eine Kopfform, die niemand sonst hat; die übergroße Batterie mit Plus-Pol ist ihr übertriebenes Merkmal. Andere Maschinen haben Laterne, Kessel oder Käferpanzer. Kleine Zap-Roboter anderer Spiele sind Kugeln mit Antennen; diese sind Glühbirnen-Männchen.',
    silhouette: 'Kleiner Zylinderkörper auf Federbeinen, oben die birnenförmige Glaskugel, hinten der große Batterie-Zylinder.',
    mainName: 'Silbergrau (Gehäuse)',
    accName: 'Glühgelb (Birne, Funken)',
    materials: [['Batterie', '#2f3640'], ['Federn', '#9aa3ad'], ['Fassung (Messing)', '#c8a046']],
    signature: 'Glühbirnen-Kopf mit Wendelfaden und Messingfassung; bei jedem Zap leuchtet der Faden auf.',
    details: {
      kleidung: 'Blechgehäuse, Federbeine, Batterie-Rucksack mit Pol-Kappen',
      material: 'Blech, Glas, Messing, Gummi',
      muster: 'Rillen der Fassung, Batteriestreifen',
      schnallen: 'Batterieklemmen',
      abnutzung: 'kleine Delle im Gehäuse',
      accessoires: 'Batteriestreifen und Fußkappen (Teamzonen)',
    },
    face: 'Zwei Punktaugen und ein Strichmund im Glas der Birne, gezeichnet als Glühfaden; zappelig mal grinsend, mal erschrocken.',
    weapon: 'Antenne am Kopf mit Kugelende, aus der der Zap-Blitz springt.',
    anim: {
      idle: ['Birne flackert, Federbeine wippen'],
      walk: ['hüpfen auf Federn'],
      attack: ['Birne leuchtet auf (Anticipation), Blitz aus der Antenne'],
      hit: ['Birne flackert aus und wieder an'],
      spawn: ['federn beim Landen nach'],
      death: ['Birne zerplatzt mit Funken'],
    },
    special: { variants: 'Birne rund, Birne spitz, Birne gedreht; Farbton ±6°, Größe ±5 %' },
  },
  'flying-machine': {
    concept: 'Die Flugmaschine ist ein Ornithopter aus Segeltuch-Schlagflügeln mit Holzrippen und einem kleinen Teekessel-Dampfantrieb. Eine Pilotin mit Fliegerkappe kurbelt, und vorn sitzt eine kleine Bugkanone. Sie ist ein fliegender Geschützturm mit großer Reichweite.',
    unique: 'Schlagflügel aus Segeltuch (keine Propeller-Tragflächen) und eine kurbelnde Pilotin sind einmalig; die Silhouette ist eine breite Fledermaus-Form aus Stoff. Flieger anderer Spiele sind Holz-Doppeldecker; dieser ist ein Schlagflügler mit Kessel.',
    silhouette: 'Sehr breit: zwei geschwungene Segeltuchflügel mit Rippen, in der Mitte ein schmaler Holzrumpf mit Kessel und Pilotin.',
    mainName: 'Segeltuch-Leinen (Flügel)',
    accName: 'Lindgrün (Rahmen, Kessel)',
    materials: [['Holzrippen', '#8a5a32'], ['Messingkessel', '#c8a046'], ['Fliegerkappe', '#5a3a28']],
    signature: 'Zwei Schlagflügel aus Segeltuch mit fünf Holzrippen, die wie Fledermausflügel auf- und abschlagen.',
    details: {
      kleidung: 'Pilotin mit Lederkappe, Schutzbrille und Schal',
      material: 'Leinen, Holz, Messing, Leder',
      muster: 'Nähte zwischen den Rippen, Flicken im Tuch',
      schnallen: 'Spannschnüre, Messingösen',
      abnutzung: 'Rußfahne vom Kessel',
      accessoires: 'Flügelstreifen und Pilotenschal (Teamzonen)',
    },
    face: 'Pilotin mit runden Brillengläsern, Zunge im Mundwinkel, konzentriertem Blick; beim Schuss kneift sie die Augen zu.',
    weapon: 'Kleine Bugkanone aus Messing auf einem Drehzapfen.',
    anim: {
      idle: ['Flügel schlagen gleichmäßig mit `char.flap`, Kessel dampft', 'Pilotin kurbelt'],
      walk: ['schnellerer Flügelschlag, leichtes Neigen nach vorn'],
      attack: ['Kanone zielt (Anticipation), Schuss mit Rückstoß, das Gestell ruckt'],
      hit: ['Tuch reißt kurz auf, die Pilotin duckt sich'],
      spawn: ['fliegt mit kräftigem Schlag ein'],
      death: ['Flügel klappen zusammen, sie trudelt mit Rauch herab'],
    },
  },
  furnace: {
    concept: 'Der Ofen ist ein brummiger, laufender Kanonenofen aus Eisen mit Ofenrohr als hohem Hut und einer glühenden Klappe als Bauch. Er spuckt Glut auf Gegner und lässt alle paar Sekunden einen Feuergeist aus der Klappe hüpfen.',
    unique: 'Ein Kanonenofen auf kurzen Eisenbeinen mit glühender Bauchklappe ist eine Form, die nur er hat; das Ofenrohr als Zylinder ist sein Hut. Die Ofen-Augen schauen durch das Klappengitter. Laufende Öfen anderer Spiele sind Schmelzöfen auf Rädern; dieser ist ein Bollerofen mit Füßen.',
    silhouette: 'Rundbauchiger Ofen auf Stummelbeinen mit hohem, leicht geknicktem Rohr; vorn die runde Klappe mit Glut.',
    mainName: 'Gusseisen-Blaugrau',
    accName: 'Glut-Orange',
    materials: [['Glut', '#ffd27a'], ['Kohle', '#2a2228'], ['Messinggriff', '#c8a046']],
    signature: 'Eine runde Ofenklappe mit Gitter, hinter der Glut glüht; geht sie auf, hüpft ein Feuergeist heraus.',
    details: {
      kleidung: 'Ofenkörper mit Zierleisten, Ofenrohr-Hut, Eisenbeine mit Klauenfüßen',
      material: 'Gusseisen, Messing, Glut',
      muster: 'Ornament-Relief am Bauch, Nietreihen',
      schnallen: 'Klappenriegel, Rohrschellen',
      abnutzung: 'Rost am Fuß, Rußfahne am Rohr',
      accessoires: 'Ofenrohr-Band und Henkeltuch (Teamzonen), Kohlenschaufel am Rücken',
    },
    face: 'Zwei glühende Augen hinter dem Klappengitter und ein Mund aus der Klappenöffnung; brummig im Idle, die Klappe weit offen im Angriff.',
    weapon: 'Die Ofenklappe spuckt Glutbrocken.',
    anim: {
      idle: ['pafft Rauchringe aus dem Rohr'],
      walk: ['watschelnder Gang auf Eisenbeinen, scheppernd'],
      attack: ['Klappe öffnet sich (Anticipation), Glutbrocken fliegen'],
      hit: ['Funken stieben aus dem Rohr'],
      spawn: ['landet mit Aschewolke'],
      death: ['Ofen kühlt aus: Glut erlischt, er fällt scheppernd auseinander'],
    },
    special: { evo: 'Schmelz-Evo: Zwei seitliche Klappen und ein Doppelrohr mit glühenden Nähten kommen hinzu, das Eisen wird rotglühend gefleckt. Glutfunken bilden die Partikelhülle, beim Spuckern öffnen sich die Seitenklappen.' },
  },
  'cannon-cart': {
    concept: 'Die Kanonenkarre ist ein Kanonenrohr in Form eines Hechtkopfs auf einer Schubkarre, die ein kleiner Kanonier mit Ohrenschützern schiebt. Sie fährt und feuert. Unter halbem Leben bricht der Karren zusammen und das Rohr bleibt auf einem Dreibein als feste Kanone stehen.',
    unique: 'Das Kanonenrohr als Hechtkopf mit Zähnen an der Mündung ist einmalig; andere Kanonen sind Löwenmaul oder Schüssel. Fahrende Kanonen anderer Spiele sind graue Lafetten; diese ist eine bunte Schubkarre mit Fischkanone und Kanonier.',
    silhouette: 'Flach und lang: Karre mit Rad vorn, darauf das schräg nach vorn zeigende Fischrohr, hinten der kleine Kanonier an den Griffen.',
    mainName: 'Petrol (Rohr, Karre)',
    accName: 'Messing (Beschläge, Flossen)',
    materials: [['Karrenholz', '#8a5a32'], ['Kanonier-Haut', '#e8b08a'], ['Ohrenschützer', '#f2efe6']],
    signature: 'Das Rohr ist ein Hechtkopf mit Flossenkamm; die Mündung ist das Fischmaul mit Zahnreihe.',
    details: {
      kleidung: 'Kanonier mit Wollmütze, Ohrenschützern, Schürze und Stiefeln',
      material: 'Bronze, Holz, Messing, Wolle',
      muster: 'Schuppenmuster am Rohr, Holzmaserung',
      schnallen: 'Messingbänder um das Rohr, Radnabe',
      abnutzung: 'Ruß am Fischmaul',
      accessoires: 'Karrenwimpel und Ohrenschützer (Teamzonen), Fernrohr in der Schürze',
    },
    face: 'Der Fischkopf hat ein großes, rundes Auge, das zum Ziel schaut. Der Kanonier hat runde Wangen und pfeift durch eine Zahnlücke; beim Schuss hält er sich die Ohren zu.',
    weapon: 'Hechtkopf-Kanone aus Bronze auf einer Schubkarre.',
    anim: {
      idle: ['Kanonier schaut durchs Fernrohr', 'das Fischauge blinzelt'],
      walk: ['Karre rollt, Kanonier schiebt'],
      attack: ['Rohr ruckt zurück, Rauch aus dem Fischmaul, der Kanonier hält sich die Ohren'],
      hit: ['Karre ruckelt'],
      spawn: ['landet auf dem Rad und rollt an'],
      death: ['Rohr zerspringt, der Kanonier rennt weg'],
    },
    special: { forms: { cannon: 'Feste Kanone: Die Karre ist zerbrochen, das Rohr steht auf einem Dreibein aus Karrenstangen, der Kanonier hockt dahinter und hält sich bei jedem Schuss die Ohren zu.' } },
  },
};
