// Design-Briefs: Zirkel (Magie)
export default {
  wizard: {
    concept: 'Der Magier ist ein theatralischer Feuermagier in einer weinroten Robe mit Ballonärmeln. Neben ihm schwebt ein fliegendes Zauberbuch, das auf Kommando aufschnappt und Feuerbälle spuckt. Er dirigiert es wie ein Orchester.',
    unique: 'Das schwebende, feuerspuckende Buch als Begleiter ist einmalig; kein anderer Magier zaubert über ein lebendes Objekt. Der Eismagier hat einen Schneekugel-Stab, der Elektromagier Blitzflaschen. Feuermagier anderer Spiele schleudern Feuer aus den Händen; dieser lässt sein Buch spucken.',
    silhouette: 'Dreieck aus weiter Robe, oben ein schiefer, spitzer Hut; an der Seite schwebt ein offenes Buch, die Ärmel sind große Ballons.',
    mainName: 'Weinrot (Robe)',
    accName: 'Glutorange (Buchseiten, Feuer)',
    materials: [['Buchleder', '#5a3a28'], ['Bart', '#d8d0c4'], ['Haut', '#e8b894']],
    signature: 'Ein dickes, ledergebundenes Buch mit Zahnseiten und Schnalle, das schwebt und Feuer spuckt.',
    details: {
      kleidung: 'Robe mit Ballonärmeln, spitzer Hut mit Knick, Schnabelschuhe',
      material: 'Samt, Leder, Pergament',
      muster: 'Flammenstickerei am Saum, Sterne am Hut',
      schnallen: 'Buchschnalle, Gürtelschnalle mit Flamme',
      abnutzung: 'angesengte Ärmel',
      accessoires: 'Gürtelschärpe und Hutband (Teamzonen), Lesezeichen-Bänder am Buch',
    },
    face: 'Langes Gesicht mit spitzem Bart, theatralisch hochgezogenen Brauen und deklamierend offenem Mund.',
    weapon: 'Das fliegende Zauberbuch; er dirigiert mit einem kurzen Taktstock.',
    anim: {
      idle: ['blättert im schwebenden Buch, das gähnt', 'Ärmel blähen sich'],
      walk: ['wehender Schritt, das Buch folgt'],
      attack: ['hebt den Taktstock (Anticipation), das Buch schnappt auf und spuckt einen Feuerball'],
      hit: ['Hut verrutscht, das Buch klappt zu'],
      spawn: ['landet in einer Rauchwolke, das Buch flattert auf'],
      death: ['sinkt zusammen, das Buch fällt und schlägt zu'],
    },
    special: { evo: 'Feuerschild-Evo: Ein Kranz aus Flammenblättern kreist um ihn, das Buch bekommt einen goldenen Feuer-Einband, die Robe glühende Säume. Flammenzungen bilden die Partikelhülle; zerbricht der Schild, platzt der Kranz auseinander.' },
  },
  'ice-wizard': {
    concept: 'Der Eismagier ist ein gelassener, etwas schusseliger alter Magier im frostweißen Pelzmantel mit einem Eiszapfen-Bart bis zum Gürtel. Er schwenkt einen Stab mit einer Schneekugel und verlangsamt Gegner mit Eissplittern.',
    unique: 'Der Stab mit Schneekugel, in der eine kleine Winterlandschaft schneit, ist einmalig; der Eiszapfen-Bart ist sein Übertreibungsmerkmal. Der Magier hat ein Buch, der Elektromagier Flaschen. Eismagier anderer Spiele tragen blaue Kapuzen mit Kristallen; dieser trägt einen Pelzmantel mit lavendelfarbenem Futter.',
    silhouette: 'Dreieck aus Pelzmantel, oben eine runde Pelzmütze, der Bart hängt als Zapfenbündel herab, der Stab trägt eine runde Kugel.',
    mainName: 'Frostweiß (Pelzmantel)',
    accName: 'Lavendel (Futter, Kugelsockel)',
    materials: [['Eis', '#bfeaff'], ['Haut', '#f0e4dc'], ['Stab (Birke)', '#e8dcc8']],
    signature: 'Eine Schneekugel mit Tannenbäumchen und Häuschen auf einem Birkenstab; geschüttelt schneit es.',
    details: {
      kleidung: 'Pelzmantel, Pelzmütze, Fäustlinge, Fellstiefel',
      material: 'Pelz, Wolle, Glas, Eis',
      muster: 'Schneeflocken-Stickerei, Pelzstriche',
      schnallen: 'Eiszapfen-Knöpfe',
      abnutzung: 'Raureif an den Säumen',
      accessoires: 'Schal und Mantelsaum (Teamzonen)',
    },
    face: 'Rundes, rosiges Gesicht mit Brille auf der Nasenspitze, freundlichen Lachfalten und einem Bart aus Eiszapfen.',
    weapon: 'Birkenstab mit Schneekugel, in der Tannen und ein Häuschen im Schneegestöber stehen; der Stab ist mit Eis überzogen.',
    anim: {
      idle: ['schüttelt die Schneekugel und staunt'],
      walk: ['gemächlicher Schritt, der Bart klirrt'],
      attack: ['schwenkt die Kugel (Anticipation), Eissplitter-Fächer'],
      hit: ['Bart klirrt, ein Zapfen bricht'],
      spawn: ['landet mit Frostschlag, Schneeflocken'],
      death: ['friert zu einer Eisstatue ein und zerbröselt'],
    },
  },
  'electro-wizard': {
    concept: 'Der Elektromagier ist ein exzentrischer Erfinder-Magier mit einem Rucksack aus gläsernen Blitzflaschen in Kupferbügeln und Spulen-Handschuhen. Er trifft zwei Ziele gleichzeitig und landet mit einem Elektroschlag. Er grinst manisch.',
    unique: 'Der Blitzflaschen-Rucksack mit leuchtenden Glasbehältern und die Kupferspulen-Handschuhe sind einmalig. Der Elektroriese hat Schulterspulen, der Elektrodrache ein Horn. Elektromagier anderer Spiele haben stachelige Haare; dieser trägt eine Schutzbrille und einen Kragenmantel.',
    silhouette: 'Hoch und schmal im langen Mantel; hinten ragen drei Flaschen über die Schultern, vorn sind die Hände gespreizt.',
    mainName: 'Petrolblau (Mantel)',
    accName: 'Blitzgelb (Flascheninhalt, Funken)',
    materials: [['Kupfer', '#c87a3a'], ['Glas', '#d8f6ff'], ['Haut', '#e8c0a0']],
    signature: 'Drei Leidener Flaschen in einem Kupfergestell auf dem Rücken, verbunden mit Kabeln zu den Handschuhen.',
    details: {
      kleidung: 'Kragenmantel, Weste mit Taschenuhr, Schutzbrille auf der Stirn, Gamaschen',
      material: 'Wolle, Kupfer, Glas, Gummi',
      muster: 'Blitz-Paspel, Spulenwicklung',
      schnallen: 'Kupferklammern am Gestell',
      abnutzung: 'angesengte Haarspitzen',
      accessoires: 'Mantelkragen und Brillenband (Teamzonen)',
    },
    face: 'Schmales Gesicht mit manischem Grinsen, weit aufgerissenen Augen und statisch zu Berge stehendem Schnurrbart.',
    weapon: 'Spulen-Handschuhe, aus denen zwei Blitze gleichzeitig springen.',
    anim: {
      idle: ['Funken knistern zwischen den Fingern'],
      walk: ['eiliger Schritt, die Flaschen schwappen leuchtend'],
      attack: ['beide Hände vor (Anticipation: Flaschen laden), zwei Blitze'],
      hit: ['Kurzschluss-Zucken, die Haare stehen ab'],
      spawn: ['landet mit Elektroschlag (`char.land`)'],
      death: ['Flaschen platzen, er sinkt mit Rauchschwaden zusammen'],
    },
  },
  witch: {
    concept: 'Die Hexe ist eine gackernde, verschlagene Zauberin mit einem zweimal geknickten Hut, auf dessen Spitze eine Krähe sitzt. Ihr Stab ist ein Knochen-Windspiel. Sie schießt Geisterkugeln und ruft alle paar Sekunden Skelette.',
    unique: 'Die Krähe auf der Hutspitze ist ein lebender Begleiter, den nur sie hat; das Knochen-Windspiel klingt bei jedem Zauber. Die Nachthexe hat einen Glockenturm-Hut, die Hexenmutter einen Kessel. Hexen anderer Spiele tragen Lila mit Schädelstab; diese trägt Moosgrün mit Krähe.',
    silhouette: 'Hoch und schmal, oben der doppelt geknickte Hut mit Krähe, der Stab hängt voller Knochen-Röhrchen.',
    mainName: 'Moosgrün (Mantel, Hut)',
    accName: 'Flieder (Futter, Geisterkugeln)',
    materials: [['Krähe', '#2a2632'], ['Knochen', '#e8dfc8'], ['Haut', '#d8c8a8']],
    signature: 'Eine Krähe mit gelbem Schnabel sitzt auf der Hutspitze und schlägt beim Zaubern mit den Flügeln.',
    details: {
      kleidung: 'doppelt geknickter Hut, Mantel mit Zackensaum, Schnabelschuhe',
      material: 'Wollfilz, Knochen, Federn',
      muster: 'Flicken mit Sternen, Zackensaum',
      schnallen: 'Knochenknöpfe',
      abnutzung: 'Löcher im Hut',
      accessoires: 'Hutband und Mantelfutter (Teamzonen)',
    },
    face: 'Spitze Nase und spitzes Kinn, schiefes Grinsen mit einem Zahn, funkelnde schmale Augen.',
    weapon: 'Knochen-Windspiel-Stab: ein krummer Ast mit fünf hängenden Knochenröhrchen.',
    anim: {
      idle: ['die Krähe putzt sich, das Windspiel klimpert'],
      walk: ['schleichender Schritt, Hut wippt'],
      attack: ['Stab nach vorn (Anticipation), Windspiel klingt, Geisterkugel fliegt', 'die Krähe krächzt'],
      hit: ['die Krähe flattert auf'],
      spawn: ['landet in Rauch, die Krähe landet nach ihr'],
      death: ['löst sich in Federn auf, die Krähe fliegt davon'],
    },
    special: { evo: 'Seelen-Evo: Eine zweite, geisterhafte Krähe kreist um sie, der Hut bekommt eine leuchtende Krempe, das Windspiel fliederfarbene Seelenlichter. Seelenfunken bilden die Partikelhülle; beim Heilen leuchtet das Windspiel.' },
  },
  'night-witch': {
    concept: 'Die Nachthexe ist eine träge, spöttische Hexe im mitternachtsfarbenen Mantel. Ihr Hut ist ein kleiner Glockenturm, in dessen Glockenstuhl Fledermäuse schlafen. Läutet die Glocke, fliegen zwei heraus, und mit ihrem Sichelstab schlägt sie selbst zu.',
    unique: 'Der Glockenturm-Hut mit Glocke und Fledermäusen ist einmalig; die Fledermäuse haben dadurch ein Zuhause. Andere Hexen haben eine Krähe oder einen Kessel. Nachthexen anderer Spiele haben Fledermausflügel; diese hat einen Turm-Hut.',
    silhouette: 'Hoch mit schmalem Turm-Hut, der eine offene Glockenstube und ein Spitzdach hat; der Sichelstab bildet einen Haken.',
    mainName: 'Mitternacht (Mantel)',
    accName: 'Mondsilber (Glocke, Sichel)',
    materials: [['Hutmauer', '#4a4060'], ['Glocke', '#c8ccd8'], ['Haut', '#d0c8e0']],
    signature: 'Hut als Glockenturm: Mauerwerk, eine Glocke im offenen Stuhl, Fledermäuse hängen kopfüber.',
    details: {
      kleidung: 'Turm-Hut, Mantel mit Fledermaus-Zackenkragen, spitze Stiefel',
      material: 'Samt, Stein, Silber',
      muster: 'Mauerfugen am Hut, Mondsicheln am Saum',
      schnallen: 'Sichelbrosche',
      abnutzung: 'Spinnweben am Hut',
      accessoires: 'Mantelfutter und Glockenseil (Teamzonen)',
    },
    face: 'Blasses Gesicht mit halb geschlossenen, gelangweilten Augen, dunklen Lippen und spöttischem Mundwinkel.',
    weapon: 'Sichelstab mit Mondsichel-Klinge.',
    anim: {
      idle: ['die Glocke schwingt, eine Fledermaus guckt heraus', 'gähnt'],
      walk: ['schwebender Gang, der Mantel schleift'],
      attack: ['Sichelstab-Hieb mit Drehung'],
      hit: ['Glocke bimmelt, Fledermäuse flattern'],
      spawn: ['landet, die Glocke läutet einmal'],
      death: ['Glocke läutet ein letztes Mal, eine Fledermaus fliegt heraus, sie verblasst'],
    },
    special: { extra: '**Fledermäuse rufen (`char.spawnUnit`):** Die Glocke schwingt stark, zwei Fledermäuse fliegen aus dem Hut.' },
  },
  'mother-witch': {
    concept: 'Die Hexenmutter ist eine resolute Hexen-Oma mit Lockenwicklern unter dem Hut und einem Kessel-Rucksack, in dem Fluchsud blubbert. Mit der Schöpfkelle schleudert sie Fluch auf Gegner. Wer verflucht stirbt, wird zum Ferkel.',
    unique: 'Kessel-Rucksack und Schöpfkelle sind einmalige Küchenzauber-Geräte; die Lockenwickler sind ihr übertriebenes Merkmal. Die Hexe hat eine Krähe, die Nachthexe einen Turm-Hut. Hexenmütter anderer Spiele tragen Schleier; diese trägt Kittelschürze und Wickler.',
    silhouette: 'Dreieck mit breitem Rock, hinten ein runder Kessel, der über die Schultern ragt, die Kelle als Stab.',
    mainName: 'Oliv (Kleid, Hut)',
    accName: 'Fluchrosa (Sud, Wickler)',
    materials: [['Kessel', '#3a3640'], ['Haut', '#d8c4b8'], ['Kelle (Kupfer)', '#c87a3a']],
    signature: 'Ein schwarzer Kessel als Rucksack mit rosa blubberndem Fluchsud und Dampfblasen.',
    details: {
      kleidung: 'Kittelkleid mit Schürze, Hut mit breiter Krempe, Pantoffeln',
      material: 'Wolle, Gusseisen, Kupfer',
      muster: 'Blümchenschürze, Strickmuster am Schultertuch',
      schnallen: 'Kesselgurte',
      abnutzung: 'Sudflecken',
      accessoires: 'Schultertuch und Hutschleife (Teamzonen), Lockenwickler',
    },
    face: 'Runzliges, rundes Gesicht mit Brille, gerunzelter Stirn und drohend gespitzten Lippen.',
    weapon: 'Kupferne Schöpfkelle.',
    anim: {
      idle: ['rührt im Rückenkessel und schnuppert'],
      walk: ['watschelnd, der Kessel schwappt'],
      attack: ['Kelle in den Kessel (Anticipation), Fluchsud schleudern'],
      hit: ['Brille rutscht, ein Wickler fällt heraus'],
      spawn: ['landet, Dampf steigt'],
      death: ['Kessel kippt, rosa Dampf hüllt sie ein'],
    },
  },
  'magic-archer': {
    concept: 'Der Magieschütze ist ein verträumter Sterngucker mit einem Astrolabium-Hut aus Messingringen und einem Bogen mit Fernrohr-Visier. Er zielt durch das Fernrohr und schießt Lichtpfeile, die alles in einer Linie durchschlagen.',
    unique: 'Der Fernrohr-Bogen und die Messingringe an der Hutkrempe (Astrolabium) sind einmalig; andere Schützen haben Fächerköcher, Muskete oder Harfenbogen. Magische Bogenschützen anderer Spiele tragen grüne Kapuzen; dieser trägt nachtviolett mit Messing.',
    silhouette: 'Schlank, breiter Hut mit Ringen, der Bogen mit seitlichem Fernrohr.',
    mainName: 'Nachtviolett (Mantel)',
    accName: 'Sternengold',
    materials: [['Messing', '#c8a046'], ['Haut', '#e8c4a0']],
    signature: 'Ein Bogen mit Messing-Fernrohr als Visier; beim Zielen fährt das Fernrohr aus.',
    details: {
      kleidung: 'Mantel mit Sternkarte im Futter, Astrolabium-Hut, Stiefel',
      material: 'Samt, Messing, Glas',
      muster: 'Sternbilder, Gradeinteilung an den Ringen',
      schnallen: 'Messingschnallen',
      abnutzung: 'Kratzer an der Linse',
      accessoires: 'Hutband und Umhangfutter (Teamzonen)',
    },
    face: 'Verträumte Augen, ein Auge vergrößert hinter dem Fernrohr, leichtes Lächeln.',
    weapon: 'Fernrohr-Bogen mit Lichtpfeilen.',
    anim: {
      idle: ['schaut durch das Fernrohr in den Himmel'],
      walk: ['schlendernder Schritt, die Ringe klappern'],
      attack: ['Fernrohr ausfahren und zielen (Anticipation), Lichtpfeil in gerader Linie'],
      hit: ['Ringe drehen sich wild'],
      spawn: ['landet, die Ringe kreisen'],
      death: ['löst sich in Sternenstaub auf'],
    },
  },
  executioner: {
    concept: 'Der Scharfrichter ist ein hagerer, unheimlich stiller Riese in einer Lederschürze mit einer runden Eisenmaske, die zwei Gucklöcher hat. Seine Sichelaxt hängt an einer Kette. Er wirft sie wie einen Bumerang, und sie trifft auf Hin- und Rückweg.',
    unique: 'Die an einer Kette fliegende Sichelaxt und die runde Lochmaske sind einmalig; die Kette bildet einen Bogen um ihn. Scharfrichter anderer Spiele tragen Kapuzen; dieser trägt eine runde Eisenmaske mit Gucklöchern und summt.',
    silhouette: 'Hoch und hager mit langen Beinen; runde Maske, Schürze bis zu den Knien, Axt an langer Kette.',
    mainName: 'Dunkelleder (Schürze)',
    accName: 'Messing (Axtrand, Maskenrand)',
    materials: [['Maske', '#5a5f6b'], ['Kette', '#7a828e'], ['Hemd', '#d8ccb4']],
    signature: 'Eine Sichelaxt an einer langen Kette, die er um sich kreisen lässt.',
    details: {
      kleidung: 'runde Eisenmaske, Lederschürze, Hemd mit hochgekrempelten Ärmeln, Stiefel',
      material: 'Leder, Eisen, Leinen',
      muster: 'Kettenglieder, Nieten',
      schnallen: 'Schürzenriemen',
      abnutzung: 'Rost an der Maske',
      accessoires: 'Schulterband und Kettenschleife (Teamzonen)',
    },
    face: 'Nur zwei runde Gucklöcher mit leuchtenden Augen und ein schmaler Schlitz; er neigt den Kopf.',
    weapon: 'Sichelaxt mit halbmondförmiger Klinge an einer Kette.',
    anim: {
      idle: ['lässt die Axt an der Kette pendeln, summt'],
      walk: ['lange, langsame Schritte'],
      attack: ['Drehung (Anticipation), die Axt fliegt im Bogen hinaus und kommt in die Hand zurück'],
      hit: ['Maske scheppert'],
      spawn: ['landet, die Kette klirrt'],
      death: ['fällt nach vorn, die Kette rasselt'],
    },
    special: { evo: 'Nahfeld-Evo: Eine zweite Kette mit Gegengewicht, eine glühende Schneide und eine Schürze mit Eisenplatten. Kettenfunken bilden die Partikelhülle; nahe Treffer erzeugen einen Stoßring.' },
  },
  monk: {
    concept: 'Der Mönch ist ein heiterer, unerschütterlicher alter Kämpfer aus einem Bergkloster. Er trägt einen großen Bronzegong auf dem Rücken und eine Gebetskette mit großen Holzperlen. Er kämpft mit Handflächenstößen; jeder dritte Schlag dröhnt wie ein Gong.',
    unique: 'Der Bronzegong auf dem Rücken ist ein großer Kreis hinter der Figur, den sonst niemand hat; die pflaumenfarbene Kutte ist einmalig. Kämpfende Mönche anderer Spiele sind kahl und orange; dieser trägt Pflaume und hat einen weißen Zopfbart.',
    silhouette: 'Breit mit großem Kreis (Gong) hinter dem Rücken; die Hände sind riesige Handflächen, die Kutte hat weite Ärmel.',
    mainName: 'Pflaume (Kutte)',
    accName: 'Bronze (Gong, Perlen)',
    materials: [['Bart', '#f2efe6'], ['Haut', '#e0b08a'], ['Holzperlen', '#8a5a32']],
    signature: 'Ein Bronzegong an einem Holzgestell auf dem Rücken; bei der Fähigkeit dreht er ihn vor sich als Spiegelschild.',
    details: {
      kleidung: 'Kutte mit weiten Ärmeln, Schärpe, Strohsandalen',
      material: 'Leinen, Bronze, Holz',
      muster: 'Wolkenmuster am Saum, Gong-Relief',
      schnallen: 'Knotenschärpe',
      abnutzung: 'geflickte Ärmel',
      accessoires: 'Schärpe und Gebetskette-Quaste (Teamzonen)',
    },
    face: 'Freundliche Lachfalten, geschlossene lächelnde Augen, langer weißer Zopfbart und buschige Brauen.',
    weapon: 'Riesige Handflächen; der dritte Schlag dröhnt mit Gong-Echo.',
    anim: {
      idle: ['streicht sich den Bart, die Gebetskette klackert'],
      walk: ['ruhiger, gleitender Schritt'],
      attack: ['Kombo: zwei Handflächenstöße, beim dritten Gongschlag (Anticipation tiefer)'],
      hit: ['lächelt weiter, der Gong summt'],
      spawn: ['landet in Meditationspose'],
      death: ['setzt sich im Lotussitz und verblasst lächelnd'],
    },
    special: {
      ability: 'Nachdenklicher Schutz: Er dreht den Gong vor sich und schlägt ihn an (Pose). Event `char.ability.monk` erzeugt Klangringe; Geschosse prallen am Gong ab.',
      aura: 'Bronzefarbene Bodenaura mit Wolkenwirbeln; beim dritten Schlag `char.strike` mit Gong-Ring.',
    },
  },
  'spirit-empress-ground': {
    concept: 'Die Spirit Empress zu Fuß ist eine würdevolle Geisterkaiserin in einer jadegrünen Seidenrobe mit bodenlangen Ärmeln. Auf dem Kopf trägt sie eine Laternenkrone, um die kleine Lichter schweben. Sie kämpft mit einem Seidenfächer, der Geisterwellen schlägt.',
    unique: 'Die Laternenkrone mit kreisenden Lichtern und die bodenlangen Seidenärmel sind einmalig; nur sie hat eine zweite Gestalt als Reiterin. Andere Königinnen tragen Krausen oder Sarkophage. Geisterkaiserinnen anderer Spiele tragen Lila; diese trägt Jade mit Laternenorange.',
    silhouette: 'Dreieck aus Robe mit herabfallenden Ärmeln, oben eine Krone aus drei kleinen Laternen, seitlich der Fächer.',
    mainName: 'Jade (Robe)',
    accName: 'Laternenorange (Lichter, Säume)',
    materials: [['Haut', '#f0dcd0'], ['Haar', '#1e1a2a'], ['Fächer', '#f6efe0']],
    signature: 'Eine Krone aus drei kleinen Papierlaternen, um die Lichter kreisen.',
    details: {
      kleidung: 'Seidenrobe mit Wolkensaum, breite Schärpe, Seidenschuhe',
      material: 'Seide, Papier, Lack',
      muster: 'Wolken und Wellen, Laternengitter',
      schnallen: 'Jadeschnalle',
      abnutzung: 'keine',
      accessoires: 'Ärmelsaum und Fächerquaste (Teamzonen)',
    },
    face: 'Ovales Gesicht mit geheimnisvollem Lächeln und halb geschlossenen Augen; das Haar ist zu einem Knoten mit Nadeln gesteckt.',
    weapon: 'Seidenfächer mit Laternenmotiv.',
    anim: {
      idle: ['fächelt, die Lichter kreisen'],
      walk: ['gleitender Schritt, die Ärmel schleifen'],
      attack: ['Fächer schließen (Anticipation), Fächerschlag mit Geisterwelle'],
      hit: ['Lichter flackern'],
      spawn: ['erscheint aus Laternenlicht'],
      death: ['löst sich in aufsteigende Laternen auf'],
    },
  },
  'spirit-empress-air': {
    concept: 'Die Spirit Empress auf dem Drachen reitet einen langen Nebelband-Drachen aus perlrosa Dunst. Der Leib wogt in Wellen durch die Luft. Drache und Kaiserin stoßen gemeinsam Geisterwellen aus.',
    unique: 'Ein schlangenartiger Drache als endloses Nebelband mit Reiterin ist die einzige S-förmige Silhouette im Spiel; andere Drachen haben Flügel. Fliegende Kaiserinnen anderer Spiele reiten geflügelte Tiere; dieser Drache fliegt ohne Flügel als Band.',
    silhouette: 'S-förmiger Nebelleib mit kleinem Drachenkopf vorn und Bartfäden; in der Mitte sitzt die Kaiserin mit Laternenkrone.',
    mainName: 'Perlrosa (Nebelleib)',
    accName: 'Laternenorange (Kaiserin, Lichter)',
    materials: [['Jade (Kaiserin)', '#3fb07c'], ['Drachenmähne', '#fff4fb']],
    signature: 'Ein Drachenleib aus Nebelbändern ohne Flügel, der sich wellenförmig bewegt; auf ihm sitzt die Kaiserin.',
    details: {
      kleidung: 'Kaiserin in Jade-Robe mit Laternenkrone',
      material: 'Nebel, Seide',
      muster: 'Wolkenlocken im Leib',
      schnallen: 'Zügelband aus Seide',
      abnutzung: 'keine',
      accessoires: 'Zügelband und Ärmelsaum (Teamzonen)',
    },
    face: 'Drachenkopf mit langen Bartfäden, ruhigen runden Augen und offenem Maul; die Kaiserin lächelt.',
    weapon: 'Geisterwelle aus dem Drachenmaul.',
    anim: {
      idle: ['Leib wogt in Wellen'],
      walk: ['schlängelnder Flug'],
      attack: ['Kopf zurück (Anticipation), Geisterwelle'],
      hit: ['Nebel verwirbelt'],
      spawn: ['formt sich aus Nebel'],
      death: ['Nebel löst sich auf, die Kaiserin verblasst'],
    },
  },
};
